### ISSUE TITLE
commit_on_close: false doesn't show prompt if using command mode

### ISSUE THREAD

**Issue by asfaltboy** [timbrel/GitSavvy#1010]
If we want the prompt shown, then it should show regardless of "vim mode" IMHO.

Please include the following information when filing a bug:

- Steps to reproduce: 1. make change and enter commit view, 2. add some words and exit editing mode (e.g hit <kbd>esc</kbd>), 3. hit "super+w" to close tab, it closes without any prompt.
- Sublime Text version number: dev branch (6ac8f3e)
- Git version number: 2.16
- OS type and version: MacOS 10.13.6
- Console error output: -

I worked around this by modifying my keybindings to remove the `setting.command_mode` condition, here's a sample diff:

```diff
 Default (OSX).sublime-keymap | 1 -
 1 file changed, 1 deletion(-)

diff --git a/Default (OSX).sublime-keymap b/Default (OSX).sublime-keymap
index 2b58686..e86cdef 100644
--- a/Default (OSX).sublime-keymap	
+++ b/Default (OSX).sublime-keymap	
@@ -25,7 +25,6 @@
         "keys": ["super+w"],
         "command": "gs_commit_view_close",
         "context": [
-            { "key": "setting.command_mode", "operator": "equal", "operand": false },
             { "key": "setting.git_savvy.commit_view", "operator": "equal", "operand": true }
         ]
     },
```

Can submit a PR if it makes sense to everyone...

**Comment by randy3k** [comment]
Should we override the `ctrl+w` on Windows/Linux too? I am not a vintage/vintageous user and I can't tell.

**Comment by stoivo** [comment]
Do you usesaly close buffers in vim mode with super+w? if so I think this patch is good

**Comment by asfaltboy** [comment]
@stoivo I alternate between vim modes and occasionally hit super+w without thinking which mode I am in, and I'm in command_mode and it makes me lose my commit message (since the buffer is discardable and our `gs_commit_view_close` command doesn't fire).

@randy3k we should definitely update the other OS keybinding files too.

One other thing that happens to me a lot, is that I would have a commit tab open, and then I find that I have too many tabs, want to declutter to read through the changes again before committing, and I use "close all tabs" , which doesn't launch our `commit_view_close` command once again 😞 , though not sure there's a way to solve this without writing my own close all command that wraps around these two (depending on some information about the tab)

**Comment by randy3k** [comment]
Maybe we could add an eventlisenter to emit `commit_view_close` when the view is closing and `commit_view_close` has not yet be executed.

**Comment by kaste** [comment]
This has been implemented afaik.
