### ISSUE TITLE
Git blame does not always work

### ISSUE THREAD

**Issue by oerp-odoo** [timbrel/GitSavvy#1011]
- Sublime Text version number: 3.1.1 3176
- Git version number: 2.7.4
- OS type and version: Ubuntu 16.04.5 LTS
- Console error output:
```
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 1072, in run_
    return self.run(edit)
  File "/home/oerp/.config/sublime-text-3/Installed Packages/GitSavvy.sublime-package/core/commands/blame.py", line 165, in run
  File "/home/oerp/.config/sublime-text-3/Installed Packages/GitSavvy.sublime-package/core/commands/blame.py", line 217, in get_content
  File "/home/oerp/.config/sublime-text-3/Installed Packages/GitSavvy.sublime-package/core/commands/blame.py", line 260, in parse_blame
AttributeError: 'NoneType' object has no attribute 'groups'
```
- A description of the problem.
On one of the source files, I tried to run git blame, but it just opens empty git blame. By looking at console output, I can see something went wrong. If I run git blame on same file with raw git, it does open it normally.
- Steps to reproduce, if possible
I don't know what is the difference on that specific file, but other files seem to run fine with git blame except the one I found the issue with.
- If the bug is caused by a failing command, [include a debug log](https://github.com/divmain/GitSavvy/blob/master/docs/debug.md#providing-a-debug-log).

[gitsavvy-git-blame-debug.json.zip](https://github.com/divmain/GitSavvy/files/2404222/gitsavvy-git-blame-debug.json.zip)

**Comment by randy3k** [comment]
It seems that the blame parser failed to read the blame data.

**Comment by asfaltboy** [comment]
@oerp-odoo please provide us the debug log, with at least the actual git command that returned that "breaking blame content" (instructions are in the link on the last line of your ticket description). If you cannot provide the content (because e.g it's private), please provide us a few lines of example from your CLI git blame that works on that file.

Now for more details. It seems that on that line 260 line in the code:

https://github.com/divmain/GitSavvy/blob/master/core/commands/blame.py#L258-L262

We're assuming `r"([0-9a-f]{40}) (\d+) (\d+)( \d+)?"` is not matched, so depending on your settings, `git blame -p` should return lines that fit that regex. But it's evident that your git returns something else. Now we just gotta figure out what and why.

**Comment by oerp-odoo** [comment]
@asfaltboy yes unfortunately that code is from private repo, so I can't share debug info (cause it captures whole code). And by CLI git you mean using raw git, to show you some running blame sample on that file? Or you need something else?

**Comment by stoivo** [comment]
What we want to do is to 'enable logging', run git blame on the file which is failing, disable logging and view recorded log. Then you can manually strip the private information.   
That would be the preferd for us. Alternatively you need to find a other repository wich is fails for you and you can share everithing.

**Comment by oerp-odoo** [comment]
I uploaded file with debug info. Parts with `[...]` have content striped, though I left some fragments of code. Maybe it will help.

**Comment by stoivo** [comment]
Maybe this normalize is making trouble. https://github.com/divmain/GitSavvy/blob/3372083e4e5db67824dd4bf718f1806f64d7a4d0/core/commands/blame.py#L216-L216
Can you check if you have this issue on a public repositroy it would make it a lot easier for us to work with?

**Comment by oerp-odoo** [comment]
There are no problems with public repos. Actually I can run git blame on any other file on that same private repo, except that one were I encountered this issue. I think there is something specifically in that file, that is not read correctly.

**Comment by asfaltboy** [comment]
I'm concerned that our code is brittle to your input, let's try to debug it more... If you can install the GitSavvy plugin from this repo (instead of from packagecontro.io), and add a few print lines in the function `parse_blame` in `core/commands/blame.py` (like below).

If you don't manage to install from the repo, please produce the output for your file using `git blame -p -M -- <filename> > test.txt` and then run the function to see which line breaks:

```python
import re
import unicodedata
from collections import defaultdict

COMMIT_HASH_LENGTH = 12


def parse_blame(blame_porcelain):
    lines_iter = iter(blame_porcelain)

    commits = defaultdict(lambda: defaultdict(str))

    for line in lines_iter:
        print(line)
        commit_hash, orig_lineno, final_lineno, _ = \
            re.match(r"([0-9a-f]{40}) (\d+) (\d+)( \d+)?", line).groups()
        commits[commit_hash]["short_hash"] = commit_hash[:COMMIT_HASH_LENGTH]
        commits[commit_hash]["long_hash"] = commit_hash

        next_line = next(lines_iter)
        while not next_line.startswith("\t"):
            # Iterate through header keys and values.
            print(next_line)
            try:
                k, v = re.match(r"([^ ]+) (.+)", next_line).groups()
            except AttributeError as e:
                # Sometimes git-blame includes keys without values;
                # since we don't care about these, simply discard.
                print("Skipping blame line: " + repr(next_line))
            commits[commit_hash][k] = v
            next_line = next(lines_iter)

        # If `next_lines` starts with a tab (and breaks out of the above
        # while loop), it is an actual line of code.  The line following
        # that will be a new header or the end of the file.
        print(next_line)
        print(
            dict(
                contents=next_line[1:],
                commit_hash=commit_hash,
                orig_lineno=orig_lineno,
                final_lineno=final_lineno
            )
        )


parse_blame(open('test.txt').read().splitlines())
```

**Comment by oerp-odoo** [comment]
I ran plugin after generating file with `git blame -p -M`. This is the last lines till it breaks:

```
....
....
{'final_lineno': '438', 'orig_lineno': '274', 'commit_hash': '3af032ed3d31c443666ee93162b32794144c9d85', 'contents': '    @api.one'}
1e2382e82f32504a7bd1781049363cb0d9089eaf 199 439 7
	    @api.depends(
{'final_lineno': '439', 'orig_lineno': '199', 'commit_hash': '1e2382e82f32504a7bd1781049363cb0d9089eaf', 'contents': '    @api.depends('}
1e2382e82f32504a7bd1781049363cb0d9089eaf 200 440
	        'buffer',
{'final_lineno': '440', 'orig_lineno': '200', 'commit_hash': '1e2382e82f32504a7bd1781049363cb0d9089eaf', 'contents': "        'buffer',"}
1e2382e82f32504a7bd1781049363cb0d9089eaf 201 441
	        'start_time',
{'final_lineno': '441', 'orig_lineno': '201', 'commit_hash': '1e2382e82f32504a7bd1781049363cb0d9089eaf', 'contents': "        'start_time',"}
1e2382e82f32504a7bd1781049363cb0d9089eaf 202 442
	        'date_deadline',
{'final_lineno': '442', 'orig_lineno': '202', 'commit_hash': '1e2382e82f32504a7bd1781049363cb0d9089eaf', 'contents': "        'date_deadline',"}
1e2382e82f32504a7bd1781049363cb0d9089eaf 203 443
	        'opportunity_completed',
{'final_lineno': '443', 'orig_lineno': '203', 'commit_hash': '1e2382e82f32504a7bd1781049363cb0d9089eaf', 'contents': "        'opportunity_completed',"}
1e2382e82f32504a7bd1781049363cb0d9089eaf 204 444
	        'time_consumed',
{'final_lineno': '444', 'orig_lineno': '204', 'commit_hash': '1e2382e82f32504a7bd1781049363cb0d9089eaf', 'contents': "        'time_consumed',"}
1e2382e82f32504a7bd1781049363cb0d9089eaf 205 445
	    )
{'final_lineno': '445', 'orig_lineno': '205', 'commit_hash': '1e2382e82f32504a7bd1781049363cb0d9089eaf', 'contents': '    )'}
07b1deb8735027147cf367e90e9769646dfb7a16 144 446 1
	    def _compute_buffer_consumed(self):
{'final_lineno': '446', 'orig_lineno': '144', 'commit_hash': '07b1deb8735027147cf367e90e9769646dfb7a16', 'contents': '    def _compute_buffer_consumed(self):'}
1e2382e82f32504a7bd1781049363cb0d9089eaf 207 447 11
	        """Compute percentage of buffer consumed.
{'final_lineno': '447', 'orig_lineno': '207', 'commit_hash': '1e2382e82f32504a7bd1781049363cb0d9089eaf', 'contents': '        """Compute percentage of buffer consumed.'}
1e2382e82f32504a7bd1781049363cb0d9089eaf 208 448
	
{'final_lineno': '448', 'orig_lineno': '208', 'commit_hash': '1e2382e82f32504a7bd1781049363cb0d9089eaf', 'contents': ''}
1e2382e82f32504a7bd1781049363cb0d9089eaf 209 449
	        Formulas:
{'final_lineno': '449', 'orig_lineno': '209', 'commit_hash': '1e2382e82f32504a7bd1781049363cb0d9089eaf', 'contents': '        Formulas:'}
1e2382e82f32504a7bd1781049363cb0d9089eaf 210 450
	
{'final_lineno': '450', 'orig_lineno': '210', 'commit_hash': '1e2382e82f32504a7bd1781049363cb0d9089eaf', 'contents': ''}
1e2382e82f32504a7bd1781049363cb0d9089eaf 211 451
	            if deadline is not specified:
{'final_lineno': '451', 'orig_lineno': '211', 'commit_hash': '1e2382e82f32504a7bd1781049363cb0d9089eaf', 'contents': '            if deadline is not specified:'}
1e2382e82f32504a7bd1781049363cb0d9089eaf 212 452
	                2 * (Opportunity time consumed % - Opportunity completed %)
{'final_lineno': '452', 'orig_lineno': '212', 'commit_hash': '1e2382e82f32504a7bd1781049363cb0d9089eaf', 'contents': '                2 * (Opportunity time consumed % - Opportunity completed %)'}

Traceback (most recent call last):
  File "git-blame-plugin.py", line 47, in <module>
    parse_blame(open('blame-debug.txt').read().splitlines())
  File "git-blame-plugin.py", line 16, in parse_blame
    re.match(r"([0-9a-f]{40}) (\d+) (\d+)( \d+)?", line).groups()
AttributeError: 'NoneType' object has no attribute 'groups'
```

Last line if actually a line of method dosctring.

Full dosctring of that method looks like this:
```
        """Compute percentage of buffer consumed.

        Formulas:

            if deadline is not specified:
                2 * (Opportunity time consumed % - Opportunity completed %) 

            if deadline is specified:
                (Opportunity Deadline - Opportunity Start time) * 0,5 / Buffer)
                * (Opportunity time consumed % - Opportunity completed %) 
        """
```
Maybe it has something to do with `%` being in comments?

**Comment by asfaltboy** [comment]
Great job, thank you for pasting the code, the issue seems to be with the line:
```
2 * (Opportunity time consumed % - Opportunity completed %)\u2028\n\n'
```

As you can see there's a funny looking unicode character there (it also occurs in the last line of the docstring). The [U+2028 unicode character][1] is a line separator char, and [python's `splitlines()` splits by this symbol by default][2] (along with some other chars), thus creating a new line-break where we don't expect it (git does not break the line by this symbol).

A possible fix could be to use `str.replace(os.linesep)` instead, which will produce the right kind of output for our parsing function (at least on my machine - we'll need to test on different OSes and different linux / mac / windows EOL symbols).

[1]: https://www.fileformat.info/info/unicode/char/2028/index.htm
[2]: https://stackoverflow.com/a/18325046/484127

**Comment by oerp-odoo** [comment]
I see. github also shows that with weird symbol at the end of those lines (`[]`) where I copy/pasted docstring.

**Comment by asfaltboy** [comment]
I'm looking at the [git blame.c source][1], and it seems it always adds breaks with `\n`, so we can rely on those to be constant irregardless of source file's actual line-break symbols.

Thus, I think we should be safe by changing `splitlines()` to `.split('\n')`. I'll submit a small PR to start discussion on the fix.

[1]: https://github.com/git/git/blob/master/blame.c

**Comment by oerp-odoo** [comment]
As an off-topic, I removed those funny characters (don't even know how that symbol got in a first place. Though my guess is someone used some other editor which polluted docstring and it was committed that way) from method docstring and it also solved other problem I had with that file: some parts of code showed incorrect syntax or style according to flake8 and pydocstyle, but in reality those parts were correct (just plugins showed it incorrectly).

I guess other plugins also have this problem with those weird unicode characters and then starts working incorrectly.

**Comment by kaste** [comment]
This looks like some PR has been merged *long, long* ago to resolve this
