### ISSUE TITLE
Feature Request: Commit with an older date

### ISSUE THREAD

**Issue by dufferzafar** [timbrel/GitSavvy#1017]
I frequently need to commit with a past date (I can go into the reasons if you want me to, but I feel that's not relevant.)

This is pretty much the only thing that requires me to use git outside of Sublime. 

I have a shell function called `gdate` ([you can see the source here](https://github.com/dufferzafar/dotfiles/blob/master/zsh/aliases.git.zsh#L119-L138)) which sets the `$GIT_AUTHOR_DATE` and `$GIT_COMMITTER_DATE` for that session.

So after that whenever I run `git commit` from the shell, it will commit with a previous date.

Is there any way to obtain same functionality with Savvy?

It's okay if you don't want to add this into Savvy itself as not many people would want such a thing, I'll be happy if I can make it work just for me. 

Ideally, I would want two new commands `git: change date environment` which would change it to some date (so that all further commits happen with this value) and `git: reset date environment` so that things can go back to normal.

**Comment by asfaltboy** [comment]
IIRC we use `os.environ` to populate the git process environment on launch. This means that it should be enough for you to set the variables in sublime for this feature to work.

Please try it out by opening a sublime console (<kbd>ctrl</kbd>+<kbd>`</kbd>) and entering e.g: `os.environ['GIT_COMMITTER_DATE'] = '2005-04-07T22:13:13'`. Then run the usual `git: commit` command and see if that sets the committer date correctly.

If the above works, all we need is a simple command that will set the environment variables on demand... maybe someone knows of a plugin that will do it, as I don't really see this requirement as specific to git or GitSavvy. If we really wanted to, we could modify `GsCustomCommand` to support environment variables and not just arguments, but not sure it's in scope.

**Comment by asfaltboy** [comment]
**Update**: I spend a bit of time fiddling around, and the result is a fun little plugin to let you write whatever python code you want and execute it via a command: https://github.com/asfaltboy/sublime-custom-code

**Comment by dufferzafar** [comment]
Wow, thanks a lot for this @asfaltboy!

I'll test it out today and see how it works out.

**Comment by kaste** [comment]
This is not planned as it's too idiosyncratic.  You can change the `ENV` at anytime with any means and we will follow already.  We just don't add an UI for that.  We just want to be flexible enough that people *could* write their own add-ons.
