### ISSUE TITLE
Attempt to add file change age to status

### ISSUE THREAD

**Issue by lttlrck** [timbrel/GitSavvy#1019]
I need some help. I want to add the file change age to the status and although I got it working it broke shortcuts such as open, stage single file etc.

This is what it looks like:

![image](https://user-images.githubusercontent.com/779029/46237521-da6e1600-c339-11e8-9eb5-8da3ffe0f558.png)

The change afters several slices e.g. `line[:4]` and `line[4:]` throughout `core/interfaces/status.py` and although I tried correcting them, it didn't fix the problems.

Have I gone about this the wrong way? Am I missing something in additional to these slices? I'm a little confused about regions, and how exactly the file selection works. I rarely touch Python.

This the commit that has the changes I made (minus any slice adjustments as they didn't solve anything):

https://github.com/lttlrck/GitSavvy/commit/1e9b3b6c5b15b40491da08ce4018ffc3baec2052

Any help would be greatly appreciated, this feature it pretty useful for finding associated commits (though branches are better, sometimes things get out of hand :smiley: )

**Comment by asfaltboy** [comment]
Thats a nice feature @lttlrck , thanks for working on it! How about submitting a PR and we can discuss the development in detail?

Now, about the keyboard bindings; these are specified in the `.sublime-keymap` files, like this one:
https://github.com/divmain/GitSavvy/blob/de9caff3222924ce4fd6a71a1f4f2804126f2c84/Default.sublime-keymap#L107-L119

As you can see the context selector uses the `git-savvy.status` to specify which view the bindings are valid on. The `status.sublime-syntax` file specifies how scope for each row is matched:
https://github.com/divmain/GitSavvy/blob/9ec1cc44455a11e1dfef89629fc7c4e8c01f6a57/syntax/status.sublime-syntax#L46-L58

I guess the number of spaces there doesn't match with the date added.

**Comment by lttlrck** [comment]
thanks for help, looks much better. I made a PR.
