### ISSUE TITLE
"Review pull request" branch name default

### ISSUE THREAD

**Issue by stevage** [timbrel/GitSavvy#1024]
1. Choose "review pull request", select a branch inside the main repo, called "foostuff" by "hacker".
2. Choose "Checkout as local branch".
3. The branch "hacker/foostuff" gets created.
4. Making a change and commit it. (Happens with some reviewing workflows).
5. Go to push the branch. The branch name "hacker/foostuff" is suggested, even though the correct branch name would be "foostuff".

This can be confusing, because

a) it looks like "my" branch (it has commits unique to me) yet it's named after someone else
b) it looks like an external pull request, even though "hacker" is a member of the repo.

**Comment by kaste** [comment]
This has been implemented
