### ISSUE TITLE
Aborting rebase shows the wrong message

### ISSUE THREAD

**Issue by stevage** [timbrel/GitSavvy#1025]
I started doing a rebase, then aborted from the REBASE screen (`[A] abort rebase`). Now the top two lines read:

```
  REBASE:  rebased-barcharts --> basebranch (440c488dd)
  STATUS:  Successfully rebased on top of basebranch. Undo available.
```

(It appears to be true that "undo is available", but I can't see that it did anything.)

- Sublime Text version number: 3.1.1
- Git version number: 2.11.0
- OS type and version: OSX Sierra

**Comment by kaste** [comment]
The rebase dashboard has been deprecated so I don't investigate and fix this anymore.
