### ISSUE TITLE
Error loading Syntax File when running GitSavvy: Help

### ISSUE THREAD

**Issue by RitikShah** [timbrel/GitSavvy#1028]
Sublime Text: Version 3.1.1 Build 3176
Git version 2.17.1 (Apple Git-112)
Mac OS Mojave (10.14)
Error: `Error loading syntax file "Packages/Markdown/Markdown.sublime-syntax": Apparent recursion within a with_prototype action: 25000 context sanity limit hit`

Description: When I run, GitSavvy: Help in sublime text, the text shows, but the markdown does not.
Steps:
1) Install GitSavvy via Sublime
2) Run Gitsavvy: Help

Log: [] (it had nothing, not sure why) (The error message pop-up is all I get)

**Comment by asfaltboy** [comment]
I guess the JSON code snippet in the first help page fools sublime to believe JS syntax should be set. Perhaps we could "force set" a markdown syntax (if available) falling back to plain text?

**Comment by rchl** [comment]
I can see this happening in ST4 now.
The help file opens as Plain Text and the navigation functionality does not work.
Since the opened view has a name `GITSAVVY HELP` and no extension, I think it only makes sense to assign the syntax manually rather than relying on content being auto-detected.

**Comment by kaste** [comment]
Hi!

We actually assign a syntax, or try to. I know your savvy so could you run  

```
>>> import GitSavvy
>>> GitSavvy.common.util.file.syntax_file_map["md"]
```

On my machine this returns `['Packages/Markdown/Markdown.sublime-syntax']`.

**Comment by rchl** [comment]
That actually gives a key error so there is no `md` in the map.

I do have default Markdown syntax and I can set it manually. Then the syntax setting is `Packages/Markdown/Markdown.sublime-syntax`

**Comment by rchl** [comment]
I've looked at how you set up the map at https://github.com/timbrel/GitSavvy/blob/4aaed3c94cf1d8a21bd3dc7605d9dc1a04145653/common/util/file.py#L28-L40 and while I'm not 100% sure but I feel this could be due to timing issues and `sublime.find_resources("*.sublime-syntax")` not returning all files if called early at load since the database of files is still loading. Could be that it triggers only when there are many files (I have many since I have a lot of `.git` directories in symlinked packages).

**Comment by kaste** [comment]
We have a broad `try except` clause here so we actually can't know.  Have you GitSavvy checked out (or packaged), then you could look into it. `load_resource` or `yaml.safe_load` could fail here as well.  Could be a ST4 regression too.

**Comment by rchl** [comment]
It doesn't fail. It's just that the `GitSavvy.common.util.file.syntax_file_map` list is not complete. It has many items but not markdown.

**Comment by kaste** [comment]
You patched GitSavvy to confirm that nothing fails here?

**Comment by rchl** [comment]
Oh, I see what you mean now. It can fail for each syntax separately. I'll check it out.

**Comment by rchl** [comment]
It fails for a lot of syntaxes but when it comes to Markdown the exception is:
```
could not determine a constructor for the tag 'tag:yaml.org,2002:value'
  in "<unicode string>", line 1496, column 14:
        - match: =
                 ^ Packages/Markdown/Markdown.sublime-syntax
```
More context for that line:
```yaml
  tag-attr-equals:
    - match: =
      scope: punctuation.separator.key-value.markdown
      set: tag-attr-value
    - include: else-pop
```

**Comment by kaste** [comment]
Okay, for ST4 we can use new API endpoints mentioned here: https://github.com/sublimehq/sublime_text/issues/2186#issuecomment-592959093

**Comment by kaste** [comment]
For ST3, we could naive parse e.g. extract full match from `^file_extensions:\n((.*\n)+?)^(?=\w)` and put it into `yaml.safe_load(s)`.
