### ISSUE TITLE
Cannot unstage renamed files

### ISSUE THREAD

**Issue by kaste** [timbrel/GitSavvy#1042]
- Rename a file
- Open status dashboard
- Stage both the new untracked and the old deleted file
- Staged area show something like this: `    popups/blame_view.html -> popups/blame_view_bogus.html`
- Try to unstage, status bar indicates success, but nothing happens

Actually invokes

```
  {
    "type": "git", 
    "seconds": 0.13777518272399902, 
    "stderr": "", 
    "stdout": "Unstaged changes after reset:\nM\tcore/interfaces/status.py\n", 
    "command": [
      "reset", 
      "HEAD", 
      "popups/blame_view.html -> popups/blame_view_bogus.html"   # <- Ouch
    ], 
    "stdin": null
  }, 
```

**Comment by asfaltboy** [comment]
I've had this happen to me but just left it out and ultimately forgot about it.
