### ISSUE TITLE
disable git status badge in Sublime Text build 3181

### ISSUE THREAD

**Issue by randy3k** [timbrel/GitSavvy#1066]
Since build 3181, sublime text comes with its own git status badge, shall we automatically disable our own badge for build >=3181 and the setting `show_git_status` is on?

**Comment by stoivo** [comment]
screenshot?

**Comment by asfaltboy** [comment]
![image](https://user-images.githubusercontent.com/321520/49857063-da869980-fdf1-11e8-918f-3aea2050d5fa.png)

See the two branch names in the bottom status line ^

**Comment by randy3k** [comment]
I ended up disabling the sublime text git badge because it doesn't show the `+` and `-`.

**Comment by randy3k** [comment]
I agree. I would love to have an api to control the status bar.

**Comment by kaste** [comment]
I'm not inclined to change the default here atm.  I like what we do here.  It's helpful if you're behind or ahead upstream, and also shows rebase information...
