### ISSUE TITLE
Bug: branch interface doesn't open graph for selected branch

### ISSUE THREAD

**Issue by asfaltboy** [timbrel/GitSavvy#1072]
When in branch interface, hit `[g]` to open graph under for the branch under the cursor. Instead, the graph view opens with the checked out branch, not the branch under cursor.

- Sublime Text 3 3184
- Git 2.19.1
- OS type and version 10.14.1 (18B75)
- Console error output -nothing

Git bisect points at 6a6c612 as the culprit, and we can see the `LogGraphMixin` command no longer uses `get_graph_args`, and users of the mixin need to use `prepare_target_view` to set additional graph arguments as view settings.

**Comment by kaste** [comment]
Closing. Should be fixed.
