### ISSUE TITLE
git: graph all is missing from the commands and settings

### ISSUE THREAD

**Issue by mrmeszaros** [timbrel/GitSavvy#1085]
# Asks

* sublime-command entry for showing `git: graph all`.
* sublime-settings entry for configuring whether the BRANCH tab shows "--all"

# Status

* The python class: [GsLogGraphAllBranches](https://github.com/divmain/GitSavvy/blob/de9caff3222924ce4fd6a71a1f4f2804126f2c84/core/commands/log_graph.py#L87)
* No sublime-commands entry
  - it seems [this commit](https://github.com/divmain/GitSavvy/commit/cda8d550525ab5a0ec6182ada12363b066017600#diff-db82941e6d15b7a54e5c0eb5ef1f756b) broke it
* No sublime-settings entry
  - [this comment line](https://github.com/divmain/GitSavvy/blob/de9caff3222924ce4fd6a71a1f4f2804126f2c84/GitSavvy.sublime-settings#L258) asks not to add `"--all"` to the args.
  - I was not able to find the point in time, when it was configurable through "all_branches" it mentions.

## History
Here are entries related to the history of `git: graph all`: 

* #179
* #486 
* #523
* #537 
* #538

**Comment by randy3k** [comment]
You could simply add the following command in `Default.sublime-commands`
```
    {
        "caption": "git: graph all",
        "command": "gs_log_graph_all_branches"
    }
```

**Comment by kaste** [comment]
I wanted to improve the log_graph view so that most of this stuff can be changed dynamically. I prefer a common `gs_open_log_graph` (don't remember the name right now) which takes arguments. I would prefer if we had rather less commands in the palette so I don't get naming confusion if I add my own.

**Comment by randy3k** [comment]
> I wanted to improve the log_graph view so that most of this stuff can be changed dynamically.
+1

**Comment by mrmeszaros** [comment]
Good points @kaste !

Just to clarify:
1. I wanted to configure my Graph tab of the status to see all graph branches.
2. Stumbled upon `git_graph_args` in the settings, with the following comment above:
    > Do not add "--all" in this setting, it is added in graph all branches
   However I was not able to find that in the settings, nor in the command palette
3. Did some research in the issue tracker and code history, and created this issue

I am open to other solutions, and also putting effort into cleaning up how this works / can be configured.

**Comment by kaste** [comment]
> I wanted to configure my Graph tab of the status to see all graph branches.

Do you mean the BRANCH special view? Then you can just reassign the `[g]` binding.

```
  {
      "keys": ["g"],
      "command": "gs_log_graph_all_branches",
      "context": [
          { "key": "setting.command_mode", "operator": "equal", "operand": false },
          { "key": "setting.git_savvy.branch_view", "operator": "equal", "operand": true }
      ]
  },
```

We should add this to the status dashboard as well, no, or 👍 ?

**Comment by kaste** [comment]
Closing as commands can be *added* by each user. We still want to do some dynamic toggle but that's a different issue.
