### ISSUE TITLE
[Question] There is something like GitSavvy that can run on the terminal?

### ISSUE THREAD

**Issue by ellipticaldoor** [timbrel/GitSavvy#1125]
I will like to be able to use GitSavvy without sublime,

There is a way of running this plugin from just the terminal?

If this is not posible, there is another cli tool that can accomplish something similar?

**Comment by kaste** [comment]
GitSavvy is a Sublime plugin so in any way even if you invoke something - we had to discuss what this exactly is - from the command line it would first start Sublime.

**Comment by asfaltboy** [comment]
I was actually toying around with the idea of extracting the common commands and views (i.e interfaces) out of sublime into an external app. That app can then expose a local API to both CLI, GitSavvy and other editors (e.g VSCode) to allow for easy construction of the plugins.

Another advantage of such a tool is that it can be more flexible with dependencies and structure to for example:
- retain state of a repo in memory, avoiding IO trips to disk (which are sometimes expensive, e.g see Windows) unless needed.
- cache and/or throttle commands easier

Originally I thought about using [git-go][0] and [grpc][1], but I've had so many issues with building grpc for vscode that I basically rage quitted on the whole idea 😆 ... my main consideration is the ease of async with "goroutines", cross-platform go without needing libgit and my personal interest in using go more.

[0]: https://github.com/src-d/go-git
[1]: https://grpc.io/

If anyone else is interested, let's talk about it

**Comment by ellipticaldoor** [comment]
@asfaltboy did you know about this project? https://github.com/jesseduffield/lazygit/

Is written with go

**Comment by asfaltboy** [comment]
I have seen it, but never was curious to see what it uses, until now! Happy to see they're using src-d's go-git like I intended to ... Basically I want to use [this sort of code][1], and expose an additional API (probably will need to be http/websocket based)

[1]: https://github.com/jesseduffield/lazygit/blob/master/pkg/git/branch_list_builder.go

**Comment by kaste** [comment]
Closing, not actionable and probably discussed.

**Comment by 3v1n0** [comment]
@asfaltboy I also had the same idea, as also per https://github.com/timbrel/GitSavvy/issues/930#issuecomment-404128021 let me know if you want to hack something :)

**Comment by asfaltboy** [comment]
Let's do it @3v1n0 ! Maybe use simple http or websocket interface to start with, we can use https://github.com/asfaltboy/VSGitSavvy or just scrape and start over. And let's find a place to discuss this outside this ticket :)  I would love to tackle the branch view first as it's loading annoyingly slowly for me
