### ISSUE TITLE
GitSavvy should ignore lines in commit messages that being with #

### ISSUE THREAD

**Issue by kylebebak** [timbrel/GitSavvy#1126]
I'm not sure if this is a bug, but it's definitely unexpected behavior. And it doesn't play well with tools like husky that insert `prepare-commit-msg` strings that aren't meant to be saved in the commit.

GitSavvy 2.18.0
OSX 10.12.6
Git 2.10.2
ST 3197

Basically, lines in a commit message that are prefixed with '#' should be ignored, or there should be a flag to ignore these lines.

Currently, everything starting at and after `## To make a commit` is ignored, but lines before this, such as `# this is a message inserted by a prepare-commit-msg or commit-msg hook, this line should be ignored` **aren't ignored**.

A config flag such as `ignore_commented_commit_message_lines` would be appropriate.

**Comment by kaste** [comment]
We actually had this in dev before 2.18.0, and I strongly insisted to roll back because it was a terrible default for beginners. 

I wonder if we can avoid the obvious "can we have another option" if we just put the prepare commit message below the snip marker.

**Comment by kylebebak** [comment]
Putting the prepare commit message below the snip marker would would obviate the need for an additional option, but it would also mean that people who **want** to add a message to their commits would need to manually move it above the snip marker to include it. Not a great default for those users.

I still think the appropriate fix is ignoring any lines that begin with `#` -- this is exactly what `git` does if you include such lines in a commit message.

I don't think there's a good reason that GitSavvy should behave differently.

**Comment by asfaltboy** [comment]
I can't remember exactly what was changed and why, @kaste could you provide a link to the PR you wanted to rollback ?

As far as I know git allows users to customise the comment character, and it defaults to single '#', but there might be reasons to change it (e.g users might want to reference single issue on a line of it's own to trigger CI / ticket linking on their VCS servers).

The confusing bit is that our syntax renders both lines that start with either single '#' or lines that start with double '##' with a "comment style". Ref: https://github.com/divmain/GitSavvy/blob/9ec1cc44455a11e1dfef89629fc7c4e8c01f6a57/syntax/make_commit.sublime-syntax#L17

**Comment by kylebebak** [comment]
`git` includes lines such as `issue # 35 is not ignored` in the commit message, i.e. as long as the line doesn't **start with #** it's included.

Given that this is the case I think overriding default behavior by including lines that start with `#` is unnecessary, and goes against the principle of least astonishment.

**Comment by kaste** [comment]
Actually we don't override default behavior, we reverted additional code, so what we have right now is the default for the operation mode we use here.

Given GitSavvy is an app, it actually also follows the behavior of GitGUI, GitHub et.al. 

Overall it was just a cheap implementation. Usually you start with an empty "message field" in our commit view, and users can expect that what they type will be the commit message verbatim. We added support for the prepare hooks just now and this is basically a follow-up problem. 

How do these automatic (prepared) message look like actually? I never used this.

@asfaltboy The syntax handling is interesting, I *actually* wrote something like this as a commit message

```
lirum larum                 . See also
#234 which handles ....
```

which then got crippled. Such a line does not appear as comment.

**Comment by kylebebak** [comment]
This what `husky`'s commit-msg or prepare-commit-msg hooks looks like when opening the GitSavvy commit view:

~~~


# Please enter the commit message for your changes. Lines starting
# with '#' will be ignored, and an empty message aborts the commit.
# On branch master
# Your branch is up-to-date with 'origin/master'.
#
# Changes to be committed:
#	modified:   app/screens/SearchScreen/SearchScreen.js
#

## To make a commit, type your commit message and press SUPER-ENTER. To cancel
## the commit, close the window. To sign off on the commit, press SUPER-S.
##
## You may also reference or close a GitHub issue with this commit.  To do so,
## type `#` followed by the `tab` key.  You will be shown a list of issues
## related to the current repo.  You may also type `owner/repo#` plus the `tab`
## key to reference an issue in a different GitHub repo.

 app/screens/SearchScreen/SearchScreen.js | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
~~~

Everything above **## To make a commit...** is actually **included** in the commit, even though all these lines begin with **#**, and husky assures the user that the lines won't be included in the commit.

Again, by default in `git`, a line that begins with a **#** is a comment, and is not included in the commit message.

Unless I'm misunderstanding something very basic, GitSavvy is NOT in line with `git`'s default behavior here, and to my way of thinking that's an issue.

**Comment by kylebebak** [comment]
And again, if I'm understanding correctly, and the reason to include lines that begin with **#** is to allow users to reference issues and so on in the commit message, this is a very

**Comment by kaste** [comment]
To run such a prepare hook actually doesn't make much sense inside a GUI like GitSavvy bc it doesn't provide any information not already on the screen. Maybe we can also get some other examples. 

The comment char is not relevant here, and the instructions GitSavvy puts here are mildly clear in that everything above the fold is the commit message.  

As I said this is a merely a follow-up problem of running this hook. I also don't know any other GUI that actually runs the prepare commit message hook so this might be the issue in the first place.

About the default stuff, really, you can just read it up on the git commit man page.

**Comment by kylebebak** [comment]
Whether or not it makes sense for me, or anyone else, to run a certain msg hook is irrelevant to whether GitSavvy's default behavior of including lines starting with **#** is desirable. And again, these are lines that `git` excludes by default.

Either GitSavvy should have the same default behavior with regard to commit messages as `git`, or GitSavvy should not run the msg hooks.

**Comment by randy3k** [comment]
As a workaround, use the setting

```
    "global_flags": {
        "commit": ["--cleanup=strip"]
    }
```

**Comment by randy3k** [comment]
> I also don't know any other GUI that actually runs the prepare commit message hook so this might be the issue in the first place.

The vim plugin fugitive is doing the same thing
https://vi.stackexchange.com/questions/2544/how-to-manage-fugitive-commit-with-a-git-pre-commit-hook?answertab=votes#tab-top

I already got the inspiration there.

**Comment by kylebebak** [comment]
Using `global_flags` to modify the cleanup behavior worked. Thanks a lot @randy3k !

I really think this should be the default behavior, but given that there's a work-around I think this issue should be closed.

**Comment by randy3k** [comment]
Actually, I am with @kylebebak. However, as @kaste strongly discouraged it and I have reverted the commit fdaddedfdc51878abf157446ea7eb8bbba3c6cd9

The doc says the default cleanup action is
> Same as strip if the message is to be edited. Otherwise whitespace.

However, we are not editing the message via the commit command, instead, we prepare our own message and pass it to `git commit -m "<message>"`. 

So, @kaste is right: keeping leading # is the default behaviour of `git commit -m "<message>"`. And @kylebebak is also not wrong, stripping leading # is the default behaviour of `git commit` in cli.

**Comment by kaste** [comment]
I think that is overall a misleading UX here. If I use the standard pre-commit-hook I now see something like this

![image](https://user-images.githubusercontent.com/8558/55259021-cf525f00-5264-11e9-91d7-b9766057ca8b.png)

We have at the top a somewhat standard commit message as seen when using the cli. After that comes our own message. That's of course confusing.

Now I argue that what we actually do when we initialize the commit view already is a prepare commit message hook. We have a builtin hook, just like git itself has a standard hook which can be altered with custom hooks. We take a 'git diff', our own help message and put it in a buffer.  

Now, the question is: should we even run by default such a custom hook? Who wants that? If so, we need to strip comments bc all custom hooks are written for cli usage and likely follow the '# ' comment marker semantics. If we don't run a hook bc there is none installed or we decide maybe it's not a good idea at all in our context, then we also must follow the standard behavior as seen in GitGUI, GitHub, VSCode... and not strip comments. We must take the message entered in our message 'field' verbatim. 

Aside: I know why figutive does this neat trick; it's not for custom prepare hooks, most of the time there isn't any installed, they just kick in the default, built-into-git 'hook' to get a decent, standard buffer content *without* waiting or locking the index. They follow the cli usage closely. We don't. 

We could also add an option: Use our commit view, or use the standard git commit flow and message. But *our* view should actually outperform the git standard flow. Its diff could be dynamic, and its amend setting as well. 

For comparison, here is the Sublime buffer when I issue a 'git commit -v' on the cli. 

![image](https://user-images.githubusercontent.com/8558/55260027-91a30580-5267-11e9-922a-fb11c903733f.png)

**Comment by kylebebak** [comment]
Also, just wanted to say that the work-around given above is much better than a typical work-around, because it doesn't do anything hacky, and it doesn't require an ad-hoc config flag, like I suggested originally.

Being able to set `global_flags` like that is good design IMO =)

**Comment by IPWright83** [comment]
How do you go about setting the global flags? Is this done via the `gitConfig` file?

**Comment by kaste** [comment]
It's in the GitSavvy settings within Sublime.

**Comment by stevage** [comment]
Ugh. I just got bitten by this. Turns out I have been committing tons of messages with all that "Please enter the commit message for your changes" boilerplate. How embarrassing.

I absolutely love GitSavvy. It's literally the only reason I use Sublime at all, and has been for a couple of years.

But I cannot honestly fathom how there can possibly be any argument about whether the current behaviour is acceptable.

The text literally reads:

> # Please enter the commit message for your changes. Lines starting
> # with '#' will be ignored, and an empty message aborts the commit.
> ...

It says right there "Lines starting with # will be ignored". And they're greyed out. And then they're not ignored at all, they're actually included in the commit message??!

This is awful, awful UX that is worse than just surprising to the user, it bites them in the arse months down the track when they realise they've been spreading ugly embarrassing commit messages across dozens of repos.

Please, please fix this.

**Comment by randy3k** [comment]
Are you using a pre commit hook?

**Comment by stevage** [comment]
This particular repo is, yes. And looking into it, it apparently uses Husky. (I'm not even sure what Husky is).

**Comment by randy3k** [comment]
I guess we need to refactor the UI here https://github.com/timbrel/GitSavvy/blob/6b996ec5434ad0b80da4015b3a4e79b9ede1e056/core/commands/commit.py#L147

so the automatic generated comment would be trimmed away.

**Comment by kaste** [comment]
So, 

1. we MUST fix our syntax because it presents some files as comments which is a lie.

2. we could of course strip comments from the prepare message but then what's the purpose of that message. In the examples above posted everything was commented.

**Comment by kaste** [comment]
Esp. @randy3k since you initially implemented this. Do you have a useful precommit hook running?

**Comment by randy3k** [comment]
I was also testing it with the standard pre-commit hook.

I guess we could perpare the UI as


```
<message from COMMIT_EDITMSG>

------------>8----------------

<Our help text>

<comments from COMMIT_EDITMSG>

```

Upon committing, any text after `------------>8----------------` will be trimmed.

**Comment by kaste** [comment]
I'm inclined to revert to the previous state we had.

A couple of problems: 

- With the current system (t.i. running the prepare-msg-hook) we actually run the `pre-commit` hook twice, first in the prepare phase before showing the view to edit the message, and then again when committing. 

- Since we evaluate the "COMMIT_EDITMSG" file there is a good chance to show outdated messages to the user.  (You often see this in Git GUI and probably other tools as well.) (The current code also adds a newline always which is a bug, see code snippet above https://github.com/timbrel/GitSavvy/issues/1126#issuecomment-578961904.)

- Our commit message view does *NOT* lock the staging area, t.i. you can still stage and unstage hunks at that time; but we do not re-run the hooks. (The "native" git commit workflow does snapshot the staging area.)

- Running `pre-commit` before showing the view is too slow. We can't delay opening the view for x seconds. (Ideally maybe it would run in the background, but then we can't use the prepare-message anymore; esp. the slower `pre-commit` runs before the message hook.)

- Splitting and further mangling the "COMMIT_EDITMSG" (https://github.com/timbrel/GitSavvy/issues/1126#issuecomment-579896971) makes it harder to add dynamic features to our commit view (e.g. we already colorize the diff; we sure will update the shown diff if the stage changes; or allow to unstage already staged hunks within that view, ...)

Notes:

- Git GUI and other tools don't run the `prepare-msg-hook`, only `pre-commit`. Sublime Merge actually runs the prepare message hook *after* the user committed the message, doubt that makes sense though.

- Lack of good open source hooks makes it hard to test and implement. At the current time there is no user story here. 

- If we just fallback to the "native" git workflow, t.i. the user issues `git commit` for example using a custom command, we avoid a lot and the user has a working consistent workflow (locked stage, early abort if stage is empty or the hooks fail).
