### ISSUE TITLE
Status dashboard: Automatically ask for a 'push --force-with-lease'

### ISSUE THREAD

**Issue by kaste** [timbrel/GitSavvy#1130]
If we're ahead and behind, the push command (which will fail) should automatically ask the user for a '--force-with-lease'.

**Comment by randy3k** [comment]
If it exists, it would increase my chance to overwrite remote master's. I am a bit worried about data safety. Although there is a pop up for destructive commands, some users would proceed anyway without reading.

**Comment by kaste** [comment]
Do you have another idea? Usually, you never do a '--force' but with PR's esp. on GitHub it is the common workflow. 

Isn't it at least so that if we're in a '-4/+2' state, we can fail immediately if the user tries to do a normal 'push' bc we know for certain that this will fail? I thought we show a quick panel with 'proceed anyway, force-with-lease, force'. For data safety it would maybe be enough to make 'proceed anyway' the default. 🤷‍♀️
