### ISSUE TITLE
Freeze on big diffs

### ISSUE THREAD

**Issue by stevage** [timbrel/GitSavvy#1133]
I use inline diffing a lot to stage hunks. Every now and then, out of habit, I accidentally attempt to diff a CSV file or JSON file which has been completely changed. Sublime completely freezes.

Is it possible for GitSavvy to detect this situation and refuse to show the diff?

**Comment by kaste** [comment]
It probably doesn't freeze forever, does it?

It looks like the main GsInlineDiffRefreshCommand runs on the main thread. You could try a PR here, all other commands in that file delegate to a run_async method and you could basically copy-paste that pattern here.

**Comment by stoivo** [comment]
It is slow since it tries to find which characher changed, so it can display the 
![Screen Shot 2019-06-14 at 12 15 45](https://user-images.githubusercontent.com/3492040/59502570-5b584800-8e9e-11e9-9803-c206c092d908.png)

As @kaste  said. PR welcome.
