### ISSUE TITLE
Unable to determine Git repo path.

### ISSUE THREAD

**Issue by Nudelcode** [timbrel/GitSavvy#1156]
When Git:branch ist used in the Command Palette from Sublime Text 3. The Command Palette is closing and nothing happens. The Log says :  Unable to determine Git repo path.
Sublime Version and Log are listed below.

- Sublime Text version number : 3.2.1. Build 3207

- Git version number:  2.22.0

- OS type and version: Windows 8.1 Pro

- Console error output:

DPI mode: per-monitor
startup, version: 3207 windows x64 channel: stable
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/Sublime Text 3
packages path: /C/Users/CC-Student/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/CC-Student/AppData/Roaming/Sublime Text 3/Local
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Users/CC-Student/AppData/Roaming/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 1.61332
startup time: 1.74032
first paint time: 1.74132
reloading plugin Default.arithmetic
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.colors
reloading plugin Default.comment
reloading plugin Default.convert_color_scheme
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.detect_indentation
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.rename
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin ShellScript.ShellScript
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.50-pyyaml
reloading plugin Github Tools.github
reloading plugin Github Tools.github_blame
reloading plugin Github Tools.github_copy_link
reloading plugin Github Tools.github_create_pr
reloading plugin Github Tools.github_file_history
reloading plugin Github Tools.github_issues
reloading plugin Github Tools.github_open
reloading plugin Github Tools.github_plugin_settings
reloading plugin Github Tools.github_pulls
reloading plugin Github Tools.github_repository
reloading plugin GitSavvy.__init__
reloading plugin GitSavvy.git_savvy
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
plugins loaded
C:\Users\CC-Student\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package\common/util/file.py:29: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
Package Control: Skipping automatic upgrade, last run at 2019-08-06 09:19:05, next run at 2019-08-06 10:19:05 or after
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 1052, in run_
    return self.run()
  File "C:\Users\CC-Student\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package\core/interfaces/branch.py", line 23, in run
  File "C:\Users\CC-Student\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package\core/git_command.py", line 448, in repo_path
  File "C:\Users\CC-Student\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package\core/git_command.py", line 429, in get_repo_path
ValueError: Unable to determine Git repo path.

**Comment by asfaltboy** [comment]
Where is your git client installed? If you're not sure, start here:
https://git-scm.com/book/en/v2/Getting-Started-Installing-Git

**Comment by Nudelcode** [comment]
The Path to my Git CLient is: C:\\Programms\Git

**Comment by asfaltboy** [comment]
It may be that this path is not "picked up" in sublime. Luckily, GitSavvy provides a `git_path` setting for setting up the path to git on different environments. To learn how to change settings, please refer to the [documentation in the README][1].

Reference to setting:
https://github.com/divmain/GitSavvy/blob/cd1f570f3456481aa972730e0df426ef6d479647/GitSavvy.sublime-settings#L8-L23

[1]: https://github.com/divmain/GitSavvy/blob/master/docs/README.md#settings

**Comment by kaste** [comment]
It throws `ValueError: Unable to determine Git repo path.` so it should already have a git binary. If not it should throw https://github.com/divmain/GitSavvy/blob/cd1f570f3456481aa972730e0df426ef6d479647/core/git_command.py#L356

So it literally can't find a repo path. @Nudelcode you don't have a project or folder open, have you? An unsaved file without a folder will not work. A saved file without an open folder will not follow symlinks.

**Comment by kaste** [comment]
Closing due to lack of response
