### ISSUE TITLE
New organization

### ISSUE THREAD

**Issue by randy3k** [timbrel/GitSavvy#1177]
To @stoivo @asfaltboy and @kaste,

@divmain has just moved the reop to a new github org `timbrel`. I will submit a PR to package control for the change of repo soon though I believe that github will automatically forward the url.

PS: I have also just invited @kaste to join the org.

**Comment by randy3k** [comment]
ref: https://github.com/wbond/package_control_channel/pull/7719

**Comment by stoivo** [comment]
It looks like we where make admins for the repo but not invited into the org. Since it dosn't show any members of the org nor can I request to join the Github actions for the org.

**Comment by randy3k** [comment]
You are right. Only the org owner could enable github actions. It is not a big loss at this point as UnitTesting doesn't yet support github actions.

**Comment by stoivo** [comment]
But shouldn't we at least be memebers of the orginization?

**Comment by randy3k** [comment]
What you said is probably reasonable if `timbrel` is used to host only GitSavvy. However, @divmain may have other plans and it will be again up to him.

**Comment by kaste** [comment]
I have UnitTesting in a docker container 🤫

**Comment by stoivo** [comment]
Github actions is enabled! 

We need to reenable Travis and Appveyor for the new org. I tried to register them but need to wait for divmain to approve the orginization request.

**Comment by kaste** [comment]
Nothing to do here.
