### ISSUE TITLE
git flow hotfix finish hangs sublime text forever

### ISSUE THREAD

**Issue by luispuerto** [timbrel/GitSavvy#1183]
- Sublime Text version number: _3.2.2_
- Git version number: _2.23.0_
- OS type and version: _macOS 10.14.6_
- Console error output: _There isn't output on console_
- A description of the problem: _git flow hotfix finish hang sublime text forever_
- Steps to reproduce, if possible: _create a hotfix branch, do some changes and commit, then finish the hotfix._ 
- If the bug is caused by a failing command, [include a debug log](https://github.com/divmain/GitSavvy/blob/master/docs/debug.md#providing-a-debug-log). _It's empty._ 

PS/ I also realized that if you start a new repo and then execute gitsavvy git flow init denies the init if you don't have a remote repo.

**Comment by kaste** [comment]
Well, *I* don't use flow, but you should `GitSavvy: enable logging` from Command Palette, then open Sublime's console, and look what commands get executed and actually 'hang'. 

Well, 'hangs', literally forever in I have to restart Sublime?

**Comment by asfaltboy** [comment]
it hangs waiting for editor input... It's an old issue (dupe of #279 ?).

I don't use git-flow much anymore, a solution would be to implement hotfix function ourselves, or set `EDITOR=/path/to/sublime` for this command ...

**Comment by luispuerto** [comment]
Hey!! 

I did exactly that to try to get the log and the result, after restarting sublime, was an empty file. 

I can try again later, but it's not that dificultades to reproduce, because it happens even with a new repo.

I have the editor set as sublime in The global git config or should I set it in other place?

**Comment by luispuerto** [comment]
PS/ I really don't understand why has to wait for editor input. On terminal doesn't ask for anything… just merge and delete the branch.

**Comment by asfaltboy** [comment]
Hmm, that's a valid point ... can  you confirm that you use nvie's original gitflow version (and if not point me to the source)?

In the [original bash script][1] it shows a "summary of actions", can you paste yours in here (obfuscate the names if you like)?

I have a feeling the "notag" flag is enabled in shell but not when called from GitSavvy...

[1]: https://github.com/nvie/gitflow/blob/develop/git-flow-hotfix#L332-L348

**Comment by luispuerto** [comment]
Hey! 

I'm not using original [nvie's git-flow ](https://github.com/nvie/gitflow) mainly because the last commit was in 2012. I'm using [gitflow-avh](https://github.com/petervanderdoes/gitflow-avh) since it seems to be actively being developed (or at least the last commit was a little bit more than a year ago). 

You can see the summary of actions for hotfix, [here](https://github.com/petervanderdoes/gitflow-avh/blob/40fc2df960d034cb57dd277af7501be6884f767e/git-flow-hotfix#L229) and [here](https://github.com/petervanderdoes/gitflow-avh/blob/40fc2df960d034cb57dd277af7501be6884f767e/git-flow-hotfix#L726).

**Comment by luispuerto** [comment]
PS/ I almost forget, a couple of more reasons I'm using the avh version. 

- The `multi-hotfix = true` option seems to be working in this version, while in the nvie's one seems that it's not working. 
- avh's version has an additional option that is `git flow <whatever> delete`. I don't always want to merge the branch I've been working on. So delete it's quite handy. Perhaps you can implement this in the near future.

**Comment by asfaltboy** [comment]
Thanks @luispuerto , I looked at the AVH code yesterday, and saw that a flag/config is required to bypass the tag annotation. Please output your printed summary (the actual summary you get when running the command) both in shell and in sublime. Also, please provide the output of the following:
```bash
$ git config -l | grep flow
```

**Comment by luispuerto** [comment]
do you mean this? 

```shell
$git flow hotfix finish -n test
Switched to branch 'develop'
Merge made by the 'recursive' strategy.
 test.md | 1 +
 1 file changed, 1 insertion(+)
Deleted branch hotfix/test (was a5ce85b).

Summary of actions:
- Hotfix branch 'hotfix/test' has been merged into 'master'
- Master branch 'master' has been back-merged into 'develop'
- Hotfix branch 'hotfix/test' has been locally deleted
- You are now on branch 'develop'
```

And this? 

```shell
$ git config -l | grep flow
gitflow.multi-hotfix=true
gitflow.branch.master=master
gitflow.branch.develop=develop
gitflow.prefix.feature=feature/
gitflow.prefix.bugfix=bugfix/
gitflow.prefix.release=release/
gitflow.prefix.hotfix=hotfix/
gitflow.prefix.support=support/
gitflow.prefix.versiontag=
gitflow.path.hooks=/Users/lpuerto/Coding/zzTest2/.git/hooks
```

In sublime I don't get anything

**Comment by asfaltboy** [comment]
There isn't a message about tag nor do I see a config about "notag" flag ...  Is it possible that you already tagged the hotfix with the same version (check the output of `git tag -l` and compare with your hotfix branch name`...

Ref: https://github.com/petervanderdoes/gitflow-avh/blob/40fc2df960d034cb57dd277af7501be6884f767e/git-flow-hotfix#L530

**Comment by luispuerto** [comment]
https://github.com/petervanderdoes/gitflow-avh/wiki/Reference:-git-flow-hotfix#git-flow-hotfix-finish---finish-a-hotfix-branch

>-n,--[no]notag
>don't tag this release

the problem with hotfix is that there isn't a flag for no message. 

I just realize that what I said in a [previous comment](https://github.com/timbrel/GitSavvy/issues/1183#issuecomment-545146434):

> On terminal doesn't ask for anything… just merge and delete the branch.

Isn't true when there are changes to merge. The problem is that a hotfix always is going to have a message since they aren't doing it with fast forward. Sorry, my initial problem was trying to delete a hotfix branch that didn't have any commit. So when I did on the terminal —using finish command— it didn't brought up any editor since there was nothing to merge. SORRY for the confusion. 

On another note, I really don't know whey when using the hotfix finish on sublime doesn't bring up sublime to edit the tag and the message or whatever. Since I have setup sublime as my default editor on Git, on the terminal is doing it just fine.

**Comment by kaste** [comment]
Well, it probably doesn't bring up Sublime bc Sublime hangs. 😁

So if you can confirm that this would work on the terminal bc it prompts Sublime and waits for a message, then the fix would be just to issue the command in GitSavvy from a dedicated thread. Then Sublime would not hang but the thread.

**Comment by kaste** [comment]
Aside, avh is installed by default on Windows so it is the standard fork now.

**Comment by luispuerto** [comment]
>then the fix would be just to issue the command in GitSavvy from a dedicated thread. Then Sublime would not hang but the thread.

@luispuerto should I do that? and how?

**Comment by luispuerto** [comment]
PS2/ Adding the `delete` action the command palette would be really appreciate 😉

**Comment by asfaltboy** [comment]
If you would like to have a workaround, I would recommend defining a custom command in your `User.sublime-commands` which uses the `run_in_thread` option, as [described here][1].

If you're looking to contribute a fix to GitSavvy, check out [the functionality in `flow.py`][2], adding optional support for launching the command in a thread should be straight forward (see [the custom command's `run_in_thread` implementation][3]). We may need to read the various `git-flow` settings to know when a command needs to open an editor, or when it needs to wait (or alternatively, just never wait for some flow commands to complete).

[1]: https://github.com/timbrel/GitSavvy/blob/master/docs/custom.md#command-arguments
[2]: https://github.com/timbrel/GitSavvy/blob/master/core/commands/flow.py#L171-L184
[3]: https://github.com/timbrel/GitSavvy/blob/3c2e06468c8a64c024760ee0c22ba261c08731df/core/commands/custom.py#L67-L70

**Comment by kaste** [comment]
Since I learned that I actually have avh installed because it ships by default on Window. Could you do a babystep per babystep reproduction for someone who never used flow? It sounds like a trivial fix.
