### ISSUE TITLE
Remotes should be updated if removed / renamed in git

### ISSUE THREAD

**Issue by asfaltboy** [timbrel/GitSavvy#1187]
Currently, the remotes are cached and kept forever, so closing sublime is required if we change git remotes.

**Comment by kaste** [comment]
Where exactly?  If I i `remote add` then e.g. it appears in (BRANCHES dashboard) immediately for `[h]` and `[p]`, if I `remote remove` it disappears. AFAIK only "last used remote" is cached, not sure though, still plenty of files here I never touched 😁.

**Comment by asfaltboy** [comment]
I actually not sure what's going on ... I have an older remote appearing in my BRANCHES , but I don't understand why ... I'll reopen once I had more time to look

**Comment by kaste** [comment]
In BRANCHES other remotes can show up as long as there are branches pointing to them.  For this dashboard, we just query for all branches and then group them by remote.
