### ISSUE TITLE
[ST 4] branch status badge no long is shown when there are no views

### ISSUE THREAD

**Issue by randy3k** [timbrel/GitSavvy#1206]
In the alpha release of ST4, the [old bug](https://github.com/timbrel/GitSavvy/issues/1099) of not showing status badge is regressed. The fix in #1101 no longer works.

The original bug was a regression of https://github.com/timbrel/GitSavvy/pull/1083. Reverting to a commit just before it, the bug is no longer seen.

**Comment by randy3k** [comment]
Running `window.get_view_index(view)` when there are no views now yields `(-1, -1)` in ST 4. In ST 3, we have `(0, -1)`.

**Comment by kaste** [comment]
Well, you need feedback from *them* otherwise you don't know if this is a bug or an intentional change. Other than that, the crucial part is to **not** run on widget and preview views.

**Comment by randy3k** [comment]
From jps
> lot's of small details about sheet management have changed, due to the refactoring needed for the tab multi-select. The best option is to make an issue for it, and then Benjamin can go through the logic next week and verify if this is a desirable change or not

So I am going to file an issue to SublimeTextIssues and cross reference this issue.

**Comment by jskinner** [comment]
FWIW `window.get_view_index()` will be changed in 4053 to be compatible with ST3

**Comment by kaste** [comment]
Close as fixed upstream
