### ISSUE TITLE
[Errno 24] Too many open files

### ISSUE THREAD

**Issue by rwols** [timbrel/GitSavvy#1221]
```
Please report this error to GitSavvy:

[Errno 24] Too many open files

Traceback (most recent call last):
  File "/home/raoul/.config/sublime-text-3/Installed Packages/GitSavvy.sublime-package/core/git_command.py", line 197, in git
    startupinfo=startupinfo)
  File "./python3.3/subprocess.py", line 784, in __init__
  File "./python3.3/subprocess.py", line 1281, in _get_handles
OSError: [Errno 24] Too many open files

```

- Sublime Text 3210
- Git 2.20.1
- Ubuntu 19.10

This message popped up when I was running UnitTesting many times. I don't know how to reproduce it exactly, but I believe it's reproducible by running lots of automated tests where each test opens and closes a file very quickly. If I have time I'll try to make a reproducible case.

**Comment by kaste** [comment]
Hi! We only ever run one git command at a time.  (So in an automated setup at max the queue would fill.) It is likely that we do git status calls here which in turn can be quite heavy, but only on rather large repos.

Also possible that linters like SublimeLinter or Lsp fire on new or activated events which can in my experience do more harm. (E.g. mypy is not very friendly in such situations.)

**Comment by rwols** [comment]
It looks like this is just a symptom of my bad integration tests for LSP, I'll have to investigate further :)
