### ISSUE TITLE
Mapping jj or jk to escape causes user interface to revert to command mode

### ISSUE THREAD

**Issue by jtmusky** [timbrel/GitSavvy#1222]
- Sublime Text version number: **build 3211**
- OS type and version: **Windows 10**
- Console error output: **N/A**
- A description of the problem. **Using NeoVintageous keymaps with "jj" as the escape key doesn't work within the gitsavvy UI.**
- Steps to reproduce, if possible: **Install NeoVintageous and use the following keymap preference**
```json
[ 
   { "keys": ["j", "j"],
        "command": "_enter_normal_mode",
        "args": {"mode": "mode_insert"},
        "context": [{"key": "vi_insert_mode_aware"}]
    }
]
```
Use the following gitsavvy options:
```json
"vintageous_friendly": true,
"vintageous_enter_insert_mode": true,
```

**Comment by kaste** [comment]
Don't we generally bind `j` (and `k`) already for navigation in most UI views?

**Comment by jtmusky** [comment]
> Don't we generally bind `j` (and `k`) already for navigation in most UI views?

I use those keys specifically for most navigation. However within vim "insert" mode I use the double "j" to escape back into command mode where the navigation takes place. GitSavvy wants "insert" mode for navigation.

**Comment by kaste** [comment]
Honestly, you maybe know more about this ...  I don't use the vim emulation, I just know that we already bind the `j` key, so I thought binding a `jj` will never catch here.  

I see that we define `j` usually like so

```
    {
        "keys": ["j"],
        "command": "gs_status_navigate_file",
        "args": { "forward": true },
        "context": [
            { "key": "setting.command_mode", "operator": "equal", "operand": false },
            { "key": "setting.git_savvy.vintageous_friendly", "operator": "equal", "operand": true },
            { "key": "setting.git_savvy.status_view", "operator": "equal", "operand": true }
        ]
    },
```

So, "command_mode" (don't know what this is to be honest) must be false and "vintageous_friendly" must be true. Should we do this differently?

**Comment by kaste** [comment]
Well this should be asked on the *NeoVitangeous* repo probably as I'm not sure what the *really best* way of doing things here is.  (For example I don't know why we require "insert" mode t.i. *command_mode=false*, we literally have read only views most of the time.)

Anyhow, your binding needs probably just another constraint (aka "context"). So `jj` is only applicable if *not* in a GitSavvy view, for example checking that `selector` is *not* `gitsavvy` could work.
