### ISSUE TITLE
gitignore 

### ISSUE THREAD

**Issue by tsktech** [timbrel/GitSavvy#1223]
the .gitignore is not validated when checking for status, all file show has unstaged

**Comment by kaste** [comment]
Hm, we don't parse the *.gitignore* files on our own, e.g. we just call `git status` almost like on the command line, and just parse and render its output.  Make sure it works as expected on the command line, e.g. the gitignore files look correct and are in the correct folders.

**Comment by tsktech** [comment]
Hi, thanks for the quick revert.. 

I am a bit confused I guess on the workflow, my normal practise is git add * (so that the dot file are ignored). is GitSavvy instead of selecting each one and excluding the dot files.. when 's' shortcut is pressed.. 

hm.. hence tried work around by including the dot files in .gitignore.. I guess I am doing something wrong..

**Comment by kaste** [comment]
`git add *` is a feature you only have within your shell, t.i. the meaning of `*` is defined by your shell.  

It is the recommended workflow to add files you don't want to version control to your *.gitignore* file (or *.git/info/exclude* for private files).  Such ignored files will not appear as dirty in the GitSavvy status view, after that you can use the `<a>` key to add all files etc.

My guess is that your *.gitignore* is malformed, or has a typo.

**Comment by tsktech** [comment]
Dear Kaste, thanks a lot bro..  yes the issue was with the .gitignore

**Comment by kaste** [comment]
You're welcome
