### ISSUE TITLE
Shortcuts for move cursor to next/previous file stopped working

### ISSUE THREAD

**Issue by kraag22** [timbrel/GitSavvy#1227]
On Status screen I was using keys "." and "," for moving cursor to "to next/previous file". It stopped working now. I can move cursor only with arrow keys or mouse.

Please include the following information when filing a bug:

- Sublime Text version number 
3.2.2 build 3211
- Git version number
2.24.0
- OS type and version
masOS Mojave 10.14.6
- A description of the problem.
Shortcuts for move cursor to next/previous file stopped working
- Steps to reproduce, if possible
go to status screen and try to move cursor between files via shortcut
- GitSavvy version
2.20.0

**Comment by kaste** [comment]
Work fine here.  

In the Sublime console (`View > Show Console`) try `sublime.log_commands(True)`. Then use the keys, it should log the commands, roughly like so 

```
>>> sublime.log_commands(True)
command: drag_select {"event": {"button": 1, "x": 192.5, "y": 500.5}}
command: gs_status_navigate_file {"forward": true}
command: gs_status_navigate_file {"forward": false}
command: gs_status_navigate_file {"forward": true}
command: gs_status_navigate_file {"forward": false}
```

*After* that, ensure you close the status view, restart Sublime, open a new status view.  Check again.  Maybe we didn't migrate to the new version properly which ships a new syntax for the status view.

**Comment by kraag22** [comment]
Thanks for swift response. I tried to turn logs on. It showed the same stuff as you posted (bunch of `gs_status_navigate_file` commands), but cursor didn't move.
After restart everything is working fine. So you can close this issue.

PS: Exactly same thing happend on both my work and personal macbook...

**Comment by kaste** [comment]
I can see now how that migration to the next version could have failed... glad it wasn't more than a restart.

**Comment by kraag22** [comment]
Exactly same issue happened yesterday. But restart doesn't help. It affects both of my macs. Logs are printed normally.

**Comment by kaste** [comment]
Odd. While viewing the status dashboard, maybe open the console and execute 

```
view.find_by_selector("meta.git-savvy.entity")
```

Or generally, while at a file `ctrl+alt+shift+p` (ctrl is probably super on a mac), click copy and post the selector here.

Maybe the new syntax is not applied to the view.

**Comment by kraag22** [comment]
works now again :)

**Comment by kaste** [comment]
Anything you changed in between?

**Comment by kraag22** [comment]
nothing
