### ISSUE TITLE
Add one file in directory without staging all files

### ISSUE THREAD

**Issue by stevage** [timbrel/GitSavvy#1231]
Not sure if this is a support request or a feature request. But I'm trying to find a way to stage a file within a directory which currently isn't being tracked at all -- without staging the entire directory.

Normally I'd just stage the whole directory, then unstage the files within it that I don't want (and possibly ignore them). But this one contains some enormous files so that's not viable.

Is there any way to achieve this currently, without resorting to the command line?

**Comment by kaste** [comment]
I don't see a command here, nor any trick.  Strange with so many commands already, there is no "stage this file".  (I rather remove the "quick stage..." commands which just duplicate what we have... 🙄)

Maybe a "stage this file" could then be added to the sidebar, or the right click context menu.

**Comment by kaste** [comment]
This has been actually implemented (kind of) in #1305 released 2.23.0 (June 2020).  

The command is called `gs_stage_hunk` and must be bound manually, to a key, context menu, whatever.  To stage an untracked file, you have to first open it, t.i. it only works with the *current* file/view/buffer.
