### ISSUE TITLE
Set upstream for the active branch

### ISSUE THREAD

**Issue by mercurykd** [timbrel/GitSavvy#1244]
Sublime Text 3210
git version 2.24.0.windows.2
Windows 10 x64 1909

![image](https://user-images.githubusercontent.com/30900414/73069817-32824180-3ec8-11ea-8b16-73fd88622b9a.png)

Nothing happens

**Comment by kaste** [comment]
That's a bit too short. I can see you're in the branch view. What command or keybinding do you trigger here? Are there some errors shown in console? Is this probably a stupid mistake on our side, or something hard to reproduce?

**Comment by mercurykd** [comment]
After rebooting the PC, the problem disappeared. My apologize.

**Comment by kaste** [comment]
We'll see if it comes back.
