### ISSUE TITLE
GitSavvy breaks terminal git rebase --interactive

### ISSUE THREAD

**Issue by nh2** [timbrel/GitSavvy#1248]
I found in the last couple months on multiple large (work) git repos that GitSavvy breaks some git CLI functionality when it comes to rebasing.

I use `git rebase -i --autostash --autosquash` to `fixup` a commit.

With the GitSavvy plugin disabled, everything works fine:

```
Created autostash: 555e12ed2
Applied autostash.
Successfully rebased and updated refs/heads/mybranch.
```

With the GitSavvy plugin enabled, performing the same results in:

```
Created autostash: 97c65ca0a
The previous cherry-pick is now empty, possibly due to conflict resolution.
If you wish to commit it anyway, use:

    git commit --allow-empty

Otherwise, please use 'git cherry-pick --skip'
interactive rebase in progress; onto e0da8424d
Last commands done (2 commands done):
   pick 264eb6968 cpp: Commit message 1.
   pick 264eb6968 cpp: Commit message 1.
Next commands to do (2 remaining commands):
   fixup d0973164d fixup! cpp: Commit message 1.
   pick 66a8bb984 Commit message 2.
You are currently rebasing branch 'mybranch' on 'e0da8424d'.
```

I have the suspicion that there is some race condition going on between GitSavvy and the interactive rebase.

I _believe_ that I din't have these problems mid-last year (but I have no data on this).

This is very frustrating, because I like GitSavvy a lot (but need the git CLI to work unimpeded as well).

**Comment by kaste** [comment]
Hi, I also have some troubles with rebases, but not always.  

- Is Sublime in the background or foreground while git performs the rebase?
- Is git enabled in Sublime core? (You know, the new badges in the current version.)
- Are the files affected by the rebase open? I.e. do they reload often?
- Which view is active while rebasing? E.g. a GitSavvy special view?
- Which OS? And lastly is the other Sublime product, was it called Sublime Merge?, also running?

**Comment by nh2** [comment]
> Is Sublime in the background or foreground while git performs the rebase?

I'm pretty sure that in my usage Sublime is in the foreground, because `rebase -i` pops up the rebase plan editor in Sublime; I edit it and press Ctrl+S to save and Ctrl+W to close the tab. Because I have other Sublime tabs open, the main window does not close and stays focused.

> Is git enabled in Sublime core? (You know, the new badges in the current version.)

Yes, `"show_git_status": true,` is on the default setting.

> Are the files affected by the rebase open? I.e. do they reload often?

Usually yes; I often `git commit --fixup` files that I have just, or recently, improved, and then do `git rebase -i`.

> Which view is active while rebasing? E.g. a GitSavvy special view?

No GitSavvy views are open. Only normal editor tabs.

> Which OS? And lastly is the other Sublime product, was it called Sublime Merge?, also running?

I encountered it both on Ubuntu 18.04 and NixOS 19.09.

No Sublime Merge is installed.

**Comment by nh2** [comment]
> Hi, I also have some troubles with rebases, but not always.

I can also confirm that _sometimes_ it does not happen, but I don't know what controls it.

For example, I could reliably reproduce it 5 times in a row performing the same rebase with GitSavvy installed via Package Control, and then today I uninstalled it, installed it via Git, tried the same rebase again and it worked.

**Comment by kaste** [comment]
Really, the unpackaged, straight GitSavvy behaves different from the PackageControl version? 

- I had yesterday a somewhat reliably failing rebase where closing "Sublime Merge" was the fix. 

- Two weeks ago, I had another reliable case where closing some (affected) views was the only fix.

Generally, this got worse say in the last year, either with the newer Sublime and/or the newer git.  (During the last year git reimplemented git rebase -i in native c afaik, it's way, way faster now and maybe that's causing problems.)

Compared to that GitSavvy did not change too much. The only thing that changed is that the background "status" call now uses `GIT_OPTIONAL_LOCKS`. (Reverting that did not help.) 

Maybe we should turn off GitSavvy "while rebasing".

**Comment by nh2** [comment]
> Really, the unpackaged, straight GitSavvy behaves different from the PackageControl version?

I doubt it, I think it's just a race condition and me cloning a different one and Sublime reloading it turned the race in my favour. A day later I got the same problem with another rebase, on the master checkout.

Another way it manifests: Sometimes when I insert another commit in `rebase -i` using `pick`, I get this:

```
Created autostash: 8c8c21ab3
Applied autostash.
error: nothing to do
```

This problem also disappears when disabling GitSavvy.

Btw, another idea:

A year ago or so, I'm pretty sure this all worked flawlessly with GitSavvy. Perhaps the problem was introduced at the same time that Sublime gained its native git support? Maybe it's not actually GitSavvy<->Git that are creat problem, but GitSavvy<->Sumlime's Git? I have no evidence for it, just an idea.

**Comment by kaste** [comment]
After updating to the latest git (2.26) which once again changes some `rebase` implementation; and also after upgrading my OS; 🤞 I had no issues at all, I hope hope hope it stays.

I still do the 🤞 before starting a rebase but then it just flies through, even 30+ commits. (It is also incredible fast right now.)

**Comment by kaste** [comment]
It still works very reliable.  Closing as too much has changed code wise anyway.
