### ISSUE TITLE
[diff view] Cyrillic fail

### ISSUE THREAD

**Issue by mercurykd** [timbrel/GitSavvy#1251]
windows 10 x64 1909
subl 3210 dev
![image](https://user-images.githubusercontent.com/30900414/73719566-47b56680-4739-11ea-965e-06398038df42.png)

**Comment by kaste** [comment]
Hi! Which GitSavvy view is this? Diff or commit message? Can you provide a small public repo to reproduce?

**Comment by kaste** [comment]
Oh, the title says it's the diff view. 🙄

**Comment by kaste** [comment]
Ah, also check please which encoding is used for the special view and in contrast for the original file. (That's in the statusbar.)

Lastly, in the Sublime console

```
import locale; locale.getpreferredencoding()
```

**Comment by mercurykd** [comment]
> Which GitSavvy view is this?
This is the difference between two branches

> import locale; locale.getpreferredencoding()
cp1251

>  which encoding is used for the special view and in contrast for the original file
![image](https://user-images.githubusercontent.com/30900414/73727611-442adb00-474b-11ea-8a78-e3a2e69a9028.png)
![image](https://user-images.githubusercontent.com/30900414/73727620-48ef8f00-474b-11ea-9cac-43ea7be6ed76.png)

I can not reproduce with the same files, but in the test folder
Apparently some special case of a specific repository
I can make a log

**Comment by kaste** [comment]
There won't be nothing in the logs because GitSavvy doesn't log anything.  The best you can do is to get your hands a bit dirty... in the Sublime console which is our python REPL.

```
>>> import subprocess
>>> subprocess.Popen('git --version', stdout=subprocess.PIPE).communicate()
```

just to check if anything works. 

Then make the file dirty so it appears again in a diff.

```
>>> b, _ = subprocess.Popen('git diff', stdout=subprocess.PIPE, cwd=<your project root>).communicate()
```

Now `b` holds the output which we need to decode.

```
>>> b.decode()  # try utf-8
>>> b.decode('cp1251')  # etc.
```

**Comment by mercurykd** [comment]
> Then make the file dirty so it appears again in a diff.

when i make the file dirty so it appears again in a diff = All is well
The problem appears when I compare 2 branches
```
b, _ = subprocess.Popen('git diff ZD-428..master', stdout=subprocess.PIPE, cwd='C:\OSPanel\domains\zd').communicate()
b.decode()
>>> b.decode()
Traceback (most recent call last):
  File "<string>", line 1, in <module>
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc4 in position 59482: invalid continuation byte
```
Apparently the parser cannot decode due to a non-standard character?

**Comment by kaste** [comment]
Well, okaaay.  Which command or approach in GitSavvy do you use to get this diff (from the branches view, or the log graph...)?

Have you found an encoding that works, e.g. `b.decode('cp1251')`. Esp. `b.decode('latin-1')` probably doesn't throw but produces the bug here.?

**Comment by mercurykd** [comment]
> Well, okaaay. Which command or approach in GitSavvy do you use to get this diff (from the branches view, or the log graph...)?

from the branches view, hotkey "f"

> Have you found an encoding that works, e.g. b.decode('cp1251'). Esp. b.decode('latin-1') probably doesn't throw but produces the bug here.?

b.decode('cp1251') = fail
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 101522: character maps to <undefined>

b.decode('latin-1') = ok
```
diff --git a/app/app_dispatcher.php b/app/app_dispatcher.php\nindex db86a330..18b7f628 100644\n--- a/app/app_dispatcher.php\n+++ b/app/app_dispatcher.php\n@@ -11,13 +11,14 @@ class app_dispatcher extends core_object\n         // if(!OFFICE) {\n         //     die();\n         // }\n+\n         // Ñ\x84Ð¸ÐºÑ\x81Ð¸Ñ\x80Ñ\x83ÐµÐ¼ Ð²Ñ\x80ÐµÐ¼Ñ\x8f Ð½Ð°Ñ\x87Ð°Ð»Ð° Ð²Ñ\x8bÐ¿Ð¾Ð»Ð½ÐµÐ½Ð¸Ñ\x8f Ñ\x82ÐµÐºÑ\x83Ñ\x89ÐµÐ³Ð¾ Ð¼ÐµÑ\x82Ð¾Ð´Ð°\n         if (OFFICE === true && DEBUG === true) {\n             $start = microtime(true);\n         }\n
```

**Comment by kaste** [comment]
Okay, that explains the bug because we use "latin" as a fallback which doesn't throw but produces garbage.  Now, the question is which encoding to use here?  Anyway you know how these files are encoded?

**Comment by mercurykd** [comment]
I found a file that had non utf8 encoding
![image](https://user-images.githubusercontent.com/30900414/73786000-debe0500-47b1-11ea-9183-fbf4634d0e24.png)
When save it to utf-8 - diff breaks
![image](https://user-images.githubusercontent.com/30900414/73786286-63a91e80-47b2-11ea-8354-e406c3125eaa.png)

**Comment by mercurykd** [comment]
> Can you provide a small public repo to reproduce?

https://github.com/mercurykd/test_diff

**Comment by kaste** [comment]
Yeah, okay now I see.  When showing the diff here the output has *multiple* encodings, t.i. various bits have different encodings.  In GitSavvy we only decode once, the whole output with one encoding.  So whatever encoding you choose here some lines show garbage, some show nicely. 

It is a bit questionable why we choose "latin1" as fallback, maybe *locale.getpreferredencoding()* would be better but of course not good or even "correct".

**Comment by mercurykd** [comment]
Is it possible to do as in bash?
![image](https://user-images.githubusercontent.com/30900414/73841749-af041100-4834-11ea-84c1-3f74077c7e7d.png)

**Comment by kaste** [comment]
That bash output is just *utf8*, ignore errors.  Sublime renders something like this

![image](https://user-images.githubusercontent.com/8558/73842999-034fc680-481e-11ea-9fdd-44899e5ea957.png)

**Comment by kaste** [comment]
We now do not fail anymore on decoding errors but show question marks as shown in my last comment and a help text.

Mixed encodings are still unsupported.  It's mildly complex to do this, somewhat challenging even. I think this would be a good, interesting PR.
