### ISSUE TITLE
Why git hook pre-commit runs without visual progress before new commit tab open? [Question]

### ISSUE THREAD

**Issue by max-mykhailenko** [timbrel/GitSavvy#1253]
I use Sublime 3210, latest GitSavvy and use custom git hooks based on husky. I have defined pre-commit hook and it runs without any visual progress right after I press `c` on dashboard. How I can improve this behaviour? Goal is to run pre-commit only after commit message ready (or maybe I should move code check to `commit-msg` hook).

Config
```
// Settings in here override those in "GitSavvy/GitSavvy.sublime-settings",

{
  "show_commit_diff": "full",
  "show_panel_for": ["pull", "push", "merge", "commit"],
  "git_status_in_status_bar": false,
  "merge_log": false,
  "tab_order": [
      "status",
      "branch"
  ],
  "hide_help_menu": true,
  "live_panel_output": true,
  "show_full_commit_info": true
}
```

**Comment by kaste** [comment]
Yeah, that's the current state, and I don't think you can do anything except doing a PR. 🤷‍♀  

Although I appreciate that we run hooks, it is rather strange in an app that you hit `c` and then wait 5 seconds before something happens. I would rather expect that the hooks run in the background and then you get notified if e.g. `lint-staged` fails. You also should see the output of these hooks probably.

**Comment by max-mykhailenko** [comment]
I move checks to `commit-msg` hook and now it works with progress and only once for commit

**Comment by kaste** [comment]
Does that mean the "pre-" hooks run multiple times (twice?) ?

**Comment by max-mykhailenko** [comment]
@kaste I realise that `pre-commit` hook runs before commit view showed and after I wrote some message and press commit (cmd + enter).

**Comment by kaste** [comment]
Re-open because running "pre-commit" twice is a bug.
