### ISSUE TITLE
Issue autocomplete (reference or close an issue) fails on Windows 1o

### ISSUE THREAD

**Issue by JanaJarecki** [timbrel/GitSavvy#1277]
Hej,
When committing and typing a # and the tab key, I suppose that I should see the open issues, but nothing happens. Can I fix this?
Cheers,
Jana

Windows 10
Sublime Text 3.2.2
GitSavvy 2.21.0

**Comment by kaste** [comment]
Hm. The issue may be that we don't report back when we can't determine the GitHub repo but just fail.  Can you open the Sublime console (`View -> Show console`) and see if we throw here?

Generally, there is some automation to find the GitHub repo but you can also just set it using (via Command Palette ctrl+shift+p) `github: set remote for integration`.

**Comment by JanaJarecki** [comment]
Thank you for the quick reply. The set remote for integration command results in an error with this console log:

    Traceback (most recent call last):
      File "...AppData...\Sublime Text 3\Installed Packages\GitSavvy.sublime-package\core/commands/push.py", line 140, in run_async
      File "...AppData...\Sublime Text 3\Installed Packages\GitSavvy.sublime-package\core/ui_mixins/quick_panel.py", line 130, in show_remote_panel
      File "...AppData...\Sublime Text 3\Installed Packages\GitSavvy.sublime-package\core/ui_mixins/quick_panel.py", line 147, in show
      File "...AppData...\Sublime Text 3\Installed Packages\GitSavvy.sublime-package\core/git_mixins/remotes.py", line 13, in get_remotes
      File "./python3.3/collections/__init__.py", line 56, in __init__
      File "./python3.3/collections/abc.py", line 578, in update
      File "...AppData...\Sublime Text 3\Installed Packages\GitSavvy.sublime-package\core/git_mixins/remotes.py", line 13, in <genexpr>
    AttributeError: 'NoneType' object has no attribute 'groups'

**Comment by JanaJarecki** [comment]
Info that may or may not help:
This happened on one single new branch (feature branch) that was pulled from a remote branch into the local repository, in this repository other branches (like development) have proper remotes set for integration which work.

**Comment by kaste** [comment]
What's the output of 

```
$ git remote -v
```

then? 

If you can't post. For this open source repo it could look like

```
fork    https://github.com/kaste/GitSavvy.git (fetch)
fork    https://github.com/kaste/GitSavvy.git (push)
origin  https://github.com/timbrel/GitSavvy (fetch)
origin  https://github.com/timbrel/GitSavvy (push)
```

Our regex parsing here is just `<name>\tab<url>\space` (or in code `"([0-9a-zA-Z_-]+)\t([^ ]+)"`) which doesn't match for your case.

**Comment by JanaJarecki** [comment]
*hm* so far this looks fine to me (no special characters), may I email it to you just to be sure?

**Comment by JanaJarecki** [comment]
Shot in the dark: I'm on Windows, we're not having [backslash issues](https://medium.com/@ageitgey/python-3-quick-tip-the-easy-way-to-deal-with-file-paths-on-windows-mac-and-linux-11a072b58d5f)?

**Comment by kaste** [comment]
First try https://regex101.com/r/W1cD8P/1/

**Comment by JanaJarecki** [comment]
Ah - great. The issue is that the name of the branch name was xxx/yyyy (like feature/doc, feature/newmodel, etc.), solved when changing the name! Thank you!

**Comment by JanaJarecki** [comment]
The autocomplete works like a charm now, thank you so much, sorry for the effort.

**Comment by kaste** [comment]
The branch name or the remote name?

**Comment by kaste** [comment]
Oh, I now see git allows `/` for remote names

For example

```
$ git remote -v                                                                                            fo/bar  https://github.com/kaste/GitSavvy.git (fetch)
fo/bar  https://github.com/kaste/GitSavvy.git (push)
```

We don't support that, and I cannot just change the regex here, it would break somewhere else.
