### ISSUE TITLE
log view disappeared

### ISSUE THREAD

**Issue by dlnsk** [timbrel/GitSavvy#1287]
This error is in console when I go to Log view:
```
git log --graph --decorate --date=format:%Y-%m-%d %H:%M --pretty=format:%h%d %<|(80,trunc)%s | %ad, %an --decorate-refs-exclude=refs/remotes/origin/HEAD --exclude=refs/stash --all --simplify-by-decoration --sparse
fatal: unidentified argument: --decorate-refs-exclude=refs/remotes/origin/HEAD

```
Yes. `refs/remotes/origin/HEAD` doesn't exist in my repository. But I made `git remote set-head origin -a` and it has created but nothing to change.

**Comment by kaste** [comment]
Has this been resolved since you opened the other issue? The error message looks like you're using an old version of git but I would have to look it up.

**Comment by kaste** [comment]
Just checked again `--decorate-refs-exclude` can take any string t.i. it doesn't have to reference a valid, known `ref`.

**Comment by dlnsk** [comment]
git version 2.7.4

**Comment by dlnsk** [comment]
Sorry. Repository has old version of git.
