### ISSUE TITLE
[GRAPH view] fails with unrecognized argument error

### ISSUE THREAD

**Issue by peteratemarsys** [timbrel/GitSavvy#1289]
Hi,

When I'm on the status view and try to switch to the graph view, I get the following console and error message:

```
$ git log --graph --decorate --date=format:%Y-%m-%d %H:%M --pretty=format:%h%d %<|(80,trunc)%s | %ad, %an --decorate-refs-exclude=refs/remotes/origin/HEAD --exclude=refs/stash --all --simplify-by-decoration --sparse

fatal: unrecognized argument: --decorate-refs-exclude=refs/remotes/origin/HEAD
```
gitsavvy version 2.22.0
Recently upgraded to Mac OS Catalina

Many thanks

**Comment by kaste** [comment]
Updating git should do it. Which version have you installed?

Don't remember which version is the minimum required since it's been already a while since I coded this. Have to look it up again.

**Comment by peteratemarsys** [comment]
Yes it did, thank you. I was on git `v2.10.x`. It works fine on `v2.26.0`.

**Comment by kaste** [comment]
They added that in v 2.16 (Jan 2018). I misread that because I actually roughly wanted to be compatible with the last 4 years of git (circa v2.10). Don't know if I should revert this arg, since we already pushed, and updating git from time to time is not a bad thing.
