### ISSUE TITLE
[Feature Request] Show prev/next commit for current file

### ISSUE THREAD

**Issue by tektrip-biggles** [timbrel/GitSavvy#1294]
A really useful command, ideally with the option to bind a keyboard shortcut would be to navigate through previous versions of a particular file.

Currently, this is possible by doing the following:
"git: log current file" > "For current branch" > (select commit) > "Show file at commit"

However, if you want to quickly look through multiple commits, it is a little cumbersome. Ideally, once looking at a specific commit for a specific file, it would be possible to quickly go through the commit history. [This site](https://githistory.xyz) is close to what I mean, although the fancy sliding animations are of course unnecessary. 

A challenge may be to maintain the window's position in the file when essentially loading different versions of it.

**Comment by kaste** [comment]
Yes! (But to be clear not show prev/next *commit* but show prev/next *revision* or *version* of that file.)

Currently, we have in the file revision view, the following state (properties...): *commit_hash* which introduced the revision, *file_path*, and *repo_path*. 

It is probably easy(?) to get the previous version. Something along `git log -1 <commit_hash> -- <file_path>`, but how do we get the next version? 🤔

**Comment by kaste** [comment]
That's in 2.25.0
