### ISSUE TITLE
Diff view does not switch when staged

### ISSUE THREAD

**Issue by ehuss** [timbrel/GitSavvy#1299]
A recent changes seems to make it so that gitsavvy doesn't know the difference between the "diff view" and the "diff view (staged)".  Steps:

1. Change a file.
2. In the "Git Status" view, press `f` (lowercase) to open a view to show the changes.
3. Go back to the status view (without closing the diff view), and stage the change.
4. Press `Shift-F` to open a view to show the staged changes.

What happens: Pressing `Shift-F` brings focus to the diff view opened in step 2, which refreshes and is empty.

Expected: Pressing `Shift-F` should open a new view with the staged changes.

This used to work, but something changed recently so that it doesn't seem to work right. A workaround is to close the diff view before step 4.

Using  2.22.2.

**Comment by kaste** [comment]
Yes, that feels buggy.  We actually only have "one" diff view in the two modes, showing staged changes or unstaged ones.  Hence we reuse the view now.  Probably makes sense to switch the staging area or "mode" as well.  Other than that, the common or intended workflow is to use `<TAB>` in the diff view to switch the modes.

**Comment by kaste** [comment]
Fixed in https://github.com/timbrel/GitSavvy/releases/tag/2.22.3

**Comment by ehuss** [comment]
Awesome, thanks!  I just want to say, I think this plugin is amazing, thanks for all the work, and the incredibly quick fix!

**Comment by kaste** [comment]
🙏 (and don't forget to try the `<TAB>` trick 😏)
