### ISSUE TITLE
New diff colors are too muted

### ISSUE THREAD

**Issue by stevage** [timbrel/GitSavvy#1310]
A new change came through in the last couple of days which changed the default diff colors for me. It now looks like this:

<img width="266" alt="Screen Shot 2020-06-12 at 10 58 10 am" src="https://user-images.githubusercontent.com/678344/84453617-a2d50800-ac9b-11ea-9966-5c37e639f8a7.png">

Is it possible for me to make those colors much brighter and more distinguishable? I find them almost invisible right now.

**Comment by kaste** [comment]
Sure, we now use the new built-in colors See https://www.sublimetext.com/docs/3/incremental_diff.html under the section "styling". 

We add  ".git-savvy.inline-diff" as suffix here. See also the releases notes https://github.com/timbrel/GitSavvy/releases/tag/2.23.0

**Comment by stevage** [comment]
Thanks. So it looks like the only way to fix this is to manually edit one of the existing themes? This looks to be a [fairly involved process](https://stackoverflow.com/questions/18746993/how-do-i-edit-the-solarized-light-theme-in-sublime-text-3).

Just a bit frustrating, because basically I don't want/need any further changes to GitSavvy, I just want it to keep working the way it always has. I have now disabled auto package upgrades.

I see this in the release notes:

>Notable: We now use the builtin color scopes (just like the intra line colorization for the normal diff views does). The Sublime Text scopes (e.g. "diff.inserted.char") are suffixed with ".git-savvy.inline-diff".

But honestly, this doesn't mean anything to me :/

**Comment by kaste** [comment]
Very helpful 🙄 

The link for manually editing color schemes is completely wrong. Either you use a downloaded, pre-installed scheme, t.i. something *not* in your user folder. Then:

1. Open `Preferences`, look up "color_scheme", copy the filename to your clipboard. 
2. Create an empty file with that name in your User folder.
3. Edit to you liking. E.g. 

```
{
   "rules":
    [
        {
            "scope": "diff.inserted",
            "foreground": "#f0f"
        },
    ]
}
```

The scopes being "diff.inserted", "diff.deleted", for intra-line modifications "diff.inserted.char" and "diff.deleted.char", t.i. suffixed with ".char". You can further narrow it down and suffix `.git-savvy` to only affect GitSavvy views. (the inline diff and normal diff) Or further suffix again with `.inline-diff` or `.diff` to change these independently.  (Hierarchic topology...) So you may end up with `"diff.deleted.char.git-savvy.inline-diff"` if you need full control. Likely not.

If you instead use a scheme already in your User folder, you just add some rules to it, and probably already know how to do this, ... well it is already in User.

**Comment by IPWright83** [comment]
@stevage I completely agree that the colours are too muted, I couldn't really use it so appreciate you raising this issue. I've put this together based on the suggestion of a color scheme.

```
{
    "rules": [
       {
        "scope": "diff.inserted",
        "foreground": "#fff",
        "background": "#2A8F41"
       },
       {
        "scope": "diff.deleted",
        "foreground": "#000",
        "background": "#d93f0b"
       },
       {
        "scope": "diff.deleted.char",
        "foreground": "#fff"
       },
       {
        "scope": "diff.inserted.char",
        "foreground": "#fff"
       }    
    ]
}
```

**Comment by kaste** [comment]
Admitted, it took me a week to like the standard colors, I actually like them a lot and even think they're a bit more clever.  We always had very prominent, bright highlighting here in GitSavvy, but compare that for example to the GitHub intraline colorization which is very light as well.

There is nothing to do here anyway as we just use the standard scopes newer themes implement anyway.  I do like the muted variants because it does not distract from reading the code actually.  I think with very bright highlighting we tend to just scan the lines for the highlighted regions but it makes reading the diff actually harder.
