### ISSUE TITLE
Inline-diff hops up after staging a hunk?

### ISSUE THREAD

**Issue by winehook** [timbrel/GitSavvy#1349]
Hello there -- love GitSavvy, depend on it every day.  Makes my life very easy, thank you.

Quick question though -- lately when I'm staging my commits using the inline-diff option, I find I'm jumping around in the document in a slightly weird fashion.  If I hit the . key to jump to a hunk, I go right to the hunk.  Hitting the h key to stage that hunk does stage it, but also jumps me backwards in the file about 20-30 lines.  So I'm not looking at the hunk I just approved, I'm now somewhere above that.  Hitting the . key takes me to the next hunk, where hitting h will again jump me upwards in the file.  

It's not a huge deal, but I'm wondering if this is something I knocked out of whack somehow in my settings or something else?  Thank you!

**Comment by kaste** [comment]
Annoying jumping is a bug. Either I did a mistake, or there is just no code for the particular case. A short screencast would help.  It is especially important if you're on a red or green line before staging. And if it's really staging or unstaging.  And if you're for example hunk the first hunk of the file or something in the middle. And if the hunk is only red, only green or both. 

You can also play a bit with it by hunking and then undoing, and hunking again but being on a different line.

**Comment by winehook** [comment]
Ok, I'll try to do a screen capture next time I'm experiencing it -- thanks

**Comment by winehook** [comment]
Ok, here's a screen cap.  https://cln.sh/zpXBFy 
What I do in the video is:
1. hit l to do the inline diff
1. hit . to go to the first hunk
1. hit h to stage the first hunk

You'll see that I then jump upwards in the file a bunch of lines.

I've done some testing locally to see if it makes a difference which line I'm on when hitting the h key, but it doesn't seem to make any difference at all.

Hope this is helpful?

**Comment by winehook** [comment]
Also, more info: it's hard to tell from the video because the line numbers are cut off, but it's jumping upwards about 100 lines.

**Comment by kaste** [comment]
I cannot reproduce this for such a simple case at all.  It's the first hunk, and a green one only.  

![rpN3FElvBF](https://user-images.githubusercontent.com/8558/91213851-81b87b00-e712-11ea-9910-86fd56b1944d.gif)

The screen cast above shows how it is intended. It's pixel-perfect.

Interesting, most bits of this line calculations is shared.  So I would expect that `o` to open the file at cursor position is also way off on your computer? Also `tab`. E.g. here I switch between the staged and unstaged area. 

![isCsrX8tC1](https://user-images.githubusercontent.com/8558/91214255-1c18be80-e713-11ea-890b-a03f8aaa1d8a.gif)

The intention here is that the current line stays at the exact same position although its line number changes. 

Btw, why doesn't `l` scroll to the first hunk automatically.  This is the default behavior on my machine as well?

Which ST version?  Did you restart ST in case it's just a temp glitch?

**Comment by winehook** [comment]
Wow, interesting.  I did just stop/start Sublime, with no change.  

If I use o to open the file, it does jump down to where the cursor is.  tab also works properly.  
But yeah, when I hit l to do inline diff, it always starts at the top of the file.  I have to hit . to jump down to the first hunk.

I did just go in and remove a handful of unused/old packages, but to no effect.  I may drop some others as well.

I'm running ST version 3.2.2. Build 3211.  Gitsavvy version is 2.25.4.  Should I try removing the package and then reinstalling it?

Dave

**Comment by kaste** [comment]
Well, the most interesting part is maybe the calculation of the relative row.  Place the cursor somewhere in a diff view. Open the Sublime console, and try the following code

```
>>> view.sel()[0].begin()
599
>>> cursor = view.sel()[0].begin()
>>> view.text_to_layout(cursor)
(61.0, 460.0)
>>> view.viewport_position()
(0.0, 62.0)
>>> view.line_height()
20.0
>>> (460.0 - 62.0) / 20.0
19.9
```

The actual numbers here are from my computer.  Regardless, the computation is that the cursor is 19.9 lines from the top of the view.  (So basically, the line number might be 25, but since I scrolled I'm roughly on 20th visible line.)

I wonder if this computation fails on your computer.

**Comment by kaste** [comment]
For the initial scrolling when using `l` I found that we have a setting `inline_diff_auto_scroll` which defaults to `true` but it looks like you have it set to `false` so it does *not* scroll to the first hunk automatically.

**Comment by kaste** [comment]
Could you try setting `"animate": false` in the global Preferences.  In your video it shows that `.` smoothly scrolls to the hunk.  So the root cause could be that the view (or viewport) is still scrolling while I compute the row/line offsets here.  Meaning, that in the code from above comment `viewport_position` returns an intermediate result.

**Comment by winehook** [comment]
Yup, that did it!  Wow, good catch.  Now hitting h zaps the hunk and I remain right there in the code.  Great find!

I already had inline_diff_auto_scroll set to 'true' in my default settings and just set it to 'true' in my user prefs, but still not jumping down, but I don't really care about that anyway.  It could be some other linter or something is getting in the way.  Not worried about it.  

Thank you for helping me diagnose!

**Comment by kaste** [comment]
I'll push a hotfix.  It somehow still looks like something scrolls up (for example to the beginning if the file) and then I measure in between and scroll down.  Since we're 100 lines or so off.  I could locally only reproduce small glitches for what should be pixel-prefect.  100 lines is *huge*.  Of course I'm curious why `inline_diff_auto_scroll` doesn't work.

**Comment by winehook** [comment]
For what it's worth, I just discovered an interesting thing: even though the view jumps up a bunch of lines, the actual cursor is still far below.  When I stage a hunk, if I hit the space, the view jumps back down to where the hunk was just staged.  So it's not that the cursor is in the wrong place, it's the view.  

I'm going to go through and remove a bunch more unused packages; perhaps something else I've got installed is causing this to happen.  Just wanted to share in case that made any difference for you.

**Comment by kaste** [comment]
So `animation_enabled: false` resolves the issue.  But the fixes I pushed don't?

And the initial scroll to the first hunk is also still broken?

**Comment by winehook** [comment]
I'm sorry, I feel like I'm turning into one of "those" people who provides confusing feedback.  My apologies if I'm muddying the waters.  Here's the latest:

1. After a restart of Sublime, now hitting the l to diff a file takes me to the first hunk.  Score!
1. I realized that I was jumping around more in larger files than in smaller files, so I started thinking about font size.  (I'm no spring chicken -- I've got the font cranked up a decent amount to help out my eyes.)  I went to Preferences->Font and Reset.  Bingo.  Now staging and unstaging a hunk doesn't jump around at all.  I stay right on the line.  I can't keep things this way, but at least that's an explanation.  
1. I'm seeing some unusual behavior with TAB -- hitting TAB now jumps me up a handful of lines (even with the font Reset).  If I keep hitting TAB, I keep jumping up -- eventually after about 10 or 20 hits I end up at the top of the file.  It's cycling back and forth between the staged/unstaged versions, I can see that in the title bar.  But it's consistently moving toward the top of the file.  I never really used TAB before, so it's not an issue for me, but wanted to share.

I hope this is helpful?

**Comment by kaste** [comment]
Well, we're basically in the dark here still.  So it's not animation and intermediate view states but fonts.  

Here is the function we use to compute the current position.  You can try this in Sublime's console.  

```
>>> from GitSavvy.core.view import capture_cur_position
>>> capture_cur_position(view)
Position(row=99, col=4, offset=34.75)
```

`row` and `col` are zero-based.  So here I'm actually on *line* 100.  The `offset` says I'm roughly at the 34th line in the viewport, t.i. basically counting *visible* lines.  

It would be interesting if this function actually works on your setup.

**Comment by winehook** [comment]
Ok, I've got a bit more data for you. 

I have a 1200+ line file.  Went in and made an edit, then did a git diff by line.
Jumped straight to the spot where the change was made.  Typed in the cur_position command and got this:

>>> capture_cur_position(view)
Position(row=1208, col=0, offset=9.0)

Then hit h to stage the hunk.  Jumped way off the screen.  Without typing anything else, went into the console and typed  position command and got this:

>>> capture_cur_position(view)
Position(row=1207, col=0, offset=59.03703703703704)

So it looks like the row is correct (my edit was deleting an entire line of code -- so changing line 1208 to 1207 would be exactly right) but that offset seems out of whack.

Is this helpful?

**Comment by kaste** [comment]
You don't have to use the diff stuff to test this.  You can activate an ordinary view, and put the cursor on some line.  Then execute `capture_cur_position(view)`.  Then count the lines from the top and see if they match.  Maybe they match if scrolled to the top of the view, maybe they begin to fail if you scroll 100 lines down.  

For example, put the cursor on line 100. Scroll all the way up to the top. Expected `Position(row=99, col=0, offset=99)`. Scroll roughly ten lines down expected `offset=89`. Etc.

**Comment by winehook** [comment]
Ok, well, I've done some experimenting -- the position function seems to accurately describe where the cursor is with respect to the viewport.  If I leave the cursor on one spot and scroll away, the position will tell me how far off the screen it is. So what I thought earlier was "interesting" was just the position function describing exactly what the state of things was.  The viewport jump up and away from the cursor when I stage the hunk.  

Anyway, I think at this point I'm just going to shift my workflow and do regular diffs rather the inline diffs.  It's not a problem.  There's likely something specific about my setup (perhaps I have an unusual key mapping?) that is interfering with this, and I don't want to waste your time anymore with it.  You can go ahead and close this ticket and we'll chalk it up to the mysteries of the universe.  Thanks again for your effort in trying to chase it down!  DV
