### ISSUE TITLE
Create fixup commit from graph view

### ISSUE THREAD

**Issue by FPtje** [timbrel/GitSavvy#1355]
## Proposal

In the GRAPH view, when pressing enter on a commit, add the option "Create fixup commit from stage", which is an alias for `git commit --fixup <commit>`. 

## Explanation

GitSavvy has two fixup related commands:

- git: fixup from stage
- git: quick stage current file and fixup

Both these options change the git history, by changing the commit to include the fixup. `git`, however has another option: `git commit --fixup <commit ref>`, the description of which is as follows:

```
--fixup=<commit>
Construct a commit message for use with rebase --autosquash. The commit message will be the subject line from the specified
commit with a prefix of "fixup! ". See git-rebase(1) for details.
```

I prefer this method when working in any non-master branch, precisely because it does not change history. This allows for a "soft" form of rebasing that allows other people to cooperate without force pulling. It also plays nicer with GitHub's review function. Right before merging into master, a `git rebase --autosquash` will do the actual rebasing.

## Why this is needed

My current way of creating fixup commits is as follows:

- Stage hunks/files in GitSavvy STATUS
- Copy commit ID from GitSavvy GRAPH
- In a terminal, enter `git commit --fixup <PASTE>`
- Push the branch from GitSavvy STATUS

This is cumbersome. Being able to fixup from GRAPH would be much nicer, since I use that to judge which commit I want to fixup anyway.

On another note, perhaps it would be nice to make the `git: fixup from stage` option available in GRAPH as well?

**Comment by kaste** [comment]
Yeah, that is cumbersome, and I do it often.  I actually don't fully grasp "our" fixup commands; I really just make a fixup commit and go on, and do the squashing later.  It is okay for the happy path but when the fixup does not apply and sure it doesn't apply all the time; our fixup command just aborts.  And then I'm really out of my flow. 

What I wanted to do is write a helper in the actual commit message view.  Basically you stage in a diff or the status view, then `c` to enter the commit message.  Here type `fixup<TAB>` and it will open a menu where you can select a commit; upon selection it will complete the commit subject.  (Same for squash.)

In the next release will be a "copy" helper, to copy the hash or commit message easier.  After that, I probably add some rebasing functionality into the graph. 

Your idea is also good, what I don't like in the graph is that I can't tell if I have a dirty state, or already something staged, etc.  Don't know if showing the action all the time would be okay.  (The actions menu shouldn't have too many options to not scare people.)

**Comment by FPtje** [comment]
Typing ˋfixup<tab>ˋ in the commit view sounds like a nice idea. I wonder, though, how would people know about that functionality? The commit view doesn't have any help text like the STATUS or GRAPH windows do. 

> In the next release will be a "copy" helper, to copy the hash or commit message easier. After that, I probably add some rebasing functionality into the graph.

Cool! 

> Don't know if showing the action all the time would be okay.

You could make it only show when there are staged files. The option makes no sense otherwise 👍

**Comment by kaste** [comment]
The commit view has help text

![image](https://user-images.githubusercontent.com/8558/91538756-98302380-e918-11ea-9add-84e979420381.png)

This is nicely written prose.  Maybe we should make it concise and tabular like the other help texts.

**Comment by kaste** [comment]
I like this idea, t.i. the original one, a lot.

**Comment by FPtje** [comment]
Thanks for adding this feature!
