### ISSUE TITLE
gs_show_commit with `HEAD` opens up the wrong commit

### ISSUE THREAD

**Issue by asfaltboy** [timbrel/GitSavvy#1368]
It used to show the last commit in current branch (i.e HEAD), and now it seems stuck to some commit down the tree... perhaps there's some caching magic that was added that identifies HEAD as a unique commit :/ .. not sure if there's a use case here for typical GitSavvy usage; but, for me, it can be nice to see a `skip_cache` sort of argument to avoid this.

**Comment by kaste** [comment]
That's just a bug.  Everywhere else I use the cache I explicitly check if `commit` is empty or `HEAD` and then skip the cache automatically.  Didn't foresee the use case here. 🤷
