### ISSUE TITLE
Command "git config"

### ISSUE THREAD

**Issue by mercurykd** [timbrel/GitSavvy#1372]
Open config in new tab
Options : --global, --system

**Comment by kaste** [comment]
Hm, I have this actually for the local config.  You can just use 

```json
  {
      "caption": "git: edit global config",
      "command": "gs_custom",
      "args": {
          "output_to_panel": false,
          "args": ["config", "--global", "-e"],
          "start_msg": "...",
          "complete_msg": "finished editing",
          "run_in_thread": true
      }
  },
```

**Comment by mercurykd** [comment]
> Hm, I have this actually for the local config. You can just use
> 
> ```json
>   {
>       "caption": "git: edit global config",
>       "command": "gs_custom",
>       "args": {
>           "output_to_panel": false,
>           "args": ["config", "--global", "-e"],
>           "start_msg": "...",
>           "complete_msg": "finished editing",
>           "run_in_thread": true
>       }
>   },
> ```

thx!

**Comment by kaste** [comment]
That's a portable command.  For your own system you can just open the file probably

```json
  {
		"caption": "git: edit global config",
		"command": "open_file", 
		"args": {
			"file": "~/.gitconfig"
		}
  }
```
