### ISSUE TITLE
Add `git show $commit` command to the graph view

### ISSUE THREAD

**Issue by gwenzek** [timbrel/GitSavvy#1375]
Would it be possible to add the `git show` command to the graph view ?

When selecting a commit and pressing `Enter`, I currently have Checkout, Create tag, Revert Commit, Reset branch to commit, Cherry pick, Compare against, Diff against, ...
Could we also have `Show commit` ?

(It's also possible to directly show the commit by pressing `o` instead of `Enter` but I think it would be more consistent

**Comment by kaste** [comment]
Well, you already found the shortcut o which is used throughout the app for navigation. Also ? to show the different bindings.  There is currently no plan to move that also to the actions menu as that becomes a too long list to browse.

**Comment by gwenzek** [comment]
I'm personally a big fan of the command palette, and I would rather prefer to have every action exposed in the palette. Filtering is quite easy anyway.

Thanks you for the plugin, cheers.

**Comment by asfaltboy** [comment]
@gwenzek if you're looking at a command that will display recent commits and allow you to show them, try `git: log`, it basically achieves the same thing.

For reference, you can add your own custom commands under [User Commands][1]. As a self-referential example to get started, you can create the following `User.sublime-commands` to have a useful command in the palette to edit your custom commands:

```json
[
    {
        "caption": "Preferences: User Commands",
        "command": "open_file",
        "args": {
          "file": "<sublime Packages dir>/User/User.sublime-commands"
        }
    }
]
```

[1]: https://sublime-text-unofficial-documentation.readthedocs.io/en/stable/reference/command_palette.html
