### ISSUE TITLE
enter insert mode is broken with NeoVintageous 1.22.0

### ISSUE THREAD

**Issue by iuliantatarascu** [timbrel/GitSavvy#1395]
NeoVintageous refactored command names (https://github.com/NeoVintageous/NeoVintageous/issues/749), so the enter insert mode feature in GitSavvy is broken

The following change would fix it:
```diff
--- GitSavvy/common/commands/view_manipulation.py
+++ GitSavvy/common/commands/view_manipulation.py (Unsaved)
@@ -21,6 +21,7 @@
             if self.savvy_settings.get("vintageous_enter_insert_mode"):
                 self.view.settings().set("vintageous_reset_mode_when_switching_tabs", False)
                 self.view.run_command("_enter_insert_mode")
+                self.view.run_command("nv_enter_insert_mode")


 class gs_handle_arrow_keys(TextCommand, GitCommand):
```

Versions:
Sublime Text 3.2.2 build 3211
GitSavvy 2.27.1
NeoVintageous 1.22.0

**Comment by kaste** [comment]
Thanks for lettings us know.  Do you want to make a PR, or should I fix it?

**Comment by iuliantatarascu** [comment]
I don't want to make a PR for just 1 line

**Comment by kaste** [comment]
Fair enough.
