### ISSUE TITLE
GitSavvy 2.27.2 ignores settings

### ISSUE THREAD

**Issue by domibarton** [timbrel/GitSavvy#1398]
Hi

First of all, pretty awesome work w/ GitSavvy. I've never seen a better (pro) Git integration anywhere else :) 

I use GitSavvy a lot and upgraded it to 2.27.2. After the upgrade, I experienced that these settings no longer work:

```
{
    "vintageous_friendly": true,
    "vintageous_enter_insert_mode": true
}
```

It isn't vintageous friendly and I will no longer be sent to `insert mode`. For example, when I open the `STATUS` view, I'm in `command mode`. When I go to insert mode and press tab, I will end up in the `BRANCHES`, but again in `command mode`.

I also replaced `super+s` (`cmd+s` on OS X) in the key bindings:

```
    {
        "keys": ["super+s"],
        "command": "gs_commit_view_do_commit",
        "context": [
            { "key": "setting.command_mode", "operator": "equal", "operand": false },
            { "key": "setting.git_savvy.get_long_text_view", "operator": "equal", "operand": true },
            { "key": "setting.git_savvy.commit_on_close", "operator": "equal", "operand": false }
        ]
    },
```

This no longer works and I'm stuck with the old behaviour.

**Comment by domibarton** [comment]
UPDATE: Yeah, I'm using NeoVintageous of course :)

**Comment by kaste** [comment]
Hm, I actually just applied the patch suggested in #1395 as a hotfix for the newest NeoVintageous.  It seemed reasonable and was only additive.  I did not actually test this change because I don't use the package.

**Comment by kaste** [comment]
The keybinding will not work because get_long_text_view as a marker has been removed/renamed in 2.27.0.  I'm not at my computer. I will look up the new name.

**Comment by kaste** [comment]
The new name is commit_view since #1377.

**Comment by domibarton** [comment]
I've updated to ST4, it works again w/ it. Shall I close the issue or shall I do some digging in ST3?

**Comment by domibarton** [comment]
> The new name is commit_view since #1377.

Yep that worked. Thanks, should've done more digging first… sorry :)

**Comment by kaste** [comment]
The intention is to keep GitSavvy ST3 compatible as long as possible.  I don't know if NeoVintageous is ST4 only.  I think it's too early to switch since ST4 is still closed alpha.  I only used it to find bugs.  I would appreciate some digging.

**Comment by kaste** [comment]
Closing as it looks solved.
