### ISSUE TITLE
More streamlined "push" and "create PR" flow

### ISSUE THREAD

**Issue by kaste** [timbrel/GitSavvy#1411]
"Creating a PR" should behave like `gs_push` and for example read the same settings, like `prompt_for_tracking_branch`.  But overall the workflow is hitting too many times `<enter>`.  

- First, we ask basically "really?".  For example, you exec `gs_push`, then we ask "really? should we set an upstream?".  Yes of course, that's what I was asking for.  
- We ask for a remote even if there is only one.
- We ask for a remote branch name, although it is weird and usually confusing to *not* take the same name as the local one.  Why would you even do that?  If the name is taken on the remote?  Probably rename the local branch as well.  

All 3 questions can be aborted.  So the "really?" is really not necessary, is it?  I do understand that we want *some* pause before the actual action.  Basically if we were to take the first remote (if there is only one), and just take the local branch name, *then* we would just push it to the server without the "really" question.  Promptly which is maybe to fast.  

We could omit the "really" though, and make the branch name question mandatory.  So one `enter`, or `esc` to abort, if there is only one remote.  Otherwise two times `<enter>`.  We would go from 3 enter's, to either 2 or 1 enter.  (And remove one setting which nobody flipped anyway because the code on `false` was wrong (or annoying) in that it never set the upstream!)

For `gs_push` this would be relatively clear.  For "Create PR", it is a bit confusing because we ask of course for the remote we push the code to which is *not* necessarily the base remote we open the PR against.

_Originally posted by @kaste in https://github.com/timbrel/GitSavvy/pull/1409#issuecomment-721364506_

**Comment by braver** [comment]
I've always found these questions superfluous. Sure, I understand that the command line client requires a high level of explicitness. But other clients should be closer to what most people actually do most of the time. 

You created a new branch? Then of course you push it to the only remote and you give it the same name on the remote as locally and of course it should track. The defaults are super clear and will work almost always. 

So, perhaps, take those defaults, and then prompt: "hey this is what we're about to do, if you agree just hit `<enter>`" and you're done. And if someone answers that prompt with "no, cancel, I don't want that", _then_ take them through the existing 3-step flow. For the "create PR" flow maybe preface that with the remote question, but even then it's not uncommon to push just to `origin` (I hardly do anything else, a PR doesn't have to come from a fork).

**Comment by kaste** [comment]
As per #1416 

a) If there is only one remote, take it. Ask "Push to origin/branch_name"? Merely as a stopping point, but the branch_name is editable (branch_name is obv. the _current_ branch name). That essentially leads to one <enter> to push.

b) With more remotes, we first ask for the remote, then proceed with a), coming down to two <enter>s.

At any time ESC aborts the process. -u is always set.

From the UI point of view, we always have the same problems: quick panels open at the top of the screen, input handlers at the bottom.

Different flow:

With one remote, open quick panel with two items: c) ["Push to origin/branch", "Let me edit the branch name"].  With more remotes: d) ["Push to origin/branch", "Push to kaste/branch", ..., "Let me choose the remote and the branch name separate"].  

For c) it comes down typically to one enter just as a), and more work than a) if you want to edit the branch name.  Personally, I always have multiple remotes, so I would see d) with 5+ remotes.  Undecided, wdyt?

#146 implements a) b) as it's way simpler to code coming from  what we already have.
