### ISSUE TITLE
10 seconds of lag per commit when performing fixup operations 

### ISSUE THREAD

**Issue by odinhb** [timbrel/GitSavvy#1418]
I'm experiencing a crippling slowdown when using the performing actions 'fixup from stage' (through command palette) or `[Q] squash commit with ... ` (on the rebase panel)

Sublime text freezes completely for a good ~40-60 seconds on average. It is evident from the logs that I have to wait 10 seconds for every commit shown/manipulated by the rebase panel.

Using git normally from the terminal does not produce any of these slowdowns. This issue has knocked me into the terminal as I used to rely on GitSavvy for these actions.

Using `[u] move commit up (before previous)` and `[d] move commit down (after next)` does not cause this lag.
Actually rebasing my branch using the rebase panel does not cause any lag.
Showing commits (`[w] show commit`) or editing commit messages(`[e] edit commit message`) with the rebase panel are also unaffected.

#### Environment
**GitSavvy version:** v.2.27.4 (Package Control v3.4.1)

```console
$ uname -srvmpoi
Linux 5.9.0-8.3-liquorix-amd64 #1 ZEN SMP PREEMPT liquorix 5.9-5ubuntu1~bionic (2020-11-15) x86_64 x86_64 x86_64 GNU/Linux
$ git --version
git version 2.17.1
$ subl --version
Sublime Text Build 3211
```

<details>
<summary>console output when issue occurs</summary>

```console
$ git commit --author Odin H B <odinh2908@gmail.com> --date 1605881392 -F -
[detached HEAD 19b6d039c] fix models/invoice_transcription_spec
[detached HEAD 215f0f47a] fix ocr_statistics_controller_spec
[detached HEAD d409e6e1f] fix invoice_inbox_controller_spec
[detached HEAD d20911838] rewrite the invoice_transcription factory
[detached HEAD 36b8ac08b] fix invoice_transcription_previous_data_reports_controller_spec
 Date: Fri Nov 20 15:13:30 2020 +0100
 Date: Fri Nov 20 15:11:33 2020 +0100
 Date: Fri Nov 20 15:10:51 2020 +0100
 Date: Fri Nov 20 15:13:43 2020 +0100
 Date: Fri Nov 20 15:09:52 2020 +0100
 1 file changed, 321 insertions(+), 281 deletions(-)
 1 file changed, 6 insertions(+), 2 deletions(-)
 4 files changed, 636 insertions(+), 615 deletions(-)
 1 file changed, 12 insertions(+), 9 deletions(-)
 1 file changed, 58 insertions(+), 54 deletions(-)
 rewrite spec/factories/invoice_transcriptions.rb (97%)

[Done in 10.03s]
[Done in 10.03s]
[Done in 10.03s]
[Done in 10.02s]
[Done in 10.03s]
```

</details>

[gitsavvy log when reproducing issue](https://pastebin.com/d20Zvjpm)

**Comment by kaste** [comment]
I don't have a good idea here.  Why should every commit take exactly 10s?  Do you have any hooks installed?  (Although, I think most or all(?) of them don't even run when you do a `commit -F`.)

Maybe do a normal fixup commit, and then apply it from the Repo History via the `r` menu when the cursor is on that fixup commit.

**Comment by odinhb** [comment]
> Maybe do a normal fixup commit, and then apply it from the Repo History via the r menu when the cursor is on that fixup commit.

I tried this and it worked without any lag. Thanks for showing me another feature of GitSavvy :)

> Do you have any hooks installed? 

There are no commit hooks installed in either of the repos I have experienced this problem in. It seems to be computer-wide. I'll see if I can reproduce this on my home computer/laptop sometime.

**Comment by odinhb** [comment]
Tested on a slightly different environment (my laptop)(not very different though):

GitSavvy version: v.2.27.5 (Package Control v3.4.1)

```
$ uname -srvmpoi
Linux 5.9.0-11.2-liquorix-amd64 #1 ZEN SMP PREEMPT liquorix 5.9-9ubuntu1~focal (2020-11-27) x86_64 x86_64 x86_64 GNU/Linux
$ git --version
git version 2.25.1
$ subl --version
Sublime Text Build 3211
```

But I've so far failed to reproduce it with a basic git repo. (with just some text files)

**Comment by kaste** [comment]
Maybe it's just some weird edge case on the old git v2.17.1?

**Comment by odinhb** [comment]
> Maybe it's just some weird edge case on the old git v2.17.1?

I recently upgraded some software on the original environment I posted. It now has the same git version as my laptop.
I just tried to squash a commit into another with `[Q] squash commit with ... ` on the rebase panel but the problem persists.

```
# (from apt)
Package: git
Version: 1:2.25.1-1ubuntu3

$ git --version
git version 2.25.1
```

I don't think this is the cause.

**Comment by kaste** [comment]
Just letting you know that I have no idea what's going on here.  Sure, a commit can be slow under some circumstances, for example if you're working on Chromium.  Otherwise I'm completely in the dark here.  

Can you -- given the log you posted you know which commands we run here -- replicate on the command line?  Is this generally a fast repo?  Or are for example git status calls and commits already a bit slow because of the size or structure of the repo?

Hm, are there actually ENV variables or something like that to make git more verbose, or do we have to make custom builds for that?

**Comment by odinhb** [comment]
I tried running
```
$ echo 'test' | git commit --author "<snip>" --date "123456" -F -
$ echo 'test' | git commit --date "123456" -F -
$ echo 'test' | git commit --author "<snip>" -F -
$ echo 'test' | git commit -F -
$ git commit --author "<snip>" --date "123456" # which opens an editor for the message, so it waits for that, but nothing more
```
On the big repo on the problem machine. None of them produce a slowdown like when invoked from GitSavvy.

I'd like to note that the "big" repo is not all that big (as far as I know, and in git terms) (~200k LOC). The problem also occured on a smaller repo (~50k LOC) on the same machine.

>  Is this generally a fast repo?

The only thing I experience lag with is the graph view (the history of the project is quite long). Other than that the repo is still and has always been generally snappy when using git.

> Hm, are there actually ENV variables or something like that to make git more verbose, or do we have to make custom builds for that?

I found [some talk](https://stackoverflow.com/questions/7319357/does-git-add-have-a-verbose-switch) of git having a verbose switch, but it didn't work on the `commit` command.

**Comment by odinhb** [comment]
Normally the console output from GitSavvy looks like this:

<details>

```
$ git commit --author Odin H B <odinh2908@gmail.com> --date 1607693149 -F -
[detached HEAD 9246420d4] more xsd
 Date: Fri Dec 11 14:25:49 2020 +0100
 5 files changed, 50 insertions(+), 34 deletions(-)

[Done in 0.07s]
[Done in 0.08s]
[Done in 0.07s]
[Done in 0.05s]
```

</details>

This is me running `[q] squash commit with previous` from the rebase panel.

Just to confirm, I ran another 'fixup from stage' from command pallete (with just three commits involved) and it still freezes the whole edtiro for a good 20 sec. There are indeed spooky ghosts in the code still. :ghost:

**Comment by odinhb** [comment]
[I found some debug tracing env variables](https://www.shellhacks.com/git-verbose-mode-debug-fatal-errors/)

<details>
<summary>git commit -m "test"</summary>

```
$ GIT_TRACE=true GIT_TRACE_PERFORMANCE=true git commit -m "test"
14:38:57.812762 git.c:439               trace: built-in: git commit -m test
14:38:57.815343 read-cache.c:2306       performance: 0.001168390 s:  read cache .git/index
14:38:57.819658 preload-index.c:147     performance: 0.004282278 s:  preload index
14:38:57.819943 preload-index.c:147     performance: 0.000189789 s:   preload index
14:38:57.819984 read-cache.c:1621       performance: 0.000232086 s:  refresh index
14:38:57.820513 cache-tree.c:444        performance: 0.000432470 s:  cache_tree_update
14:38:57.823192 read-cache.c:3033       performance: 0.002667605 s:  write index, changed mask = 20
14:38:57.823685 unpack-trees.c:1592     performance: 0.000052868 s:    traverse_trees
14:38:57.823713 unpack-trees.c:1691     performance: 0.000096166 s:   unpack_trees
14:38:57.823721 diff-lib.c:537          performance: 0.000149795 s:  diff-index
14:38:57.823877 cache-tree.c:444        performance: 0.000007050 s:  cache_tree_update
14:38:57.824378 run-command.c:663       trace: run_command: git gc --auto
14:38:57.825656 git.c:439               trace: built-in: git gc --auto
14:38:57.825954 trace.c:475             performance: 0.000380531 s: git command: /usr/lib/git-core/git gc --auto
[iso20022-camt_xsd_and_duplicate_prevention 0821e6213] test
 1 file changed, 2 insertions(+)
14:38:57.826700 trace.c:475             performance: 0.014236031 s: git command: git commit -m test
```

</details>

<details>
<summary>echo "test" | git commit -F -</summary>

```
$ echo "test" | GIT_TRACE=true GIT_TRACE_PERFORMANCE=true git commit -F -
14:44:12.666339 git.c:439               trace: built-in: git commit -F -
14:44:12.669527 read-cache.c:2306       performance: 0.001484255 s:  read cache .git/index
14:44:12.672384 preload-index.c:147     performance: 0.002817136 s:  preload index
14:44:12.672637 preload-index.c:147     performance: 0.000177864 s:   preload index
14:44:12.672705 read-cache.c:1621       performance: 0.000246108 s:  refresh index
14:44:12.673258 cache-tree.c:444        performance: 0.000449262 s:  cache_tree_update
14:44:12.675921 read-cache.c:3033       performance: 0.002651434 s:  write index, changed mask = 20
14:44:12.676619 unpack-trees.c:1592     performance: 0.000054885 s:    traverse_trees
14:44:12.676657 unpack-trees.c:1691     performance: 0.000139039 s:   unpack_trees
14:44:12.676666 diff-lib.c:537          performance: 0.000203055 s:  diff-index
14:44:12.676907 cache-tree.c:444        performance: 0.000013114 s:  cache_tree_update
14:44:12.677528 run-command.c:663       trace: run_command: git gc --auto
14:44:12.678795 git.c:439               trace: built-in: git gc --auto
14:44:12.679135 trace.c:475             performance: 0.000448057 s: git command: /usr/lib/git-core/git gc --auto
[iso20022-camt_xsd_and_duplicate_prevention c1936bce0] test
 1 file changed, 2 insertions(+)
14:44:12.679971 trace.c:475             performance: 0.013860259 s: git command: git commit -F -
```
</details>

It looks like git is running git gc --auto once per commit. Might be the culprit. A few days before I noticed this problem git spat some warnings at me asking me to run `git gc` and `git prune`, so I did until it shut up.

**Comment by odinhb** [comment]
Tried throwing this in User/GitSavvy.sublime-settings:

```json
  "env": {
    "GIT_TRACE": true,
    "GIT_TRACE_PERFORMANCE": true,
  },
```

But GitSavvy is freaking out:

```
$ git stash list (/home/odin/dev/work/fakturabank/repo)

Please report this error to GitSavvy:

expect bytes or str, not bool

Traceback (most recent call last):
  File "/home/odin/.config/sublime-text-3/Installed Packages/GitSavvy.sublime-package/core/git_command.py", line 167, in git
    startupinfo=startupinfo)
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1367, in _execute_child
  File "./python3.3/subprocess.py", line 1367, in <listcomp>
  File "./python3.3/os.py", line 791, in fsencode
TypeError: expect bytes or str, not bool
```

So it's not very easy to run the commands that are slow.

**Comment by kaste** [comment]
Interesting stuff.  For the `env` setting, I think it is just a `str -> str` mapping.  So set `"1"`or `"true"`

**Comment by odinhb** [comment]
> For the env setting, I think it is just a str -> str mapping. So set "1"or "true"

Derp. To err is human. With this corrected I could run the commands with logging enabled.

<details>
<summary>console ouput - 20s per commit now...</summary>

```
$ git commit --author Odin H B <odinh2908@gmail.com> --date 1607602372 -F -
[detached HEAD 81a3f4f27] add checksum to iso entries
[detached HEAD 934de2273] fix zero files in fileuploader
15:29:07.399793 git.c:439               trace: built-in: git commit --author 'Odin H B <odinh2908@gmail.com>' --date 1607607481 -F -
[detached HEAD e326e7441] wip: add xsd validation
15:29:27.527978 git.c:439               trace: built-in: git commit --author 'Odin H B <odinh2908@gmail.com>' --date 1607602372 -F -
15:28:47.239493 git.c:439               trace: built-in: git commit --author 'Odin H B <odinh2908@gmail.com>' --date 1607611985 -F -
15:29:07.401221 read-cache.c:2306       performance: 0.000558951 s:  read cache .git/index
 Date: Thu Dec 10 13:12:52 2020 +0100
 Date: Thu Dec 10 15:53:05 2020 +0100
15:29:27.529257 read-cache.c:2306       performance: 0.000497776 s:  read cache .git/index
 Date: Thu Dec 10 14:38:01 2020 +0100
15:28:47.240475 read-cache.c:2306       performance: 0.000495456 s:  read cache .git/index
15:29:07.403755 preload-index.c:147     performance: 0.002519095 s:  preload index
 11 files changed, 3281 insertions(+), 23 deletions(-)
15:29:27.531577 preload-index.c:147     performance: 0.002305845 s:  preload index
 10 files changed, 133 insertions(+), 16 deletions(-)
 4 files changed, 17 insertions(+), 2 deletions(-)
15:28:47.243661 preload-index.c:147     performance: 0.003167917 s:  preload index
15:29:07.403970 preload-index.c:147     performance: 0.000153004 s:   preload index
 create mode 100644 lib/iso20022/xsd/README
15:29:27.532241 preload-index.c:147     performance: 0.000211578 s:   preload index
15:28:47.243923 preload-index.c:147     performance: 0.000157630 s:   preload index
15:29:07.405354 read-cache.c:1621       performance: 0.001537222 s:  refresh index
 create mode 100644 lib/iso20022/xsd/camt.053.001.02.xsd
15:29:27.533230 read-cache.c:1621       performance: 0.001200688 s:  refresh index
15:28:47.245484 read-cache.c:1621       performance: 0.001718758 s:  refresh index
15:29:07.406467 unpack-trees.c:1592     performance: 0.000104167 s:    traverse_trees
 create mode 100644 lib/iso20022/xsd/camt.054.001.02.xsd
15:29:27.534323 unpack-trees.c:1592     performance: 0.000054091 s:    traverse_trees
15:28:47.246612 cache-tree.c:444        performance: 0.000999121 s:  cache_tree_update
15:29:07.406484 unpack-trees.c:1691     performance: 0.000148411 s:   unpack_trees
 create mode 100644 spec/fixtures/iso20022/invalid/by_xsd1.xml
15:29:27.534341 unpack-trees.c:1691     performance: 0.000105363 s:   unpack_trees
15:29:07.406494 diff-lib.c:537          performance: 0.000196457 s:  diff-index
15:28:47.248735 read-cache.c:3033       performance: 0.002111196 s:  write index, changed mask = 20
 create mode 100644 spec/fixtures/iso20022/unknown_revision.xml
15:29:27.534350 diff-lib.c:537          performance: 0.000155033 s:  diff-index
15:29:07.406665 cache-tree.c:444        performance: 0.000004125 s:  cache_tree_update
15:28:47.249211 unpack-trees.c:1592     performance: 0.000100607 s:    traverse_trees
15:29:27.534514 cache-tree.c:444        performance: 0.000004866 s:  cache_tree_update
15:29:07.407927 run-command.c:663       trace: run_command: git gc --auto
15:28:47.249227 unpack-trees.c:1691     performance: 0.000130856 s:   unpack_trees
15:29:27.535509 run-command.c:663       trace: run_command: git gc --auto
15:29:07.409109 git.c:439               trace: built-in: git gc --auto
15:28:47.249233 diff-lib.c:537          performance: 0.000183171 s:  diff-index
15:29:27.536662 git.c:439               trace: built-in: git gc --auto
15:29:07.409390 trace.c:475             performance: 0.000365849 s: git command: /usr/lib/git-core/git gc --auto
15:28:47.249370 cache-tree.c:444        performance: 0.000006086 s:  cache_tree_update
15:29:27.536971 trace.c:475             performance: 0.000397020 s: git command: /usr/lib/git-core/git gc --auto
15:29:07.421191 trace.c:475             performance: 0.021528995 s: git command: /usr/bin/git commit --author 'Odin H B <odinh2908@gmail.com>' --date 1607607481 -F -
15:28:47.250345 run-command.c:663       trace: run_command: git gc --auto
15:29:27.539880 trace.c:475             performance: 0.012027194 s: git command: /usr/bin/git commit --author 'Odin H B <odinh2908@gmail.com>' --date 1607602372 -F -
15:28:47.251602 git.c:439               trace: built-in: git gc --auto
15:28:47.270844 trace.c:475             performance: 0.019349080 s: git command: /usr/lib/git-core/git gc --auto
15:28:47.279020 trace.c:475             performance: 0.039644141 s: git command: /usr/bin/git commit --author 'Odin H B <odinh2908@gmail.com>' --date 1607611985 -F -

[Done in 20.05s]
[Done in 20.03s]
[Done in 20.02s]
```

</details>

[GitSavvy debug log](https://pastebin.com/PGn6N9Uu)

**Comment by kaste** [comment]
Okay.  That sure looks like it runs multiple things in parallel.  Having multiple `[Done]`s in one panel output is fishy too.  What's your setting for `show_panel_for` and `live_panel_output`? 

Honestly, it's like your running multiple GitSavvy versions in parallel.  Did you restarted Sublime lately?  Can you just turn on normal logging via the Command Palette `GitSavvy: enable logging` which will print basic information on the standard Sublime console.  For example it will print the commands we run here (again) but also the thread we run on, for example `M` or `D` or `T`. 

From the performance trace we can see that git runs as fast as ever.   The combination GitSavvy/Sublime seems to take 19s to render the panel and decode the output.  

If "live_panel" is on, try to turn it off.

**Comment by kaste** [comment]
That would very well explain the "10s", because the live panels waits to finish rendering via `"live_panel_output_timeout": 10000,` t.i. by default 10 seconds.

**Comment by kaste** [comment]
My hunch is that the above squash job runs on `M` and "live_panel" is on.  I can replicate that for commands that run on `M`, we then freeze because we read stdout and stderr from a different thread (say `T`), then try to write to the panel.  For this write, Sublime implicitly waits for `M` (because it wants to lock the app state/view) but `M` waits for `T` (for 10 seconds).  Hence we deadlock for the timeout. 

The specific issue with the rebase commands has been introduced via 1e31e247 (Let `LogPanel` continue synchronous on `enter`) published as 2.27.0 (Oct, 20, 2020).  The actual bug is a thinking error/design bug of the feature I think.

**Comment by odinhb** [comment]
Can confirm: I had `"live_panel_output": true` in my GitSavvy config. Setting it to `false` resolved the problem.

I haven't touched `show_panel_for` or `live_panel_output_timeout`. I think you figured it out.

I'm not sure what you mean by `GitSavvy: enable logging` for threading information though. I've been using this command to get the JSON debug log.

**Comment by kaste** [comment]
> I'm not sure what you mean by GitSavvy: enable logging for threading information though. I've been using this command to get the JSON debug log.

If you just open the Sublime console (Menu: `View > Show Console`), you get some simpler logging, for example:

```
 (M) [ 69ms] $ git remote -v
 (M) [ 97ms] $ git checkout -B typecheck-mixins
 (D) [ 78ms] $ git status --porcelain -z -b
```

Here `(M)` and `(D)` represent different threads.  Obviously, this is really needed for development, but may be interesting for end-users as well, to check which commands we run, the ordering, and generally their runtime.  

I decided to publish a hotfix here.  The actual *underlying* bug you found here will be fixed in a later release.  Really, *really* thanks for sticking with me so I could finally see the obvious deadlocking here.  ❤️
