### ISSUE TITLE
Binary file(s) in repo error

### ISSUE THREAD

**Issue by cvickery** [timbrel/GitSavvy#1426]
I got this message:

```
$ git diff --no-color --patch --stat --cached (/Library/Server/Web/Data/Sites/babbage.cs.qc.cuny.edu)

Please report this error to GitSavvy:

'charmap' codec can't decode byte 0x9d in position 1176870: character maps to <undefined>

Traceback (most recent call last):
  File "/Users/vickery/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package/core/git_command.py", line 192, in git
    stdout, stderr = self.decode_stdout(stdout), self.decode_stdout(stderr)
  File "/Users/vickery/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package/core/git_command.py", line 280, in decode_stdout
    decoded, _ = self.try_decode(stdout, encodings)
  File "/Users/vickery/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package/core/git_command.py", line 292, in try_decode
    raise err
  File "/Users/vickery/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package/core/git_command.py", line 288, in try_decode
    return input.decode(encoding), encoding
  File "./python3.3/encodings/cp1252.py", line 15, in decode
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 1176870: character maps to <undefined>

```
But I'm able to commit and push the repo anyway.

**Comment by kaste** [comment]
To clarify, you get the error before entering the commit message?

**Comment by cvickery** [comment]
No, when I do the commit. It’s trying to show the diffs on the commit message file. After dismissing two (typically two) modal dialogs alerting me to the issue, the commit file comes up without the diffs.
I haven’t tried to enter the commit message at that point … rather, I’ve been doing the commit and push from the command line.

Chris Vickery

On Dec 1, 2020, at 5:09 PM, herr kaste <notifications@github.com<mailto:notifications@github.com>> wrote:



To clarify, you get the error before entering the commit message?

**Comment by kaste** [comment]
Multiple things going wrong here.  

- We don't need to show a modal dialog. It is not fatal, and instead we could just print the help text (e.g. "Could not decode the diff output.  ...") instead of the typical diff below the commit message.  

- Multiple modals aren't fine either.  

That being said, git should also detect binary files and exclude them automatically from the diff.  (Or rather only print the summary of such files, not completely "exclude".) 

How can I reproduce this?  If I just add some binary files, GitSavvy produces this:

![image](https://user-images.githubusercontent.com/8558/100861604-5d4b0800-3492-11eb-94f0-c59c53ebc8f0.png)

**Comment by cvickery** [comment]
I was able to find a file that triggers the problem for me. If I run file on other files like it, they all come up “ASCII” but this one comes up “data” because there has been some bit rot of the text file (it’s been around for a long time!) — see line 86 of the attached “418.maybe” file. So maybe diff decides it’s text based on the beginning, then gets thrown off by the non-UTF-8 garbage later on.

Hope this helps,
Chris Vickery

**Comment by kaste** [comment]
You can't attach a file to a GitHub issue per email.  I just mocked it for development as it was basically clear what happens on our side.  

To start a file in one encoding and then switch the encoding later on is usually the best way to trick file type detection heuristics.  

Just released, usually takes an hour to get available as an update.

**Comment by cvickery** [comment]
Thanks!
Chris Vickery


On Dec 3, 2020, at 10:10 AM, herr kaste <notifications@github.com<mailto:notifications@github.com>> wrote:



You can't attach a file to a GitHub issue per email. I just mocked it for development as it was basically clear what happens on our side.

To start a file in one encoding and then switch the encoding later on is usually the best way to trick file type detection heuristics.

Just released, usually takes an hour to get available as an update.
