### ISSUE TITLE
github review pull request adds a git-style remote

### ISSUE THREAD

**Issue by rchl** [timbrel/GitSavvy#1464]
1. I'm an owner of the project and someone creates a PR
2. Use `github: review pull request` -> select branch -> `Checkout as local branch`

The local branch remote is set to git-style URL (`git@github.com:...`) instead of HTTP-style URL (`https://github.com/...`). That creates problems if I want to push some changes to that fork as I can only do that when using the HTTP-style URL. Only an owner can push to git-style URL.

**Comment by rchl** [comment]
I always use ssh-style URLs for my repos since access to that one is controlled through SSH keys. The HTTPS-style requires tokens to be created instead (at least when using Two-factor authentication).

The #1307 fix has a lot of comments which makes it a bit hard to figure out all the intentions and reasoning...

> Do you have a source for that? That would make the improvement in #1307 a regression.

I don't have any source, only empirical experience.

Github's own documentation doesn't say that only HTTPS works for that and it even mentions the ssh-style checkout as a viable option (https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/committing-changes-to-a-pull-request-branch-created-from-a-fork).

For me I always get "permission denied" when trying to push to a fork using ssh-style URL.

Maybe @randy3k has something to add here.

**Comment by kaste** [comment]
Yeah, it's a bit convoluted.  Discussion starts https://github.com/timbrel/GitSavvy/pull/1307#discussion_r434115139  Do you have both protocols configured on your system and use ssh for the *origin* and *https* for the people?

**Comment by rchl** [comment]
Yes, I use both on my system. I can push to forks using HTTPS if I add the remote using the `https` URL.

**Comment by kaste** [comment]
You shouldn't get the "permission denied".  I found more examples using `git@` for example on stackoverflow than `https`.  (E.g. https://stackoverflow.com/a/46063271/1526957 suggests to just use `git push git@github.com:user/repo local_branch_name:remote_branch_name` for ad-hoc changes which is actually quite nice because you don't have to clean up your remotes all the time.)

**Comment by rchl** [comment]
I had a chance to test again using git URLs and it works. :)

**Comment by kaste** [comment]
Haha  😁
