### ISSUE TITLE
Feature to solve conflicts like Atom editor

### ISSUE THREAD

**Issue by rafaelribeiroo** [timbrel/GitSavvy#1482]
Hello guys, how r u? Hope fine. Well, I love sublime and all stuffs, I know exists sublime merge but I’m looking forward for a “GUI” like atom editor, when conflicts, show in file two “USE ME” to solve, like image below, there’s one way to do this in GitSavvy?

![2b97c2caa4dd980204e77c94c4efda8987e96e42](https://user-images.githubusercontent.com/19275140/120140627-4b33f300-c1b1-11eb-89c9-c6783c546a9d.png)

**Comment by kaste** [comment]
Ah that's interesting.  GitSavvy doesn't have that ATM.  What happens with these buttons when you partly edit the conflict, taking for granted that you can actually manually edit the conflicts as well.  Do the dots beside the USE ME open a menu with further options?

**Comment by kaste** [comment]
Closing as the feature request isn't clear.
