### ISSUE TITLE
Keyboard shortcut for github integration

### ISSUE THREAD

**Issue by sfdye** [timbrel/GitSavvy#1489]
Is it possible to configure a keyboard shortcut for `github: open file no remote`?

**Comment by kaste** [comment]
Yes, the command is called `gs_github_open_file_on_remote`.

**Comment by sfdye** [comment]
Lovely, just reproduced the intelliJ behavior
```
	  { "keys": ["super+option+g"], "command": "gs_github_open_file_on_remote" },
```
