### ISSUE TITLE
Will be possible to just add gs_quick_stage_current_file command?

### ISSUE THREAD

**Issue by ellipticaldoor** [timbrel/GitSavvy#1493]
Looks like right now there is only this options
```
gs_quick_stage_current_file_and_fixup
gs_quick_stage_current_file_commit
gs_quick_stage_current_file_and_amend
```

Will be nice to have just gs_quick_stage_current_file, is this hard to add? Can I do it myself? I can't find how

**Comment by kaste** [comment]
You can probably do 

```
    {
        "command": "gs_custom",
        "args": {
            "args": ["add", "{FILE_PATH}"],
            "start_msg": "",
            "complete_msg": ""
        }
    },
```

However, it is recommended to bind `diff` to a key.  For example

```
  {
      "keys": ["ctrl+shift+."],
      "command": "gs_diff",
      "args": { "current_file": true }
  },
```

Then `ctrl+shift+. S` will do the same, `ctrl+shift+.` again to close the diff, it toggles.

`ctrl+shift+. C` to start the commit process.  `ctrl+shift+. Sm` to stage and amend.  `ctrl+shift+. C fix<TAB>` to make a fixup commit.  etc...

**Comment by ellipticaldoor** [comment]
Thank you, this works fine
