### ISSUE TITLE
OSError: resource 'auto' not found

### ISSUE THREAD

**Issue by cig0** [timbrel/GitSavvy#1502]
Hi,

I've got this error when `git: File history`, `git: Line history`, and `git: Repo history`:

```python
Package Control: Skipping automatic upgrade, last run at 2021-08-26 16:42:29, next run at 2021-08-26 17:42:29 or after
Exception in thread Thread-47:
Traceback (most recent call last):
  File "/Users/cig0/Library/Application Support/Sublime Text/Installed Packages/GitSavvy.sublime-package/common/theme_generator.py", line 58, in __init__
    self.color_scheme_string = sublime.load_resource(original_color_scheme)
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime.py", line 435, in load_resource
    raise IOError('resource "%s" not found' % name)
OSError: resource "auto" not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 858, in run
  File "/Users/cig0/Library/Application Support/Sublime Text/Installed Packages/GitSavvy.sublime-package/core/commands/log_graph.py", line 237, in augment_color_scheme
    themeGenerator = ThemeGenerator.for_view(view)
  File "/Users/cig0/Library/Application Support/Sublime Text/Installed Packages/GitSavvy.sublime-package/common/theme_generator.py", line 53, in for_view
    return JSONThemeGenerator(color_scheme)
  File "/Users/cig0/Library/Application Support/Sublime Text/Installed Packages/GitSavvy.sublime-package/common/theme_generator.py", line 156, in __init__
    super().__init__(original_color_scheme)
  File "/Users/cig0/Library/Application Support/Sublime Text/Installed Packages/GitSavvy.sublime-package/common/theme_generator.py", line 63, in __init__
    raise IOError("{} cannot be found".format(original_color_scheme))
OSError: auto cannot be found

```

The output seems to be fine, however.

Specs:
Sublime Text 4 Build 4113
GitSavvy: 2.31.0

**Comment by cig0** [comment]
Hi @stoivo:

```json
"color_scheme": "auto",
"light_color_scheme": "Packages/Color Scheme - Default/Celeste.sublime-color-scheme",
"dark_color_scheme": "Packages/Theme - Monokai Pro/Monokai Pro.sublime-color-scheme",
```

**Comment by stoivo** [comment]
ah, It a new feature in sublime text 4. We could determine the color color_scheme with `sublime.ui_info()['color_scheme']['resolved_value']` for sublime > 4096 and old logic for other.

**Comment by gwenzek** [comment]
For me the "_right solution_" would be to replace the Git savvy scopes https://github.com/gwenzek/GitSavvy/blob/3b71e40b3f708e4163a2b0b636fca325f1b5a33b/core/commands/log_graph.py#L90-L94

by the "magic" colored scope (`region.redish`, etc): https://www.sublimetext.com/docs/api_reference.html#sublime.View.add_regions
This way you don't need to override the view scheme, and you let SublimeText deal with the light/dark scheme.
You can see what it would look like at: https://github.com/timbrel/GitSavvy/commit/10f08252a95e32e8ffa3e72ea5aa7e67750a996c.
This would require a bit more work to make the colors configurable, let me know if you're interested.

(Meanwhile I opened #1645)

**Comment by kaste** [comment]
The "-ish" scope do not behave nicely here.  They never look right iirc because they don't have the right fore- and background set.  Maybe that changed though, you could try and post some screenshots.

**Comment by kaste** [comment]
I see you have it pushed, 

![image](https://user-images.githubusercontent.com/8558/196150407-a2248b7a-5ab9-4e0a-83ff-eeec649b6b55.png)

![image](https://user-images.githubusercontent.com/8558/196150500-08f73a27-435b-44e8-8869-bda4c96b8a6c.png)

It should more look like

![image](https://user-images.githubusercontent.com/8558/196150827-14c305b9-8244-4b37-b39a-657b03f4e477.png)
![image](https://user-images.githubusercontent.com/8558/196150851-4ef954a1-1649-45bf-8f4d-a1700373c9f2.png)

**Comment by gwenzek** [comment]
Yes it's a bit weird for the path highlighting.`region.yellowish` is only changing the background color, while you want to change the foreground color.  I was testing on a repo with a linear history, so I didn't notice at first. 

But you could allow user to specify other scope and defaults to eg `entity.name.function` or `entity.name.class` which are guaranteed to have colors matching the user theme.
