### ISSUE TITLE
rebase dashboard issue on git 2.34 rc1.

### ISSUE THREAD

**Issue by randy3k** [timbrel/GitSavvy#1505]
When using the rebase dashboard with "rebase_preserve_merges" setting on.

The panel shows
```
$ git rebase -p master

fatal: --preserve-merges was replaced by --rebase-merges

```

It seems that the setting name has changed from `--preserve-merges` to `--rebase-merges` in git 2.34.0.rc1, [link](https://git-scm.com/docs/git-rebase#Documentation/git-rebase.txt---rebase-mergesrebase-cousinsno-rebase-cousins).

It is a work computer and the git version is supplied by my company.
```
(=)-~$ git --version
git version 2.34.0.rc1
```

**Comment by kaste** [comment]
Hm, you're working for a company which tests git candidates.  🧐  That must be a big one.  

We just need to check when they introduced the new setting.  Hopefully long ago so we don't need to support both variants.

**Comment by randy3k** [comment]
The new setting was introduced in v2.19: https://git-scm.com/docs/git-rebase/2.19.0#Documentation/git-rebase.txt---rebase-mergesrebase-cousinsno-rebase-cousins which was released back in 2018/09.

Our min requirement is current 2.16. Shall we just bump the requirement and change the setting name?

**Comment by stoivo** [comment]
I am okey with requireing  a minimum of  2.19

**Comment by kaste** [comment]
I see it in 2.18 docs https://git-scm.com/docs/git-rebase/2.18.0#Documentation/git-rebase.txt---rebase-mergesrebase-cousinsno-rebase-cousins

**Comment by randy3k** [comment]
> I see it in 2.18 docs [git-scm.com/docs/git-rebase/2.18.0#Documentation/git-rebase.txt---rebase-mergesrebase-cousinsno-rebase-cousins](https://git-scm.com/docs/git-rebase/2.18.0#Documentation/git-rebase.txt---rebase-mergesrebase-cousinsno-rebase-cousins)

You are right. 

There are two things that the rebase dashboard offers, but the rebase feature of the graph dashboard does not.
1. undo/redo ability. It comes in handy if you have messed up the rebase conflicts.
2. the merges collapsing and preserving ability

By the way, your work in the graph dashboard is amazing.

**Comment by kaste** [comment]
I actually did not touch preserve-merges in the graph view because `rebase-merges` was already implemented and I only wanted to support the new one.  So that's finally out of the way; let's see how we can make use of it. 

The "undo/redo" stuff I don't understand in the rebase dashboard.  You can of course undo a rebase in the graph view.  You can't undo step-by-step; but I'm not sure if that's possible in the dashboard either.  What counts as an undoable step here?
