### ISSUE TITLE
Failed to connect to github.com port 443

### ISSUE THREAD

**Issue by mhenrixon** [timbrel/GitSavvy#1509]
```
$ git push origin chore/bump-dependencies:chore/bump-dependencies
fatal: unable to access 'https://github.com/username/repository.git/': Failed to connect to github.com port 443: Bad file descriptor
```

This started happening a few days ago and I can't figure out why it isn't able to push anymore. Commandline (terminal) works fine. Any suggestions are deeply appreciated.

**Comment by kaste** [comment]
Phew.  Usually that means you cannot connect to github.com; maybe firewalled for SublimeText or Little Snitch.  (Which OS is this on actually?)  Does the *exact* same command work on the Terminal?  Try closing Sublime completely, and start it from the Terminal using `subl .`  (from the folder you're working in); by doing so Sublime inherits the environment of that Terminal.  

GitSavvy itself only had one update (Nov 15).  Git itself also had an update recently.  Do you actually use the latest versions and auto-update?  Could it be that the credentials for GitSavvy stored in the GitSavvy settings diverged from what you use elsewhere?  

Shots in the dark, really.

**Comment by mhenrixon** [comment]
> Error executing: /usr/local/bin/git fetch origin
> 
> Working directory: /Users/mhenrixon/Library/Application Support/Sublime Text/Packages/yardgen
> 
> fatal: unable to access 'https://github.com/mhenrixon/Sublime-YardGen.git/': Failed to connect to github.com port 443: Bad file descriptor
> 
> VCS-based packages can be ignored by changing the "ignore_vcs_packages" setting to true.
> 
> Sublime Text will need to be restarted once the setting is changed.

Managed to get some type of error message from sublime after changing a few settings. I went over everything you said. Little Snitch was my first thought so I uninstalled it completely from my Mac and restarted but still get the same problem.

I didn't have a token before so I added one, still the same problem.

Tried starting from the commandline with `subl .` but still the same problem. Never seen this problem before, Git Savvy is one the only plugins I never had a problem with before so no idea where this is coming from.

**Comment by mhenrixon** [comment]
Honestly, I think something got borked with sublime text and I doubt this has anything to do with Git Savvy and more something to do with sublime text.

**Comment by kaste** [comment]
```
Error executing: /usr/local/bin/git fetch origin
...
```

is coming from Package Control trying to find out if there is a new version available for YardGen.  So it is not GitSavvy but Sublime as a whole is somewhat firewalled/boxed.  

I would ask on the Sublime forum https://forum.sublimetext.com/   You can of course also start to roll back updates you made/received in the last weeks.

**Comment by mhenrixon** [comment]
Such a weird situation, it was LittleSnitch after all. Not even uninstalling the damn thing with CleanMyMac removed the network proxy it installs for you in the Networking preferences pane. After deleting that, everything is fine.
