### ISSUE TITLE
Sponsor/donation

### ISSUE THREAD

**Issue by hanoii** [timbrel/GitSavvy#1539]
While this is something I probably should do more, I really (really) like what you built and went to see if I could either sponsor you through Github Sponsors or donate some but found nothing around that...

I had an ST hiatus trying out vscode but just came back on a new computer and you are the first extension I added (after packet manager obviously)

Do you have this noted anywhere, and if not, any particular meas of me doing it?

**Comment by kaste** [comment]
Haha, thanks.  You got me into freeze mode here 😆  Probably need to share my paypal.me.  Don't even know if is save to publish that address on the public.  Or maybe Github sponsors.
