### ISSUE TITLE
current light tag not show

### ISSUE THREAD

**Issue by mercurykd** [timbrel/GitSavvy#1540]
![image](https://user-images.githubusercontent.com/30900414/166647763-b607ca0a-a005-4215-a34d-a4f18ce7342a.png)

**Comment by kaste** [comment]
Cannot reproduce this: 

![image](https://user-images.githubusercontent.com/8558/166663260-5813523e-b3a0-4125-854a-edf2ac903260.png)

There is something going on here because if there are no tags it should show:

![image](https://user-images.githubusercontent.com/8558/166663612-627a5fc0-ca9b-4472-954e-ccab6a2abf72.png)

**Comment by kaste** [comment]
We actually call `$ git show-ref --tags` here which produces, e.g.,

```
a88e729dbdb4a87b8009994aed723362c46c3afc refs/tags/annotated                                                                                                                       
537af14e08c9afd23e01510cf1be83184e787374 refs/tags/testtest
```

**Comment by mercurykd** [comment]
case when there is only one tag and it occurs on the head

**Comment by mercurykd** [comment]
```json
{
    "stdin": null, 
    "command": [
      "show-ref", 
      "--tags", 
      null
    ], 
    "stdout": [
      "b5dab93f4316bb589718cbd31d73f569374a4d46 refs/tags/v1.0.0\n"
    ], 
    "stderr": [
      ""
    ], 
    "seconds": 0.111846923828125, 
    "type": "git"
  }
```

**Comment by kaste** [comment]
If I use the data you're posted as a mock response I get:

![image](https://user-images.githubusercontent.com/8558/166802495-1f527736-b43d-45bf-9dd1-3148bf2c89bb.png)

I actually need a `stdout` with just spaces to produce your pic. (e.g. ` stdout = "   \n"`)  

> case when there is only one tag and it occurs on the head

What do you mean here, in my first comment (https://github.com/timbrel/GitSavvy/issues/1540#issuecomment-1117148819) I tagged the head commit and there is only one tag.

**Comment by mercurykd** [comment]
> I actually need a stdout with just spaces to produce your pic

my enviroiment win11 x64, ST4126

**Comment by kaste** [comment]
I have a slightly newer ST and git version (also on win11) so updating could be an option for you.

**Comment by mercurykd** [comment]
git version 2.36.0.windows.1
not helping

**Comment by kaste** [comment]
You could try to clone GitSavvy into your Sublime packages folder and patch it.  For example add

```
    print(repr(stdout))
    print(entries)
```

at https://github.com/timbrel/GitSavvy/blob/6452528d22a13c6f3169ad20619471d261e576bf/core/git_mixins/tags.py#L34

Or `print(self.local_tags)` at https://github.com/timbrel/GitSavvy/blob/6452528d22a13c6f3169ad20619471d261e576bf/core/interfaces/tags.py#L117

Restart Sublime to reload GitSavvy; or set `dev_mode: true` in the GitSavvy settings and choose `GitSavvy: reload` from the Command Palette.

**Comment by mercurykd** [comment]
![image](https://user-images.githubusercontent.com/30900414/166823092-189587bc-16fb-4ca2-b9bd-e9ab5895a35d.png)

**Comment by kaste** [comment]
Funky.  What the hell is going on here?

At https://github.com/timbrel/GitSavvy/blob/6452528d22a13c6f3169ad20619471d261e576bf/core/interfaces/tags.py#L118-L121

```
        rv = "\n".join(
            "    {} {}".format(self.get_short_hash(tag.sha), tag.tag)
            for tag in self.local_tags[0:self.max_items]
        )
        print(repr(rv))
        print(repr(self.max_items))
        return rv
```

And maybe after that just `return "Hello, my darkness my old friend"`  to see if it even renders a static string.

**Comment by mercurykd** [comment]
> rv = "\n".join(
            "    {} {}".format(self.get_short_hash(tag.sha), tag.tag)
            for tag in self.local_tags[0:self.max_items]
        )

![image](https://user-images.githubusercontent.com/30900414/166826625-4858c35a-b26a-4d54-8422-f80e359a764b.png)

> return "Hello, my darkness my old friend"

![image](https://user-images.githubusercontent.com/30900414/166826930-3d6fc32a-8436-4153-a467-0d0439688764.png)

**Comment by mercurykd** [comment]
```python
return "\n".join(
            "    {} {}".format(self.get_short_hash(tag.sha), tag.tag)
            for tag in self.local_tags
        )
```
works

**Comment by kaste** [comment]
Okay, `self.max_items = -1` shouldn't be so.  This is controlled by the setting `max_items_in_tags_dashboard` which is by default `-1`.  This is introduced via https://github.com/timbrel/GitSavvy/pull/803  with the intention of selecting *all* tags.  But

```
In [41]: [1,2,3][0:-1]
Out[41]: [1, 2]
In [42]: [1][0:-1]
Out[42]: []
```

it selects all *but* or up to the last one.  

Really thanks for finding this.  The correct default could be `None` to show *all* tags or a sane natural number to not overflow the view.  (I had this set to 15 for ages, even before I started maintaining this package. 🤷 )

**Comment by mercurykd** [comment]
> Really thanks for finding this

thank you for supporting the extension. I have not seen the best implementation of working with git in any ide

**Comment by kaste** [comment]
Just released a fix.  Should be available within an hour.
