### ISSUE TITLE
GRAPH view: "show commit" options disappeard from the menu

### ISSUE THREAD

**Issue by paveljanda** [timbrel/GitSavvy#1548]
Hi,

O have a question - may I did make something wrong or may it be a bug: When I am in the GRAPH view, previously, I could list through the commits and click enter on some of them and select the "View commit" option to see the commit changes. Now that options is not there. Am I missing something?

Thanks

**Comment by kaste** [comment]
That specific menu item is gone since ages.  Moved/promoted to just `[o]` because it is used too often.  `[?]` shows this tooltip.

![image](https://user-images.githubusercontent.com/8558/179978186-b41d08c3-6f0a-4192-9500-e78cb75729ca.png)
