### ISSUE TITLE
Compatibility issue

### ISSUE THREAD

**Issue by deathaxe** [timbrel/GitSavvy#1576]
The following line causes an exception, once Package Control is migrated to python 3.8 plugin_host.

https://github.com/timbrel/GitSavvy/blob/ea66a1b7be2d22c5de21ead7dfeaf17f9125150f/git_savvy.py#L17

```
plugins loaded
Traceback (most recent call last):
  File "C:\Apps\Sublime Text\Lib\python33\sublime_plugin.py", line 528, in on_api_ready
    plc()
  File "C:\Apps\Sublime Text\Data\Installed Packages\GitSavvy.sublime-package\git_savvy.py", line 22, in plugin_loaded
    package_control.events.install('GitSavvy') or
AttributeError: 'module' object has no attribute 'events'
```

Please follow the docs https://packagecontrol.io/docs/events and import `events` directly.

```
from package_control import events
```

**Comment by kaste** [comment]
Why can't this be solved upstream?  I also do this in SublimeLinter and elsewhere.  

What is even the difference between `import x` and `from x import y`?  How can one thing work and the other way not?

**Comment by deathaxe** [comment]
The way how `package_control` is made available for both plugin_hosts seems not to include all its modules. Have no idea how to solve it upstream.

As `events` is the only module meant for external use, I'd assume it suitable to expect documented usage only.

I guess `import package_control.events` would work, also.

---

Note: The reloader code, which abuses `PackageManager()` will also fail but that's a seperate topic, which I don't care about, because this is not a documented way of using package_control anyway.

**Comment by kaste** [comment]
The reloader code probably comes from `AutomaticPackageReloader`.  (IIRC GitSavvy had the first automatic reloader code, and since then there is some copy paste back and forth between them.)

**Comment by deathaxe** [comment]
Yep. 

I've switched to just remove modules from cache before any new import in most plugins long ago, which seems pretty much enough to handle proper reloading of nested packages modules. 

see: https://github.com/SublimeText/PackageDev/blob/master/main.py
