### ISSUE TITLE
broken sorting of remote branches

### ISSUE THREAD

**Issue by mercurykd** [timbrel/GitSavvy#1643]
` "sort_by_recent_in_branch_dashboard": true,`
Sorting stopped working for remote branches. Is it possible to make this parameter enabled by default (sorting by commits is much more convenient)?

**Comment by kaste** [comment]
Sorting the *local* branches confuses me often, unless the integration branches (master/main/dev/release) would be highlighted.   I can see this more useful for the remote branches as then the new ones pop up easily.  

Also sorting should be bound to a key, and sorting by date then we should also show the date.  🤔 

Maybe we should hide remote branches not already tracked locally.  That seems superfluous information.  (Like in the tags dashboard, I only show remote tags *not* also locally available.  Usually the *new* tags.)

I wonder if a topological branches view like this one:

![image](https://user-images.githubusercontent.com/8558/196139265-7201f870-025b-4c62-9323-6ba03d343ccf.png)

would be more useful.
