### ISSUE TITLE
Allow creating signed tags

### ISSUE THREAD

**Issue by iamkroot** [timbrel/GitSavvy#1675]
It would be really great if we have an option to add `-s` to the git command invocation for creating tags. This lets us create [signed tags](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-tags).

A simple opt-in preference "sign_tags: bool" should be enough to configure this.

**Comment by kaste** [comment]
You can configure git to sign tags already.  https://github.com/git/git/blob/v2.38.1/Documentation/config/tag.txt
or https://git-scm.com/docs/git-tag#Documentation/git-tag.txt--s

I think that's more appropriate because you can set this per repo or per user/per system.  WDYT?

**Comment by iamkroot** [comment]
Ah, that sounds good! I should have checked git docs first. Have been manually adding `-s` for so long :P
Thanks for the links :)
