### ISSUE TITLE
Bug: after upgrading to latest version, git checkout -b no longer works

### ISSUE THREAD

**Issue by paveljanda** [timbrel/GitSavvy#1711]
When trying to run "git: checkout remote branch as local", the commands fails with following error in Sublime Console:

```
Traceback (most recent call last):
  File "/Users/paveljanda/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package/core/base_commands.py", line 81, in run_
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1456, in run_
    return self.run(**args)
TypeError: run() missing 1 required positional argument: 'local_name'
```

Is there any workaround for that? WIth that bug, my git workflow is unusable for now.

Thanks for any info!

**Comment by kaste** [comment]
Shit,  argument name was wrong.

**Comment by paveljanda** [comment]
Hi, did you release it yet, pls?

In version 2.38.2, the mentioned error still occurs.

Thanks

**Comment by kaste** [comment]
Works for me.  Did you restart Sublime Text?

**Comment by paveljanda** [comment]
I did, several times. It started to work finally in the evening 🤷 

Thanks for such a quick response!
