### ISSUE TITLE
Add keybind to tag a commit from the log view

### ISSUE THREAD

**Issue by p3lim** [timbrel/GitSavvy#1871]
If I wanted to tag a specific commit (e.g. before HEAD) I have to leave the context of ST/GitSavvy and do it in a terminal.

It would be nice if the log/graph view had a keybind of `t` (or something) to prompt for a tag name and message (like the "git: quick tag" menu option, could even re-use it for this) for the commit under the cursor.

**Comment by p3lim** [comment]
Same goes for removing an existing tag from a commit.

**Comment by kaste** [comment]
This is in the graph:

![image](https://github.com/timbrel/GitSavvy/assets/8558/b57d951a-1f51-4af8-87ab-d59ee594ef71)

and it indeed calls the "quick tag" command with the commit under the cursor.  Quick Tag is a strange name, don't know why it isn't explicit here "git: create tag at HEAD".

**Comment by p3lim** [comment]
Ah I wasn't aware of that contextual menu, thanks.

Looking at `gs_tag_create` it doesn't seem like I could add a binding for this myself, but the menu will suffice. I would however request that the menu entries are a little more verbose, like you mentioned:

- it should be "Create tag at <ref>" and not just "Create tag"
- it should be "Delete tag <tag>" and not just "Delete <tag>"
