### ISSUE TITLE
Feature: Show Commit under cursor

### ISSUE THREAD

**Issue by franciscolourenco** [timbrel/GitSavvy#1872]
In the status view, it would be useful to have a command to show the commit under the cursor, in the same way that it is possible to show the stash under the cursor. The S key seems appropriate if possible.

~Optionally, the same could be useful in the Graph view.~ Edit: Already working.

**Comment by kaste** [comment]
You mean the short log/graph in the status header.  (Do you have a pic otherwise?)  In the graph it's `o` (for _o_pen).

**Comment by franciscolourenco** [comment]
That's what I meant. Good to know about the graph view 👍
