### ISSUE TITLE
GitSavvy performance seems to have regressed on a large repo

### ISSUE THREAD

**Issue by nikhilm** [timbrel/GitSavvy#1939]
OS: Linux
Sublime Text version 4, build 4180
GitSavvy 2.45.0 from PackageControl

I have a large internal repo that generally slows down lots of Git tooling.
However, since upgrading to ST 4180 from 4166, I feel like GitSavvy has gotten much slower on operations that were previous not as slow.
Is there any profiling tooling I can easily run, that will not leak the confidential paths and so on from the repo, that will help y'all debug?

Situations which seem slower:
pull-with-rebase - listing branches
status tab - In particular, when I hit `l` or `e`, the diff tab would open pretty much instantaneously. Now it takes several seconds.
status tab - when I `s` a file to move from unstaged to staged, the file will be staged in git, but often the status tab won't update and will still show the file as unstaged.

**Comment by kaste** [comment]
Hm, I don't habe 4180 installed yet.  You can try *GitSavvy: enable logging* from the Command Palette, and then see the logging in Sublime's standard console.  This only logs the git commands, let's just see if they are fast enough.

**Comment by nikhilm** [comment]
This is when I hit inline diff (`l`) on a file:

```
(D) [31286ms] $ git for-each-ref --format='%(HEAD)%00%(refname)%00%(upstream)%00%(upstream:remotename)%00%(upstream:track,nobracket)%00%(committerdate:unix)%00%(committerdate:human)%00%(committerdate:relative)%00%(objectname)%00%(contents:subject)%00%(ahead-behind:HEAD)' refs/heads refs/remotes
 (D) [ 15ms] $ git stash list
 (D) [ 56ms] $ git ls-files -v
 (M) [ 39ms] $ git diff --no-color -U0 -- <file path>
 (M) [119ms] $ git show :<file path>
 (D) [130ms] $ git log -n 100 --format=%h%00%d%00%s
```

Seems like for-each-ref is the problem. It is possible this isn't a ST/GitSavvy regression then. Perhaps something about my branches has changed to cause this to slow down.

**Comment by nikhilm** [comment]
Oh! I think the issue isn't from inline diff. I think the status window is running this in the background, and that causes other operations to get queued up.

**Comment by kaste** [comment]
Yeah, 30s for a `git for-each-ref` is likely only waiting time for something else.
So how long take the status calls?  And do they take more time than on the terminal? 

Maybe the file watcher isn't running, or the commit graph is not up-to-date. 

(130ms for a *git log -n 100* seems also too slow.  Maybe the commit graph?)

**Comment by nikhilm** [comment]
I don't understand git enough to explain why, but here is what fixed this.

So, my feature branch had original branched from master.
Then, for a long time, I was doing `git pull --rebase origin master` to rebase my feature branch on origin/master. However I was never updating local master to origin/master.

Today I did that and suddenly everything is fast again.

I can close this out, but would love to know how that could be related.

**Comment by nikhilm** [comment]
Sigh! Actually, never mind my previous comment. I'm back to >30s.

**Comment by nikhilm** [comment]
Commit graph seems to be up to date based on mtime. I don't think I have a file watcher. I am on Linux, where I don't think a default one exists.

**Comment by kaste** [comment]
So it *is* the `git for-each-ref --format='%(HEAD)%00%(refname)%00%(upstream)%00%(upstream:remotename)%00%(upstream:track,nobracket)%00%(committerdate:unix)%00%(committerdate:human)%00%(committerdate:relative)%00%(objectname)%00%(contents:subject)%00%(ahead-behind:HEAD)' refs/heads refs/remotes` that is actually slow?   Then is it also slow on the Terminal I guess.  Is it?

In that call there is a `%(ahead-behind:HEAD)` which computes the ahead/behind numbers for each ref (branch).  That uses the commit graph and could be slow.  I actually have code that probes the speed for this call but that code has a bug it seems.  If you restart Sublime and watch the console, the first time GitSavvy does the call it should also should print something like

```
                            f"`git for-each-ref` took more than 200ms which is slow "
                            "for our purpose. We now run `git commit-graph write` to see if "
                            "it gets better."
```

But then it seems the follow up logic doesn't work.

**Comment by kaste** [comment]
Let's see if this is fixed by 2.45.1

**Comment by kaste** [comment]
> Is there some functionality I can disable (did GitSavvy already do that by disabling sections?)

Yes, the intention is to detect slow repos and then to disable the GitSavvy feature automatically.  GitSavvy should then not ask for the behind-ahead numbers.

**Comment by nikhilm** [comment]
Ok, based on your tip about ahead-behind, i think i realize the core issue now.
In GitSavvy, ahead-behind is [gated](https://github.com/timbrel/GitSavvy/blob/0357ccce74e272482a69b7847d2a1a511475d921/core/git_mixins/branches.py#L13) behind the git version being at least 2.41.0.

Just 3 weeks ago, our internal toolchain was updated from 2.40.0 to 2.45.2. That would explain why GS started trying to use that feature and slowed down :)

I appreciate you being super responsive! Thank you.

**Comment by kaste** [comment]
Thanks for reporting the bug, actually.   👍 

Do you have that many refs/branches or that many commits btw?

**Comment by nikhilm** [comment]
Approximately 24500 branches at this point. We use a lot of branches and it's a 10 year old monorepo.
