### ISSUE TITLE
Bug: can't interact with branches whose commits are made in another timezone in the BRANCHES tab

### ISSUE THREAD

**Issue by kylebebak** [timbrel/GitSavvy#1941]
In the BRANCHES tab, branches whose commits are made in another timezone are rendered e.g. like this: `e94895c7 ERS-7050 Wed 14:28 -0700, (origin/ERS-7050)`

Something about the `-0700` text causes problems for the plugin. Syntax highlighting doesn't work correctly:

<img width="555" alt="Screenshot 2024-08-15 at 11 09 36 AM" src="https://github.com/user-attachments/assets/f0f7964c-2627-4b3a-96c1-72a9d74ac7c9">

And trying to interact with the branch, e.g. pressing `c` to check out the branch, leads to a `No branch selected` message in the status bar

<img width="543" alt="Screenshot 2024-08-15 at 11 10 12 AM" src="https://github.com/user-attachments/assets/b8d20762-ae59-4003-8e5e-efcf0b74e98d">

Mayeb the problem is somewhere in the `branch.py` module, [maybe in the `render_branch_list` function](https://github.com/timbrel/GitSavvy/blob/ccc8ba66855eea68e67bc57b73f9006a01abe864/core/interfaces/branch.py#L200-L243)?

**Comment by kaste** [comment]
Typically when the syntax breaks GitSavvy can't grab the right portions of text/of the view to operate.  For example, the unstyled line withe the `-700` does not detect the commit hash nor the branch name.  The fix is likely in the syntax.

**Comment by kylebebak** [comment]
Sounds like one fix could be to remove the timezone info from the human date format. Either that or update the syntax. FWIW I don't rely on the timezone info

**Comment by kaste** [comment]
Syntax fix is easier, removing the timezone looks nicer probably.  I don't think that info is needed here.

**Comment by kaste** [comment]
Hm, stripping the timezone is just `re.sub(r"\s[+-]\d{4}$", "", "Wed 20:04 -0700")`.

**Comment by kylebebak** [comment]
Thank you for the quick fix @kaste  =)
