### ISSUE TITLE
Staging individual lines in diff view can add them in the wrong place

### ISSUE THREAD

**Issue by ptomato** [timbrel/GitSavvy#226]
I observed the following with staging individual lines with the `l` key in the diff view in GitSavvy 2.3.0.

Suppose I have this code

```
a
b
c
d
e
```

and I change it to

```
A
B
C
D
E
```

I only want to stage lines `A` and `E` for one commit. So in the diff view I see this (annotating the colors myself):

```
a (red)
b (red)
c (red)
d (red)
e (red)
A (green)
B (green)
C (green)
D (green)
E (green)
```

I position the cursor on each of lines `a`, `A`, `e`, `E`, and press the `l` key. Then the diff view shows this:

```
b (red)
A
c (red)
B (green)
C (green)
D (green)
E
d (red)
```

And sure enough, running `git diff --staged` shows this:

``` diff
-a
 b
+A
 c
+E
 d
-e
```

**Comment by ptomato** [comment]
Also, if I hit the `l` key on lines `A` and `a`, in the reverse order from above, then that change is staged correctly. However, if I continue with `E` and `e`, then I get this from `git diff --staged`:
```diff
-a
+A
 b
+E
 c
 d
-e
```

**Comment by stoivo** [comment]
It is confirm that I have the same behavior on my sublime. I have worked with inline diff before. It is quite difficult to understand or/and change. I will probably try to fix this but not right now. I will write a note here when I start.

If some one would like to try to fix it. it is on there lines something have to be done 
https://github.com/divmain/GitSavvy/blob/1bf4e6515df22dfdda70e815dbd32a22abcb6f35/core/commands/inline_diff.py#L448-L533

**Comment by kaste** [comment]
Closing, this has been resolved anyway.
