### ISSUE TITLE
Strange horizontal scroll when staging hunks

### ISSUE THREAD

**Issue by franciscolourenco** [timbrel/GitSavvy#290]
There is a strange automatic horizontal scrolling happening when staging hunks on some files.
When a hunk is staged, the file scroll jumps to the right.

Here is an example:
[![screeencast](http://i.imgur.com/m1pCqua.gif)](http://i.imgur.com/m1pCqua.gifv)

**Comment by alextegelid** [comment]
Now that you mention it, I've noticed this aswell.

**Comment by divmain** [comment]
You know, I've noticed that myself.  As far as I can tell, it is a Sublime Text bug.  However, I have a possible work-around in mind, so let me give that a shot.

**Comment by divmain** [comment]
Alright, let's see if this change consistently makes a difference.  As is mentioned in the commit, the addition here shouldn't strictly be necessary, but it should provide a relatively seamless workaround.  Please re-open if you notice the issue again.

**Comment by aristidesfl** [comment]
still experiencing this issue. how do I check which version is installed?

**Comment by divmain** [comment]
@aristidesfl, this hasn't been released yet through Package Manager.  You'll only see if it if you've pulled down the repo manually and pulled since the fix was added.  I generally like to keep changes like this in master for a little while before releasing into Package Manager, in case they introduce any new problems.  But for what it's worth, I haven't noticed this issue since the change was made.

**Comment by aristidesfl** [comment]
So I just cloned to test https://github.com/divmain/GitSavvy/issues/314 and this issue just is still happening.

**Comment by divmain** [comment]
Hmm alright.  I'm not sure what else to try.  As far as I can tell this is a bug with Sublime, and I'm not sure what else to use as a workaround.

I will reopen with the `investigate` tag, but it may be that we just have to live with this.

**Comment by kaste** [comment]
Closing as we usually have full control over the scroll position and the viewport now.
