### ISSUE TITLE
Can't inline diff a file with merge conflict

### ISSUE THREAD

**Issue by stevage** [timbrel/GitSavvy#338]
GitSavvy currently doesn't let you do an inline diff on a file that "has a merge conflict". I'm not sure what the technical reason is, but I ran into a situation in which it would have been useful.

Basically, I added a feature inside a single file, then (before committing) foolishly merged in master, and resolved the merge conflict (that is, edited the file, but didn't do any git actions). This left my index in a state with lots of irrelevant changes to be committed, and my one file with feature changes listed under "MERGE CONFLICTS".

What I wanted to do: make a commit containing the merge (and the non-feature parts of this file), and then subsequently a separate commit with the new feature. I would use the inline diff to do this, but GitSavvy prevented this.

My suspicion is that GitSavvy doesn't allow this because it can't handle remaining merge-conflict markers (`<===` etc). If that's true, perhaps it could check whether the file actually contained any of those, and if not, could carry on as normal?

**Comment by kaste** [comment]
We can't draw or don't know how to parse the merge conflicting diff.  Normal diffs have their before/after part (`a->b`) but files with merge conflicts have `a', a'', b`.  There is no good colorization for that.  You cannot stage hunks or lines for conflicted files anyway, only stage the whole file.  Choosing ours vs theirs is basically editing the file not staging.  

I need to try if we can show the inline diff at least if all conflicts have been resolved.  Then the diff is clean and there is probably no need to throw an error at the user.
