### ISSUE TITLE
Move cursor down after staging merge-conflicted file

### ISSUE THREAD

**Issue by stevage** [timbrel/GitSavvy#377]
Minor UI issue. When you have:

MERGE CONFLICTS:
  foo.js
  bar.js

After staging foo.js, the cursor moves up to MOVE CONFLICTS, instead of staying on the same line and now pointing at bar.js.

**Comment by randy3k** [comment]
There is a similar bug when unstaging files: the cursor moves to the `UNSTAGED` when unstaging staged file.

**Comment by kaste** [comment]
This has been resolved or at least tackled long ago.
