### ISSUE TITLE
Key binding context setting for GitSavvy dashboard

### ISSUE THREAD

**Issue by FichteFoll** [timbrel/GitSavvy#422]
I have a custom key binding for `shift+tab` that allows me to unindent mid-line in my User bindings. Due to how key bindings work, this binding is getting picked up when pressing shift+tab in gitsavvy views as well, so I wanted to add a context condition that would only hold true if I was not in a gitsavvy view (that supports dashboard cycling).

Unfortunately, I found out that all these bindings are implemented for each dashboard view individually with a context of `{ "key": "setting.git_savvy.tags_view", "operator": "equal", "operand": true }`.

I would like to request adding a setting that allows checking for whether cycling should be supported or not (or just in general whether a gitsavvy input-controlled view is active) so that I can disable my key binding for these views. Additionally, GitSavvy could potentially make use of this binding as well by only having to define the tab and shift+tab bindings once for all views where this should be supported.

**Comment by kaste** [comment]
Hi @FichteFoll, 

this is and probably was always possible using `scope`.  E.g. you could use  

```
"context": [{ "key": "selector", "operand": "git-savvy" }]
```
which is true for *all* special GitSavvy views.  And e.g. `git-savvy.status` for just the status dashboard.  

At the time you asked this, there was also `setting.git_savvy.tabbable` `True` for exactly what you had in mind.  But we don't and never used it in our own code.
