### ISSUE TITLE
Suggestion: document settings as in GitSavvy.sublime-settings

### ISSUE THREAD

**Issue by asfaltboy** [timbrel/GitSavvy#430]
While I hate duplicating, it would be pretty useful to have a "human readable" documentation for settings to, among other things, be able to link to settings from other documentation pages.

As an example, we could add a mention of being "Vintageous friendly" in [Highlighted Features](https://github.com/divmain/GitSavvy/blob/master/docs/README.md#highlighted-features), then we would probably best to add a short description of the feature, and it would be a shame to not being able to to link to the available settings.

**Comment by stoivo** [comment]
Yes, go ahead and make a pull request.

I would like if @mreq or @asfaltboy write some words about this since I don't use Vintageous.

**Comment by asfaltboy** [comment]
I can barely find time right now, will add to my OSS todo list.

**Comment by stoivo** [comment]
Thanks @asfaltboy.

**Comment by divmain** [comment]
I'm open to documenting some of this, but I think documenting all of it is a mistake.  The reason is very straightforward - documentation can so easily get out of date.  However, it would be worth calling out functionality that's only mentioned in the `sublime-settings` file, and making it clear what types of configuration are supported.

**Comment by asfaltboy** [comment]
Ok. My point is that the settings are an inseparable part of the feature it relates to. These should definitely be documented (or at least mentioned) in the related feature documentation.

I strongly feel it would be extremely useful for users if GitSavvy had a centralized documentation of all available settings; these can later be referred to from the specific feature docs.

Once we get used to the requirement that settings must be documented, it should not get out of date.

A good example of such a documentation is [Django's settings reference][1], I feel it works well.

[1]: https://docs.djangoproject.com/en/1.9/ref/settings/

**Comment by divmain** [comment]
Fair enough.  It's worth trying, and if we do find that things get out of date we can make a different decision at that point.

**Comment by stoivo** [comment]
Maybe we can make a commit hook that will create some markdown(docs/settings.md) from GitSavvy.sublime-settings

**Comment by asfaltboy** [comment]
Great idea! We can either add the hook to "Contribute.md" to be copy-pasted, but we'll depend on users. Alternatively we can run some magic cmd in travis-ci, e.g `git diff origin/master $TRAVIS_COMMIT ` and compare the `sublime-settings` file with docs/settings.md.

**Comment by stoivo** [comment]
I like it <3

**Comment by divmain** [comment]
> Alternatively we can run some magic cmd in travis-ci, e.g git diff origin/master $TRAVIS_COMMIT and compare any changes to sublime-settings with docs/settings.md, failing the build if documentation is missing.

This.  I've used this pattern to good effect in other projects, and am absolutely in favor.  This would also obviate my concerns about documentation staleness :+1:

**Comment by kaste** [comment]
All settings have comments.
