### ISSUE TITLE
`git graph` very slow on huge codebase

### ISSUE THREAD

**Issue by blaggacao** [timbrel/GitSavvy#494]
I experience very slow git graph on very huge codebase.
It seems that there is missing a sensible limit on some point in order to make it more responsive.

I would argument, that you would mostly be interested in the recent history, rather than what banching has happened some 10 years ago.

EDIT: Last line of graph is:

`171535`

**Comment by stoivo** [comment]
Hehe, thanks for reporting. I did not think of this as an issue but this is a problem when you have  150k  commits and even worse with a slow HDD. I am think that this can be configured and set a limit to 20k commit as default.

I opened 70k commits in 4 sec. 

Copy from git log doc
```
   Commit Limiting
       Besides specifying a range of commits that should be listed using the special notations explained in the description, additional commit limiting may be applied.

       Using more options generally further limits the output (e.g. --since=<date1> limits to commits newer than <date1>, and using it with --grep=<pattern> further limits to commits whose log message has a line that matches <pattern>), unless otherwise noted.

       Note that these are applied before commit ordering and formatting options, such as --reverse.

       -<number>, -n <number>, --max-count=<number>
           Limit the number of commits to output.

       --skip=<number>
           Skip number commits before starting to show the commit output.
```

**Comment by blaggacao** [comment]
I guess you are referring to this config section:

```

    /*
        Update the desired graph arguments for a customized experience.
        Do not add "--all" in this setting, it is added in graph all branches

        NOTE: Changes you make may break in-view functionality, so use with caution.
     */
    // "git_graph_args": ["log", "--pretty=format:%h%d (%ar) by `%an` %s", "--graph"],
    "git_graph_args": ["log", "--oneline", "--graph", "--decorate"],
```

**Comment by stoivo** [comment]
Actually I was think to add a new setting for git log commit limit. Also append a line last to load see the next 10 or 20k commits

page 1 `git log --max-count=10000 --skip=0`
```
●   6e96e92 (HEAD -> master, origin/master, origin/HEAD) (25 hours ago) by `Simon` a
|\  
| ● 3ec06b8 (13 days ago) by `Simon` b
|/  
●   bf5306a (25 hours ago) by `Simon` c
go to page 2
```

page 2 `git log --max-count=10000 --skip=10000`
```
go to page 1
●   6e96e92 (25 days ago) by `Simon` a
|\  
| ● 3ec06b8 (26 days ago) by `Simon` b
|/  
●   bf5306a (27 days ago) by `Simon` c
go to page 3
```

**Comment by blaggacao** [comment]
Even better! :smile: So my comment would be a workaround for now.

**Comment by stoivo** [comment]
Yes, you can use that as a work around.
