### ISSUE TITLE
Erratic key handling behavior with large checkouts

### ISSUE THREAD

**Issue by rchl** [timbrel/GitSavvy#502]
With the big checkout I'm working on [1], it takes about 1 or 2 seconds to update the git status view (other too I guess). That means that if I for example press `e` to open a diff for modified file and then close the view and immediately try to stage it with `s`, the key press will not get registered due to the view updating itself.

The possible solution for this include:
- making it clear visually that view is updating and that key bindings are inactive. For example gray out the whole view and text (apply comment scope)
- handle that case by queuing key presses so that it is executed after view was refreshed.

Second option would be preferable as that would make everything feel much more responsive, but is probably much more tricky to implement. Especially the case after the key was pressed and refresh modified the view after.

[1] https://www.chromium.org/developers/how-tos/get-the-code

**Comment by divmain** [comment]
Sorry this has been sitting idle for so long.  The second solution is problematic, in that the solution would have to 1) be generic enough to handle any long-running Git command, and 2) work for any dashboard view.  Now if, for example, a checkout occurred and keypresses were queued, the dashboard may update in an unexpected way and the queued actions would not provide the expected result.

I think the first option is the best, and something we could probably manage with how things are architected.  We can also make the behavior optional for folks that may find the visual feedback noisy.

**Comment by kaste** [comment]
This has been fixed long time ago.  IIRC we wait for git to finish and queue up the key presses in between.
