### ISSUE TITLE
Feature request: allow overriding GitSavvy settings in project settings

### ISSUE THREAD

**Issue by asfaltboy** [timbrel/GitSavvy#531]
These "per-project" settings should take precedence over user/default GitSavvy settings when parsed. Of course, not all settings apply here, we have to refine a  list.

We already do this in some  places, just need to gather all these settings (defaulting to user/defaults) into a single entry point.

I good example of a fallback strategy can be seen in [SublimeLinter settings "stack"](http://www.sublimelinter.com/en/latest/settings.html).

**Comment by randy3k** [comment]
For git repo, we have one more option to save the settings - `git config`, I think we should also put it into consideration.

**Comment by divmain** [comment]
@stoivo, any thoughts on this?  I'd like to standardize on one mechanism for persisting project-specific settings.  My preference would be to go with project settings, since the options we're saving aren't pertinent outside of GitSavvy itself.

**Comment by stoivo** [comment]
I think we should use project setting which will override the user package setting which again override the Package default settings. I would make it so all settings would we overwritten.

In this case I we should create a wrapper around reading settings or create a separate repo and make it a sublime depenence like [pyyaml](https://github.com/divmain/GitSavvy/blob/master/dependencies.json)

**Comment by kaste** [comment]
This has been implemented (in some way).
