### ISSUE TITLE
Odd behavior on bare repo / first commit

### ISSUE THREAD

**Issue by asfaltboy** [timbrel/GitSavvy#557]
Here are some things I noticed that are broken when acting on a "bare repo" (or a repo with 1 commit):

- [x] BARE: Stage dir + unstage (reset) a specified file

    ### Exception

      `/usr/bin/git reset HEAD testproj/__init__.py` failed with following output:
      fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.

    ### Solution

      $ git rm --cached testproj/__init__.py

- [x] BARE: Amend 1st commit (oops forgot .gitignore):

    ### Exception

      /usr/bin/git diff --no-color --cached HEAD^` failed with following output:
      fatal: ambiguous argument 'HEAD^': unknown revision or path not in the working tree.

    ### Solution

      $ git commit --amend  # works well on command line

- [ ] BARE: Log/RefLog/Graph/Reset commands all fail since head does not exist.

    ### Exception

      # any git command would fail with this message
      fatal: your current branch 'master' does not have any commits yet

    ### Solution

    Nothing much can be done here, but perhaps we can show a nicer message if we expect this to happen.

- [ ] 1 COMMIT: Reset (log/reflog) from 1st to "zero-commit" only 1 record displayed, can't go back to nothing. This is probably ok, and iI couldn't find a workaround other than deleting ".git" dir.

_NOTE:_ This has most likely been like this for a while but we never bothered to clean it up.

_NOTE 2:_ I'm probably going to want to convert this into a PR with failing tests, once I figure how to write and run them 😊

**Comment by kaste** [comment]
The first two issues herein have been fixed.  The others are not fixable.

**Comment by kaste** [comment]
Note: Unstaging a file has been fixed with bcacd55e (Make staging/unstaging multiple files one operation) (in v2.20.0, Dec 2019)

Amending the first commit has been fixed in #1419 (v2.27.5)
