### ISSUE TITLE
Stash changes while using rebase dashboard.

### ISSUE THREAD

**Issue by randy3k** [timbrel/GitSavvy#644]
Currently, manipulating commits are not allowed if the repo status is unclean. It could be solved by modifying [this](https://github.com/divmain/GitSavvy/blob/2938321db00b5d15ab9281b4a99e528d78e90eb7/core/interfaces/rebase.py#L477) as

```python
        if len(changed_files):
            def stage_changes_and_run_async():
                self.git("stash")
                try:
                    self.run_async()
                finally:
                    self.git("stash", "pop")

            sublime.set_timeout_async(stage_changes_and_run_async, 0)
        else:
            sublime.set_timeout_async(self.run_async, 0)
```

But it seems that it is quite dangerous to do so...any comments?

**Comment by stoivo** [comment]
Maybe ask or have it as a setting. It would be really stage if you have some changes and suddenly those changes is in a stash after you renamed a old commit(and it failed)

```python
        if len(changed_files):
            def stage_changes_and_run_async():
                if not sublime.ok_cancel_dialog(
                        "Unable to manipulate commits while repo is in unclean state.",
                        "Would you like to stash while doing this operation?")
                    return

                self.git("stash")
                try:
                    self.run_async()
                finally:
                    self.git("stash", "pop")


            sublime.set_timeout_async(stage_changes_and_run_async, 0)
        else:
            sublime.set_timeout_async(self.run_async, 0)
```

It is frustrating when it complains that I have some changed files. I like the idea :D

**Comment by randy3k** [comment]
I beleive that the try finally block will reapply the changes even the modification fails.

**Comment by stoivo** [comment]
But the pop might fail.

**Comment by randy3k** [comment]
I cannot think of any situations in which `run_async` could be executed without errors but `git stash pop` fails...Though it is exactly why I said this is a kind of dangerous.

**Comment by stoivo** [comment]
Deleting a commit would make git stash pop fail. I think ?

**Comment by randy3k** [comment]
Ai, you are very correct!

**Comment by stoivo** [comment]
So, would you like to add it? 
or add a shortcut to create a stash from the rebase dashboard. 
or every time it fails because of an unclean state, ask it the user would like to stash and redo the action?

**Comment by randy3k** [comment]
> every time it fails because of an unclean state, ask it the user would like to stash and redo the action?

👍 we should also undo absolutely everything if `stash pop` fails.

**Comment by arturolinares** [comment]
I think lazygit uses --autostash to [achieve this](https://github.com/jesseduffield/lazygit/blob/master/pkg/commands/git_commands/rebase.go#L213). Could be possible to add it as a setting?

**Comment by kaste** [comment]
Hi @arturolinares, you posting to a very old issue here.  As of now, the rebase dashboard is deprecated and you should use the rebase feature within the graph/repo history view -- use `r` to show the rebase menu over there.   `--autostash` is implemented long ago in that view.  👍

**Comment by arturolinares** [comment]
Oh, wow. I am returning to sublime after a few years and getting up to date. Thanks!
