### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by max-mykhailenko** [timbrel/GitSavvy#653]
Hi! I'm using gitsavvy almost from first releases and every new release decrease plugin performance. I can't fast add to index files on status dashboard, multiple pressing `s` will cause errors. Switching between status dashboard and branches also works slow.

How I can help with debug this problem?
How I can improve performance?

Used on iMac 2015
3.2 GHz Intel Core i5
16 GB 1867 MHz DDR3
AMD Radeon R9 M390 2048 MB

**Comment by stoivo** [comment]
I have been waiting to see an issue like this.

I don't know what's slow. I think the issue is that we make to many calls to git. We can see all calls to git in GitSavvy logging. Possibly I should improve it to add the duration. 

Can you record some log now with the current release and create a gist with it?

**Comment by max-mykhailenko** [comment]
Yes, no problem

**Comment by max-mykhailenko** [comment]
So I can't repeat errors in normal use right now, but if I try to stage/unstage/stage fast I got error about locked index.
`Unable to create '/.../.git/index.lock`
Same error also happens in normal using, I'll log it next time.

Log with "forced" bug is here.
https://gist.github.com/max-mykhailenko/9a61fe5ac5020959da075a98801f87e0

**Comment by max-mykhailenko** [comment]
Maybe it happens in larger repositories more often, I'll check it.

**Comment by stoivo** [comment]
I just looked at the log, this si all the called made aggregated
```
times comand
 4 git add -A
 3 git reset
 4 git rev-parse --show-toplevel
10 git log -n 1 --pretty=format:%h %s --abbrev-commit
10 git stash list
10 git status --porcelain -z
10 git status -b --porcelain
```
This doesn't mean much. I will add time.

**Comment by stoivo** [comment]
If you are running it GitSavvy from git repo you can check out my branch to include seconds. 

Otherwise, we will merge it to master in a couple of days. but not make a release before next month.

**Comment by max-mykhailenko** [comment]
I'll be waiting release, too many plans on this weekends

**Comment by stoivo** [comment]
We have made a minor release, can you record some log and see that includes seconds and post it here?

**Comment by max-mykhailenko** [comment]
Sometimes happens when closing files during pull.
https://gist.github.com/max-mykhailenko/ac4dad3a93096de0fa5ef9e8fc893e2f

**Comment by max-mykhailenko** [comment]
One more log with errors. Happens don't know when.
https://gist.github.com/max-mykhailenko/9329321312998b69abcc84cace227de3

**Comment by max-mykhailenko** [comment]
How I can find entries in log which corresponding to that errors?

**Comment by eden-lane** [comment]
I have the same issue, I guess. When I open diff from STATUS page and try to stage file, it throws this error:
```
`/usr/bin/git add --all -- <file_path>` failed with following output:

fatal: Unable to create '<project_path>.git/index.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
```

Maybe it would be a good idea to queue requests somehow?

**Comment by stoivo** [comment]
@randy3k  @asfaltboy

**Comment by asfaltboy** [comment]
I couldn't reproduce diff and stage that caused this error (tried simple and inline diffs). @eden-lane can you record a debug log and provide some details on your OS and machine details?
One thing I noticed in some recordings and in own tests, is that on Windows, GitSavvy commands run super slow compared to e.g MacOS

**Comment by eden-lane** [comment]
I'm on MacOS. Can't reproduce at home on pet projects, but I have this every time at work on our main and big project. I think this is the reason. Will try to reproduce and/or fix at Wednesday

**Comment by asfaltboy** [comment]
Great! Please, provide a debug log recording of the reproduced issue, that'll help us track down the issue (you can sanitize any project specific names with search replace first)

**Comment by eden-lane** [comment]
Not sure if it helps, but...
```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1072, in run_
    return self.run(edit)
  File "/Users/X/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package/core/interfaces/status.py", line 380, in run
  File "/Users/X/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package/core/git_mixins/stage_unstage.py", line 13, in stage_file
  File "/Users/X/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package/core/git_command.py", line 257, in git
GitSavvy.core.exceptions.GitSavvyError: `/usr/bin/git add --all -- var/www/s/Y/apps/app.es6` failed with following output:

fatal: Unable to create '/Users/X/Projects/Z/.git/index.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
```

So, my guess is git command takes too long and another command doesn't wait for first one to complete

**Comment by kaste** [comment]
This has been resolved; generally performance is now a main concern for every PR.
