### ISSUE TITLE
Determine syntax when .tmLanguage files are in use

### ISSUE THREAD

**Issue by stoivo** [timbrel/GitSavvy#666]
Determan the syntax files even it the syntax is not `.sublime-syntax`

Look at discussion on #661 
https://github.com/divmain/GitSavvy/pull/661#discussion_r121255072

Method to try out:
https://gist.github.com/mattst/71488757f2a2ca573c2d5e73af636d4c

@reagle, does inline diff open nicely on .py files for you?

**Comment by stoivo** [comment]
It can look like this when the syntax is selected ![screen shot 2017-06-12 at 21 35 03](https://user-images.githubusercontent.com/3492040/27051622-06c5fb3e-4fb7-11e7-8955-57b79a26a0bf.png)

**Comment by reagle** [comment]
No, I don't see that. The file type in the lower right status bar does say "GitSavvy Commit".

**Comment by stoivo** [comment]
Wrong command, 
1. Make some changes to a file
2. Open command panel
3. Find and run `git: diff current file inline`
