### ISSUE TITLE
Show word diff by default in normal diff view?

### ISSUE THREAD

**Issue by thezimmee** [timbrel/GitSavvy#752]
This is a question, not a bug; not sure where else to ask. But is there a way to have the normal diff view "show word diff" by default? So I don't have to hit the `w` key each time? Thanks.

**Comment by randy3k** [comment]
Not that I know of. Just curious: why word diff is useful, I don't understand what it offers.

**Comment by stoivo** [comment]
There is no setting like that. I would need to add a new setting for this.

I am very happy to hear that someone is using it. 

@randy3k 
 ![screen shot 2017-08-21 at 23 56 25](https://user-images.githubusercontent.com/3492040/29539928-5e2f4ac8-86cc-11e7-8778-e34947d21181.png)

**Comment by thezimmee** [comment]
Yes, I discovered it recently and absolutely love it! I am starting to use it more than the inline diff, it is so helpful. It would be nice to have this is a setting (default to show word diff), as well as to be able to default to hiding the whitespace. Thank you!!!

**Comment by kaste** [comment]
Closing as the word-diff feature/toggle has been removed.  It has been replaced by intra-line colorization which is on all the time.
