### ISSUE TITLE
git: status > f: Then  `l`, `L`, `H` do not work

### ISSUE THREAD

**Issue by taqtiqa-mark** [timbrel/GitSavvy#786]
## System Info
- Sublime Text 3143
- Platform: windows
- Arch: x64
- GitGutter Version could not be acquired!
- Install via PC: True
- git version 2.14.1.windows.1
- mdpopups 2.1.1
- markdown 2.6.9
- pygments 2.1a0
- jinja2 2.8

## Steps to reproduce, if possible
1. Open text file with unstaged git changes
1. Command: git:diff
1. place cursor on unstaged file
1. `f`
1. Tab: `DIFF: <filename>` opens
1. Place cursor in a chunk, `h` stages chunk
1. move to next chunk `.`, `H` does nothing. Console shows
````
`C:\Users\<snip>\AppData\Roaming\Git\bin\git.exe apply -R -` failed with following output:

<stdin>:9: trailing whitespace.
..... <text here>

````

1. move to a line in the chunk, `l`,`L` do nothing

**Comment by stoivo** [comment]
Works for me http://recordit.co/fABFMXDHjL
Can you supply debug log?
and possibly what changes are done to the file (whitespace changes)?

**Comment by taqtiqa-mark** [comment]
It may(?) be an issue with the GS parsing of the git diff/chunks.  Unfortunately I can't paste the source file publicly, but I could share it privately.

You should be able to see my public email on my Github profile.... email me if you want the (possible) culprit diff output and the raw file.

**Comment by taqtiqa-mark** [comment]
OKay, I think I have a file that may shed some light.  [Here](https://gist.github.com/taqtiqa-mark/8b40bb6787d5819a679e4fbfa6a2144a) is the source file and the diff I see in response to pressing `e` in th status dashboard.

When I press `l` in the status dashboard I see the following highlighted code:
1) All the text highlighted red, with dark red when the changes appear to be.
2) Immediately followed by all the text highlighted green, with dark green where than changes appear to be.

The ST3 Console output after `l` is also shown in the gist above

Hope this helps?

**Comment by stoivo** [comment]
Can you try again now? I think this might work now.

if it doesn't, check if the white spaces that should be there is there. To do so, open the diff, open settings for diff view with `ctrl+,` and set `draw_white_space` to `all`.

**Comment by kaste** [comment]
Long time has passed. The code for inline-diff has changed since, so I'm closing for now.

**Comment by taqtiqa-mark** [comment]
Apologies. I've moved to VS Code so lost track of this.
