### ISSUE TITLE
Highlight changed words in commit-diffs

### ISSUE THREAD

**Issue by AllanLRH** [timbrel/GitSavvy#800]
Would be nice if the commit-diffs (enabled by settings `"show_commit_diff": true`) would highlight the word differences in the displayed lines, like it's done in the "diff file inline"-mode:
![screen shot 2017-10-30 at 11 59 12](https://user-images.githubusercontent.com/2641327/32167657-db6e3a34-bd69-11e7-8712-fa4eaf3d79d1.png)

**Comment by stoivo** [comment]
Right now we need to rewrite the commit view.

What I would suggest for now is to run the command `git: diff cached` and then tap `w` to show word diff.

**Comment by AllanLRH** [comment]
Yes, that would work, but it's not quite as convenient… hope that you'll keep the suggestion in mind if you're rewriting the commit view some times in the future :)

**Comment by stoivo** [comment]
I will

**Comment by reagle** [comment]
I'm glad I found this instead of entering a new issue. I didn't know the `w` in diff view trick. 

In any case, absent a rewrite of the diff-view, is it possible to configure what kind of diff is shown in the commit view?

**Comment by kaste** [comment]
At the moment there is no w trick for the commit view. 

It is a technical question how the diff within the commit view can inherit much or most behavior of the stand-alone diff view.  I would like to avoid copy-pasting the code.
