### ISSUE TITLE
Region history

### ISSUE THREAD

**Issue by dufferzafar** [timbrel/GitSavvy#836]
Is there a way to view history of a particular region of lines?

Emacs has [this](https://github.com/jwiegley/git-undo-el/) which uses [`git log` output based on lines](https://github.com/jwiegley/git-undo-el/blob/master/git-undo.el#L104-L106).

The longer way to do this is via git log/blame manually but I feel this would be pretty useful to quickly go back in time.

**Comment by dufferzafar** [comment]
I wasn't aware of it before, but i think command `gs_show_current_file` is very related to this. 

I also worked out a very rudimentary plugin for myself: [see here](https://github.com/dufferzafar/sublime-text-3/blob/master/Packages/Git Region History/git_region.py#L1)

**Comment by kaste** [comment]
This has been implemented actually in 2.26.0
