### ISSUE TITLE
Cannot use WSL git.

### ISSUE THREAD

**Issue by milochristiansen** [timbrel/GitSavvy#841]
- Sublime Text version number: Build 3143
- Git version number: 2.7.4
- OS type and version: Windows 10 build 1709

The Windows Subsystem for Linux (WSL) ships with a copy of git. Unfortunately, GitSavvy does not seem to be able to use this version of git.

    error: Your Git binary cannot be found.  If it is installed, add it to your PATH environment variable, or add a `git_path` setting in the `User/GitSavvy.sublime-settings` file.

The error seems to be twofold:

1. GitSavvy does not try to use WSL git if it cannot find git for Windows.
2. GitSavvy does not transform paths (replace drive letters with "/mnt/[letter]/").

The first is fairly simple to workaround, just make a batch file that calls `bash.exe -c 'git %*'`, the second is the real issue here. Worse, a simple script to transform paths doesn't quite seem to be enough:

```
@echo off
setlocal enabledelayedexpansion

set find=Y:\
set replace=/mnt/y/
call set command=%%command:!find!=!replace!%%
set find=\
set replace=/
call set command=%%command:!find!=!replace!%%

::echo %command%

bash.exe -c 'git %command%'
```

This produces correct paths (for `Y:\`), but git reports:

```
fatal: Not a git repository (or any parent up to mount point /mnt/c)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```

I really, really do not want to install git for Windows. One install is bad enough.

**Comment by stoivo** [comment]
Ok, I haven't used windows in a long time. I will see if I can get my hands on one soon. 

I have read some comments that WSL is slow at some operations. So I don't know if you want to try to run sublime in WSL like the set up [here](https://nickjanetakis.com/blog/using-wsl-and-mobaxterm-to-create-a-linux-dev-environment-on-windows#wsl-conemu-and-mobaxterm-to-the-rescue). Not saying it's going to work but its idea.

> I really, really do not want to install git for Windows. One install is bad enough.

I respect your decision. Can you elaborate why you don't want to install git windows too? Because if you did that would fix this issue.

**Comment by milochristiansen** [comment]
Well, it boils down to me needing to maintain two sets of settings, etc.

If the fix isn't relatively easy (I don't really know what the GitSavvy internals look like so I don't really know how hard WSL would be to support), just say so and I'll go ahead and install git for Windows.

I'll have to set everything up twice, but honestly it isn't *that* big of a deal.

**Comment by stoivo** [comment]
Damn, it was actually fun to use windows again. WSL is cool and powerful. 

First, You can not run Windows Sublime and use git from WSL. It is software so everything is possible(but not this time). GitSavvy is doing other OS and file falls outside git so just replacing the git call isn't sufficient. 

Option one. Install git on windows. It will work, but you will have to git installation on your os. 

Option two. Install Sublime in the WSL. So you will have two sublime installations on the same OS. But you can easily share the config. 
```
# On WSL cd into  ~/.config/sublime-text-3/Packages
# move Config folder
mv User User.org
# Create a soft link to share the User config.
ln -s /mnt/c/Users/simon/AppData/Roaming/Sublime\ Text\ 3/Packages/User User 
```
We should only need to share the one folder https://packagecontrol.io/docs/syncing

I tried this setup and it works. Only one git but two sublimes. I have read some post that complains on speed inside WSL. It worked fast enought for me with the small repo I opened. 

So it is really up you,  
- two gits
- two sublimes
- not have it working at all

Either which option you choose, we are interested how works out.

**Comment by milochristiansen** [comment]
OK, I guess git for Windows, here I come :)

**Comment by stoivo** [comment]
:) Cool, Hope you will enjoy GitSavvy.

I will close the issue. Feel free to open another if you find some else

**Comment by mercurykd** [comment]
git for window - stash list slow...
it may be possible to make the integration wsl-git? sublime run through x-server looks ugly

**Comment by stoivo** [comment]
> it may be possible to make the integration wsl-git?

Sorry, It't just not. Maybe since this is a common case for windows users, maybe we can make the stash list togglable, like we do for remotes in branch interface?
If you'd like so, open an issue.

**Comment by mercurykd** [comment]
```
@echo off
setlocal enabledelayedexpansion
set command=%*
if not "%command%"=="" (
set find=C:/
set replace=/mnt/c/
call set command=%%command:!find!=!replace!%%
)
@echo %*>> %~dp0log.txt
For /F "Delims=" %%I In ('bash.exe -c 'git %command%'') Do Set V=%%~I
if not "%V%"=="" (
set find=/mnt/c/
set replace=C:/
call set V=%%V:!find!=!replace!%%
set find=\r
set replace=
call set V=%%V:!find!=!replace!%%
)
Echo !V!
```

feeling that almost earned ...
can not recognize the Unicode character after "status --porcelain -z"

Is the difference only in output parsing or is there something more significant?

**Comment by randy3k** [comment]
Check how GitGutter supports WSL
https://github.com/jisaacks/GitGutter/commit/dcbe842a2cbb02a4b13be1879ed2d5ff4bb9d1df

**Comment by stoivo** [comment]
And why not to do it https://github.com/jisaacks/GitGutter/issues/500

**Comment by kaste** [comment]
I'm not interested to implement this because it is way too slow.

**Comment by mercurykd** [comment]
Hey
some projects run in docker
docker on windows is usually installed in wsl
in order for docker not to slow down, you need to place the code in the wsl file system
and in this case git wsl is faster
it would be really cool for the project to override which git to use

**Comment by kaste** [comment]
You can tell GitSavvy which executable (the setting `git_path`) to use.  It is crucial that you open and edit `/mnt/c/.../somefile` paths in Sublime Text.  WSL paths must be supported in Sublime Text.  (We can't do *all* the path translations.)  (The paths must be transparent.  It can't work otherwise.)

**Comment by mercurykd** [comment]
git_path global setting?
for the project can be overridden?

**Comment by kaste** [comment]
Can be a project setting as well.  Not tested though.

**Comment by mercurykd** [comment]
> Can be a project setting as well. Not tested though.

can you write an example of overriding in the project settings?
not working yet, maybe I'm missing something

**Comment by kaste** [comment]
Projects settings:

```
{
    "settings":
    {
        "GitSavvy":
        {
        }
    }
}
```

**Comment by mercurykd** [comment]
works, but only after sublime restart(

**Comment by kaste** [comment]
Ah, now I remember.  Yeah, doesn't work for that setting because we cache a single value here internally.  So we would need a patch here to allow arbitrary many `(git_executable, git_version)` pairs.
