### ISSUE TITLE
Custom multi commands [Feature request] Quick add, commit and push

### ISSUE THREAD

**Issue by Kristinita** [timbrel/GitSavvy#842]
### 1. Request

It would be nice, if would be possible quickly add, commit and push changes to current branch of remote repository.

This behavior realized in [**Easygit**](https://github.com/silentninja/easygit), but this plugin have a bugs and no longer maintained.

### 2. Justification

Save time. `git add . && git commit -m "<commit description> && git push"` — most common git commands, that I use.

### 3. Expected behavior

I press shortcut → in opened input field I print commit description → <kbd>Enter</kbd> → changes successfully add, commit and push to current branch of remote repository.

![Easygit](https://imgur.com/Q2QNXrC.png)

Thanks.

**Comment by stoivo** [comment]
I think this is something custom for your use.

I think it would be better to create this with a custom command https://github.com/divmain/GitSavvy/blob/master/docs/custom.md

@randy3k @asfaltboy 
Currently custom commands only expect one command. How should we allow multiple commands.

A option. It is important that we keep it backward compatible
```
    {
        "caption": "git: create patch (from last commit)",
        "command": "gs_custom",
        "args": {
            "args": [
                ["add", "."],
                ["commit", "-m", "{PROMPT_ARG}"],
                ["push"],
            ]
        }
    },
```
Allow it to be nested arrays for mutipul commands?

**Comment by randy3k** [comment]
May be we should assign the command a different name such as `gs_multi_custom`?

**Comment by asfaltboy** [comment]
I like @randy3k 's approach, it's less "risky" if we keep the existing code untouched?

**Comment by thepulkitagarwal** [comment]
What about one of these options? 
<img width="418" alt="screen shot 2018-02-16 at 17 17 37" src="https://user-images.githubusercontent.com/6085092/36306376-6e7e739c-133d-11e8-8d0e-1ead1a0dc41d.png">

**Comment by andyghiuta** [comment]
As a workaround, I installed this plugin: https://packagecontrol.io/packages/Chain%20of%20Command which can chain multiple commands. Here's an example:
```
    {
        "caption": "git: fetch & merge otherremote/master",
        "command": "chain",
        "args": {
            "commands": [
                ["gs_custom", {
                    "output_to_panel": false,
                    "args": ["fetch", "otherremote"],
                    "start_msg": "Started fetch",
                    "complete_msg": "Fetch complete!"
                }],
                ["gs_custom", {
                    "output_to_panel": false,
                    "args": ["merge", "otherremote/master"],
                    "start_msg": "Started merge",
                    "complete_msg": "Merge complete!"
                }]
            ]
        }
    }
```
For ease of modifying User commands, you can use https://packagecontrol.io/search/Edit%20Command%20Palette

**Comment by asfaltboy** [comment]
We should, at the very least, document this workaround, PR are welcome!

**Comment by kaste** [comment]
Closing as not planned as it's use is too niche.
