### ISSUE TITLE
Stash in tab_order

### ISSUE THREAD

**Issue by mercurykd** [timbrel/GitSavvy#872]
because git stash list slow in windows

**Comment by asfaltboy** [comment]
Hi @mercurykd thank you for opening the ticket.

Could you kindly clarify the request? Do you for example want to add a _stash_ interface and include it in the `tab_order` rotation? Or do you have some issue with git stash and would like the ability to exclude it from the _status_ interface? Which git stash commands (or interface) is slow in which window? Perhaps we should fix that bug first?

**Comment by mercurykd** [comment]
I want to add a stash interface and include it in the tab_order rotation.
Because https://github.com/git-for-windows/git/issues/1235
https://github.com/divmain/GitSavvy/issues/868

@asfaltboy you speak russian?

**Comment by asfaltboy** [comment]
Hey @mercurykd I do speak Russian, but not very good 😊

That is an nasty bug with stash on windows that I wasn't aware of... I think our first priority in this case should be to disable the stash in status dashboard on demand, perhaps via a toggle setting.

We welcome all contributions, so please feel free to submit a pull-request if you'd like to try to fix it.

**Comment by mercurykd** [comment]
If the stash is turned off in the status dashboard, will it be possible to see it somehow?

**Comment by randy3k** [comment]
There are some commands in the command palette to manage stashes.

**Comment by kaste** [comment]
git stash has been reimplemented for Windows and is now fast enough
