### ISSUE TITLE
Wrong remote for nested repositories

### ISSUE THREAD

**Issue by niosus** [timbrel/GitSavvy#875]
If there are nested git repositories GitSavvy would only show status as if the files are in the parent remote ignoring the nested one.

For the sake of example, I have a git repository set up for my dot files in the home directory `~/`.
These two examples indicate the error:
1. If I create a new folder, say `~/NewRepo/` and initialize it with `git init` from within this folder, opening sublime and GitSavvy in this folder it will show me git status as if I am withing the repo in home directory.
2. Same holds if I open an existing project in a nested folder.

- Sublime Text version number: `3157`
- Git version number: `2.7.4`
- OS type and version: `Ubuntu 16.04`

Please tell me if you need a log or something else.

**Comment by stoivo** [comment]
Can you create a script which creates the case?

**Comment by niosus** [comment]
Sorry @stoivo I don't fully understand what do you mean by a script? Could you elaborate a bit more?

**Comment by randy3k** [comment]
I cannot reproduce it.
![feb-27-2018 18-13-08](https://user-images.githubusercontent.com/1690993/36760715-f429a106-1be9-11e8-9f8c-01baf12e18bf.gif)

The root directory and the `foo` directory are both git repos while the `foo` directory has branch `foo` checked out.

**Comment by niosus** [comment]
Ok, I have to clarify here that by "open" I mean open from a terminal, e.g. `subl *.sublime-project`.
Let me think how to make sure you guys can reproduce this. Sorry for not being very clear.

**Comment by kaste** [comment]
Closing as stale
