### ISSUE TITLE
Add a notice about "run_in_thread" in custom commands documentation

### ISSUE THREAD

**Issue by mnieber** [timbrel/GitSavvy#904]
I crippled my GitSavvy workflow by adding some custom commands that *should* run in their own thread but didn't. Suddenly, many GitSavvy screens stopped responding to keyboard input, forcing me to restart sublime (until I figured out what was wrong).

To help other people to avoid these issues, it would be good to add a clear notice to the documentation that you should pay attention to this flag :-).

**Comment by randy3k** [comment]
Um, I believe many git operations cannot be parallelised.

**Comment by mnieber** [comment]
I'm using this flag for my custom `gitk` and `git gui` command, so I suppose the notice would only apply for commands that fire up long-lived processes.

In any case I'm happy my GitSavvy behaves well again!

**Comment by asfaltboy** [comment]
We mention this in the full ["Custom commands" documentation here][1]

**Comment by mnieber** [comment]
This is just how I would do it, but I would make 'run_in_thread' the first item in the list, and add "you should *set this flag to true if the command runs a long-lived process*, or otherwise GitSavvy will hang".

(it's immediately clear from the current docs that giving this flag the wrong value can mess everything up)

**Comment by asfaltboy** [comment]
Thank you for explaining. I am definitely for expanding the description for the argument, and we can also explain that only `false` / `true` are valid values.

By the way, if you'd like to help out, we appreciate contributions!

**Comment by mnieber** [comment]
Okay, I will send a PR for updating the docs!

**Comment by stoivo** [comment]
We would love to see your PR ❤️

**Comment by mnieber** [comment]
Sorry, it's still on my todo list (I will get to it!)

**Comment by kaste** [comment]
Closing as you actually made the PR/change.
