### ISSUE TITLE
Blame current file concerning HEAD

### ISSUE THREAD

**Issue by mercurykd** [timbrel/GitSavvy#929]
- 3161
- 2.17.0.windows.1
- win10x64

Blame current file gives the choice of commits in which the file was affected, but after merging the branches it is unclear which commit was taken as the basis. It is necessary to look git blame concerning HEAD.

**Comment by randy3k** [comment]
I thought the first commit is always the head, isn’t it?

**Comment by mercurykd** [comment]
If there was a merge with the conflicts, it may turn out that the last commit of the offered menu does not reflect the current state of the file, because the file state was selected earlier in the conflict, and the merge commit in the menu is not displayed.

**Comment by mercurykd** [comment]
Perhaps you misunderstood me, the difficulties of translation. Conflicts have already been resolved. Git blame shows who wrote this or that line. When you select gitsavvy git blame current file, it shows a list of commits for this file, but changes in this commit could be dropped when merging with another branch, that is, changes were made from the older commit during fusion. Thus, the first commit on top of the git blame current file command will not match HEAD.

**Comment by mercurykd** [comment]
![image](https://user-images.githubusercontent.com/30900414/38772350-9175fd90-4045-11e8-84e7-e5011f4f139f.png)

**Comment by randy3k** [comment]
So passing `-m` to `git log` should fix it.

**Comment by randy3k** [comment]
Could you share your repo with us? I was trying to reproduce your result but it correctly shows the merge commit as HEAD.

<img width="643" alt="screen shot 2018-04-14 at 9 24 52 pm" src="https://user-images.githubusercontent.com/1690993/38774002-5e8ba1d4-402a-11e8-91a3-730a24bf5213.png">

**Comment by mercurykd** [comment]
https://github.com/mercurykd/test

**Comment by randy3k** [comment]
I got this with git 2.16.2
```
(randyimac)-test$ git log -- 1.txt (master)
commit 8848b731c0b960337f5c55fd1473f54a4566d835 (HEAD -> master, origin/master, origin/HEAD)
Merge: eb640ff 462289f
Author: mercury <mercury.kd@gmail.com>
Date:   Sun Apr 15 00:33:19 2018 +0400

    Merge branch 'old-branch'
    
     Conflicts:
            1.txt

commit eb640ffbf748cfa4fb531b8e18f2fe75bf64515b
Author: mercury <mercury.kd@gmail.com>
Date:   Sun Apr 15 00:31:57 2018 +0400

    3 commit in master

commit 462289f08c60b83893752f26dda71ce97f5d35ca
Author: mercury <mercury.kd@gmail.com>
Date:   Sun Apr 15 00:31:16 2018 +0400

    2 commit in old-branch

commit f4117b9f332b493f5b4422844e37334191c38f43
Author: mercury <mercury.kd@gmail.com>
Date:   Sun Apr 15 00:30:03 2018 +0400

    init

```
It seems that it is an issue of git, I cannot reproduce it with the most updated version of git.

**Comment by mercurykd** [comment]
Yes, could you add the git blame option without specifying a commit?

**Comment by randy3k** [comment]
It should work by just defining the following (untested) in your user `Default.sublime-commands`

```
    {
        "caption": "git: blame current file at HEAD",
        "command": "gs_blame",
        "args": {"commit_hash": "HEAD"}
    }
```

**Comment by stoivo** [comment]
What version of git are you using @mercurykd ?

**Comment by mercurykd** [comment]
2.17.0.windows.1

**Comment by randy3k** [comment]
I still cannot reproduce with git 2.17.0 on macOS.
![screen shot 2018-04-18 at 12 55 05 pm](https://user-images.githubusercontent.com/1690993/38946558-cfefb3f8-4307-11e8-8a6a-130410608460.png)

**Comment by asfaltboy** [comment]
@mercurykd maybe [WSLGit][1] could be a nice workaround. Could you try [downloading it][2] and then defining the path to the binary in [the settings][3] as in:

https://github.com/divmain/GitSavvy/blob/1196f7819ebbc2b8de71222481c23ea58b4553ec/GitSavvy.sublime-settings#L15-L23

[1]: https://github.com/andy-5/wslgit
[2]: https://github.com/andy-5/wslgit/releases
[3]: https://github.com/divmain/GitSavvy/blob/master/docs/README.md#editing-settings

**Comment by stoivo** [comment]
The problem with WSLGit is file paths. When we want to read it form disk.

**Comment by asfaltboy** [comment]
Hmm good point @stoivo ... I'm not even sure where to start mapping it out

**Comment by stoivo** [comment]
Open an issue on Windows on git?

**Comment by mercurykd** [comment]
> The problem with WSLGit is file paths. When we want to read it form disk.

I can be wrong, but in my opinion there is only a difference in the name of the drive letter, for example, instead of C:\ => /mnt/c/, and reverse the backslashes to direct ones.

**Comment by asfaltboy** [comment]
Reply to: https://github.com/divmain/GitSavvy/issues/929#issuecomment-382561367

There is an interesting development with regards to windows/linux paths over here:
https://github.com/andy-5/wslgit/issues/12

Reply to: https://github.com/divmain/GitSavvy/issues/929#issuecomment-382569439

I'm guessing we could try to "quote" the arguments to `--format` (in either single or double quotes).  E.g this sort of patch:

```patch
 core/git_mixins/branches.py | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/core/git_mixins/branches.py b/core/git_mixins/branches.py
index 1b8f45e..67ca703 100644
--- a/core/git_mixins/branches.py
+++ b/core/git_mixins/branches.py
@@ -23,7 +23,7 @@ class BranchesMixin():
         """
         stdout = self.git(
             "for-each-ref",
-            "--format=%(HEAD)%00%(refname)%00%(upstream)%00%(upstream:track)%00%(objectname)%00%(contents:subject)",
+            "--format='%(HEAD)%00%(refname)%00%(upstream)%00%(upstream:track)%00%(objectname)%00%(contents:subject)'",
             "--sort=-committerdate" if sort_by_recent else None,
             "refs/heads",
             "refs/remotes")
```

If someone with ready access to a windows machine can try it out it'll be great.
