### ISSUE TITLE
Fixup should be an option in status tab

### ISSUE THREAD

**Issue by reagle** [timbrel/GitSavvy#933]
Alongside amend, it'd be nice if fixup was an option on the status page. Sometimes when I'm on that page and realize I'd like to fixup instead of commit or amend, I have to exit it, go back to the document, and do a quick fixup.

**Comment by randy3k** [comment]
I think that you could stage the related files and use `git: fixup from stage`.

**Comment by reagle** [comment]
That's true. And [f] is already taken as a shortcut for diffing. Still something worth thinking about.

**Comment by asfaltboy** [comment]
So many shortcuts but so few keys on the  ⌨️ 😆

**Comment by reagle** [comment]
Well... now that you mention it, `[x]` is still available :-).

**Comment by reagle** [comment]
BTW:  When I use the command palette, I wonder why these two fixup options are so far apart? I'd expect them to be right next to each other. 

<img width="550" alt="screen shot 2018-04-20 at 7 10 16 am" src="https://user-images.githubusercontent.com/596814/39048077-3f67190c-446a-11e8-981e-a2c04afde56d.png">

**Comment by reagle** [comment]
Sounds like a good idea.

**Comment by reagle** [comment]
Still sounds like a good idea  :)

**Comment by kaste** [comment]
Closing as not planned; you could for example just prepare the commit message, then `fix<tab>` to prepare a fixup commit.  It is also an option in the graph view (in the `r`ebase menu).  And available whenever you see a commit/patch:  e.g. open up a line history then `f` to initiate a fixup.

Note that the "quick fixup" commands are deprecated as they rely on the Python (re)-implementation of "rebasing".
