### ISSUE TITLE
How can I perform git:pull if I have a key/pw set?

### ISSUE THREAD

**Issue by Azzhoe** [timbrel/GitSavvy#937]
I have a publickey or pw set for pulling and pushing via get. So how can I get by this with this addon for Sublime?

**Comment by stoivo** [comment]
Plattform please.

**Comment by normallywho** [comment]
I just got set up with GitSavvy and ran into this. I'm using 64-bit Windows and I'm connecting to a repo on BitBucket. I have a key that I need to provide a password to in order to push/pull to the repo.

**Comment by asfaltboy** [comment]
IIRC if you have a password set, sublime will not let you provide it to git (and you probably don't want to send an unencrypted password through sublime anyway). Instead, consider using [a credential store][0] to cache the password.

[0]: https://git-scm.com/book/en/v2/Git-Tools-Credential-Storage

**Comment by kaste** [comment]
Closing, stale
