### ISSUE TITLE
Invalid continuation byte (git: Commit)

### ISSUE THREAD

**Issue by Rigui73** [timbrel/GitSavvy#942]
**- Sublime Text version:** 3.1.1 Build 3176
**- Git version:**  2.17.0.windows.1
**- OS:** Windows 10 Pro 64bits
**- Console error output:**

_Please report this error to GitSavvy:_

_'utf-8' codec can't decode byte 0xe0 in position 288: invalid continuation byte_

**- Description:**
Starting a new project, perform the commands staged and unstaged well up in the commit when giving "CTRL + ENTER" to add it jumps the error.

Note*: has happened to me in the first commit.

**- Steps to reproduce:**
Step 1: stage all unstaged and untracked files
Step 2: git commit

**Comment by stoivo** [comment]
Can you make a small screen recording when to demo the bug?

**Comment by Rigui73** [comment]
![2018-05-22-15-37-05](https://user-images.githubusercontent.com/19810439/40367864-b01c80cc-5dda-11e8-99b2-e7c756343cf7.gif)

**Comment by stoivo** [comment]
I cant reproduce. Can you upload the files you want to commit?
And try to commit just one file with the content `tmp`?

**Comment by Rigui73** [comment]
If I try to upload a single file with content "tmp", the same error occurs. I upload the file that I use but I do not think it is the problem because if I generate new projects, the same error happens to me, but if I work with previously created projects, they work without problems.

Thanks for your time.

[index.zip](https://github.com/divmain/GitSavvy/files/2035726/index.zip)

**Comment by stoivo** [comment]
Your right It was nothing to do with the file.

Do you get any traceback when exception occurs?

**Comment by stoivo** [comment]
Can you uninstall GitSavvy from Package Control and drop this file in packages folder to manually install my patch version? Should add backtrace from the exception.

[GitSavvy.sublime-package.zip](https://github.com/divmain/GitSavvy/files/2038242/GitSavvy.sublime-package.zip)
