### ISSUE TITLE
Using GitSavvy as difftool

### ISSUE THREAD

**Issue by franciscolourenco** [timbrel/GitSavvy#953]
Is there a way to use Gitsavvy as a difftool?

The use case would be able to migrate away from Sublime Text while still being able to keep use GitSavvy in a reasonably integrated way without having to build custom integrations.

**Comment by asfaltboy** [comment]
Thanks for opening a ticket @franciscolourenco . I imagine (from your other ticket) that you are  VS-Code user and would like to launch certain views/dashboards from VS Code.

Could you please elaborate a bit more on your use case, e.g:

- Which views are you most interested in launching from VS Code?
- Could you give an example of one or two "user flows" where GitSavvy is launched externally?

**Comment by franciscolourenco** [comment]
https://git-scm.com/docs/git-difftool

status view and inline diff view

**Comment by kaste** [comment]
This is probably doable and maybe not that difficult. You can tell via cli to execute a command `subl --command` ref http://docs.sublimetext.info/en/latest/command_line/command_line.html#options

I'm not interested in writing that, but I would like to see it. Just do it! and ping us

**Comment by kaste** [comment]
Closing as "wontfix" esp. because you need to write a wrapper script for the command line which we couldn't host here anyway.  If we need to add a common `ApplicationCommand` as receiver we're 👍.
