### ISSUE TITLE
Permission denied for GitHub

### ISSUE THREAD

**Issue by JanaJarecki** [timbrel/GitSavvy#962]
Hi,

apologies, if this is trivial, but I am new to GitSavvy.

Trying to push to my remote `cogsciutils` claims that the permission is denied. However
-  `git push cogsciutils master` works from the command line.
-  The authentification with the access token works from the command line.

What could I be doing wrong such that it does not work from within Sublimetext/GitSavvy?

The error reads:

```
C:\Program Files\Git\cmd\git.EXE push cogsciutils master failed with following output:

Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
````

- Sublime Text version number _3.1.1_
- Git version number _2.11.0.windows.1_
- OS type and version _Win 10_
- Console error output (see above)
- A description of the problem. (see above)
- Steps to reproduce, if possible (no)
- If the bug is caused by a failing command, [include a debug log](docs/debug.md#providing-a-debug-log):

```
[
  {
    "command": [
      "remote", 
      "-v"
    ], 
    "stdin": null, 
    "type": "git", 
    "stdout": "cogsciutils\tgit@github.com:JanaJarecki/cogsciutils.git (fetch)\ncogsciutils\tgit@github.com:JanaJarecki/cogsciutils.git (push)\norigin\tgit@github.com:JanaJarecki/cogsciutils.git (fetch)\norigin\tgit@github.com:JanaJarecki/cogsciutils.git (push)\n", 
    "stderr": "", 
    "seconds": 0.04687786102294922
  }, 
  {
    "command": [
      "branch", 
      "--no-color"
    ], 
    "stdin": null, 
    "type": "git", 
    "stdout": "* master\n", 
    "stderr": "", 
    "seconds": 0.04686403274536133
  }, 
  {
    "command": [
      "branch", 
      "--no-color"
    ], 
    "stdin": null, 
    "type": "git", 
    "stdout": "* master\n", 
    "stderr": "", 
    "seconds": 0.04687619209289551
  }, 
  {
    "command": [
      "push", 
      null, 
      null, 
      "cogsciutils", 
      "master"
    ], 
    "stdin": null, 
    "type": "git", 
    "stdout": "", 
    "stderr": "Permission denied (publickey).\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\n", 
    "seconds": 1.080941915512085
  }, 
  {
    "type": "error", 
    "error": "'`C:\\\\Program Files\\\\Git\\\\cmd\\\\git.EXE push cogsciutils master` failed with following output:\\n\\nPermission denied (publickey).\\r\\nfatal: Could not read from remote repository.\\n\\nPlease make sure you have the correct access rights\\nand the repository exists.\\n'"
  }
]
```

**Comment by stoivo** [comment]
This is a rather commen issue. The problem is that the public key is not added to the ssh agent that sublime uses. 

Read https://github.com/divmain/GitSavvy/issues/243, it should help.

**Comment by JanaJarecki** [comment]
Hi stoivo, hi asfaltboy,

thanks for the feedback.

@stoivo In #243 it says how to fix the path to git, mayabe I am misreading the thread, where does it say how to add the ssh agent to sublime's ssh agent?

Paths are okay

**Windows PATH**
```
C:\Program Files\Git\cmd`
```

**In Sublime**
```
>>> import shutil; shutil.which('git')
C:\\Program Files\\Git\\cmd\\git.EXE
```

@asfaltboy
Git finds the key alright (checked as described here: https://help.github.com/articles/checking-for-existing-ssh-keys/), if this is a check that works? I am not aware of using anything special (I dont know Pageant).

**Comment by asfaltboy** [comment]
When you say that "The authentication with the access token works from the command line" . Can you provide more details on that command line environment: are you running the windows cmd.exe, power-shell, "git bash" or another windows command prompt application?

It might be useful to compare all the environment variables in both the above command prompt and sublime to see what differs ([in python `import os; print(os.environ)`][1] and in windows command prompt use `cli`).

Lastly, you may want to [update to latest git for windows][2] build (2.18 currently).

[1]: https://docs.python.org/3.5/library/os.html#os.environ
[2]: https://git-scm.com/download/win

**Comment by JanaJarecki** [comment]
Hi,
thanks for the patience, I checked all of the above without luck. I am a bit lost, really.

> Lastly, you may want to update

Updated to Git 2.18 for windows. The issue prevails, unfortunately. 

> It might be useful to compare all the environment variables

One variable was different, PROMPT=$P$G, which I added to sublime. Still not pushing to GitHub from GitSavvy, but from cmd. (Some variables were not capitalized in sublime, but that should not matter).

> When you say that "The authentication with the access token works from the command line" . Can you provide more details on that command line environment: are you running the windows cmd.exe, power-shell, "git bash" or another windows command prompt application?

Sure, I am running in the cmd.exe in Windows

**Comment by JanaJarecki** [comment]
Hi,
thanks for the patience, I checked all of the above without luck. I am a bit lost, really.

> Lastly, you may want to update

Updated to Git 2.18 for windows. The issue prevails, unfortunately.

> It might be useful to compare all the environment variables

One variable was different, PROMPT=$P$G, which I added to sublime. Still not pushing to GitHub from GitSavvy, but from cmd. (Some variables were not capitalized in sublime, but that should not matter).

> When you say that "The authentication with the access token works from the command line" . Can you provide more details on that command line environment: are you running the windows cmd.exe, power-shell, "git bash" or another windows command prompt application?

Sure, I am running in the cmd.exe in Windows

**Comment by asfaltboy** [comment]
By the way, if you can, join us in the [gitter chat](https://gitter.im/divmain/GitSavvy), we may be able to debug faster over there.

I suspect it's something to do with the authentication method, are you using a password protected key (Sublime **cannot** prompt you for a key password - see #285), or maybe you are using two factor authentication (try [GCM][2])?

[2]: https://github.com/Microsoft/Git-Credential-Manager-for-Windows

**Comment by JanaJarecki** [comment]
A full update of everything eventually solved it, thank you guys for all the help /closing the issue.
