### ISSUE TITLE
Is it possible to show the underneath git commands that gitsavvy is using?

### ISSUE THREAD

**Issue by yangshuairocks** [timbrel/GitSavvy#979]
Hi, I want to know if is it possible to show the underneath git commands that gitsavvy is using (like `git status`, `git log` etc.)? It is helpful for people to learn git if people can see this. Thanks.

**Comment by stoivo** [comment]
Yes, record the log and then view it. 
https://github.com/divmain/GitSavvy/blob/master/docs/debug.md#gitsavvy-view-recorded-log
Does that work?

**Comment by yangshuairocks** [comment]
Yes, this has what I want but in a unintuitive way. Is it possible to display the actual git command (not the parsed JSON object) to a panel or at least to the Sublime console? That will make it more usable.

**Comment by stoivo** [comment]
Do you want the STDIN and STDOUT too?
And the log is not the the parsed date but the raw date but into a json. 
Then look like 
```
  {
    "command": [
      "config", 
      "user.email"
    ], 
    "stderr": "", 
    "stdout": "simon.toivo@telhaug.no\n", 
    "type": "git", 
    "seconds": 0.009479999542236328, 
    "stdin": null
  }, 
```
At this entry the command is `git config user.email`

```
  {
    "command": [
      "log", 
      "--max-count=6000", 
      null, 
      null, 
      "--format=%h%n%H%n%s%n%an%n%ae%n%at%x00%B%x00%x00%n", 
      "--author=Simon <simon.toivo@telhaug.no>", 
      null, 
      null, 
      null, 
      null, 
      null, 
      null, 
      null, 
      null, 
      null, 
      null, 
      null, 
      null, 
      null, 
      null
    ], 
    "stderr": "", 
    "stdout": "7f4a9b90c.....", 
    "type": "git", 
    "seconds": 0.3013949394226074, 
    "stdin": null
  }, 
``` 
the command is `git log --max-count=6000 --format=%h%n%H%n%s%n%an%n%ae%n%at%x00%B%x00%x00%n --author=Simon <simon.toivo@telhaug.no>`

**Comment by yangshuairocks** [comment]
Yes i know it's just the command in JSON format. If we can see them in both STDIN and STDOUT that will be great.

**Comment by stoivo** [comment]
Si, since you can get it if you want it I will not spend my tome coding this.
If you are interested I can help you make a PR for it. I will be happy to merge it 👍 

You need to create a setting `display_git_command_in_console` or something else. Default value should be false. 
Then in look in https://github.com/divmain/GitSavvy/blob/9ec1cc44455a11e1dfef89629fc7c4e8c01f6a57/common/util/debug.py#L40-L42. When the message type is git then do som printing.

**Comment by kaste** [comment]
If you enable `GitSavvy logging` it will now print the commands to the standard Sublime console. It may be that we instead push them to a separate panel but for now ... we have this.
