### ISSUE TITLE
Prevent opening commit window when there is nothing to commit

### ISSUE THREAD

**Issue by oerp-odoo** [timbrel/GitSavvy#980]
Is there an option to prevent commit message window from opening when there is nothing to commit? Like if you have not staged anything yet, but write `git commit`, it should not open window.

That is standard git behavior. 
Or is this intended with GitSavvy to not check if there is anything to commit or not.

I mean you can think that you staged something, then write commit message and try to commit it, but only then you will know there was nothing to commit in a first place, which could be misleading.

**Comment by stoivo** [comment]
I agree what we should do something to be closer to gits interface. I need to think about the UX

**Comment by randy3k** [comment]
We may just need to check the number of staged files. (depends on the [values][1] of `include_unstaged` and `amend`)

[1]: https://github.com/divmain/GitSavvy/blob/7b82d7e2be4850b0e0e8d17061343158bd4251ff/core/commands/commit.py#L55-L55

**Comment by oerp-odoo** [comment]
Currently as workaround, when I get commit message window I try to commit it without any message to get response from git. Then by response it is clear if there was nothing to commit or just expected empty message error.

It is not very clean workaround, but used with hooks, lets me know outcome before writing commit (cause pre-commit is also triggered after commit is being saved).

If there is no easy way to implement proper enhancement, maybe add an option to trigger `do_commit` (default keybind is control+enter) on empty commit message? It could be option to enable/disable it (depending if someone needs it or not). I would gladly use it, cause it would also help with git hooks too.

**Comment by oerp-odoo** [comment]
https://github.com/divmain/GitSavvy/pull/982 solves this problem, so I'm closing it.

**Comment by randy3k** [comment]
As discussed in this thread: https://github.com/divmain/GitSavvy/pull/1070

We are going to [revert](https://github.com/divmain/GitSavvy/pull/1071) the commit for checking "nothing to commit" in dev and discuss a better solution later.
