### ISSUE TITLE
Warning when trying to amend pushed commit?

### ISSUE THREAD

**Issue by oerp-odoo** [timbrel/GitSavvy#991]
Is there an option to warn you about amending commit which was already pushed?

I thought this was included in this option: `"prompt_before_destructive_action": true,`

But it does not warn me. I will know that amended such commit, when I try to push without `--force` option only. Which is kind of late.

P.S. Maybe I was used to SublimeGit, which had that feature on default :)

**Comment by randy3k** [comment]
there is not this option for now. but it’s a good feature request. i personally encountered the same situation a few times

**Comment by kaste** [comment]
I don't want to implement this as amending, rebasing and what else on feature branches is just too common practice.
