### ISSUE TITLE
Git push after deleting remote branch does nothing.

### ISSUE THREAD

**Issue by stevage** [timbrel/GitSavvy#993]
1. Checkout a remote branch as local.
2. Delete the remote branch (ie, `git push --delete origin blah`)
3. Status page correctly shows "Remote branch is gone"
4. Now do "git: push". Nothing happens at all.

What I think should happen:

Same as doing "git: push to branch name" (ie, prompting for remote and branch name), which worked just fine.

**Comment by randy3k** [comment]
Thanks for the report. I can reproduce it. It is addressed by a0e46a5

**Comment by kaste** [comment]
The comment above and the current code suggest that this has been fixed without closing the issue.
